import ZkFormal.V2.PubIdx

/-! Indexed public-segment records and the assembly bridge to `PubIdx`.
Prefix and record position are generated by the verifier, not encoded as bytes. -/
namespace ZkFormal.V2
open ZkFormal.Air

section
variable {F : Type} [Lean.Grind.CommRing F] [DecidableEq F] [PubVal F]

/-- The fingerprint width includes all generated message fields. -/
theorem PubSeg.record_length (s : PubSeg) (pub : List F) (j : Nat) :
    (s.record pub j).length = s.messageWidth := by
  cases h : s.indexBase <;>
    simp [PubSeg.record, PubSeg.messageWidth, h, Nat.add_assoc, Nat.add_comm, Nat.add_left_comm]

/-- The default settings preserve the original byte-only record semantics. -/
theorem PubSeg.record_plain (s : PubSeg) (pub : List F) (j : Nat)
    (hp : s.msgPrefix = []) (hi : s.indexBase = none) :
    s.record pub j = (List.range s.width).map (fun c => pub.getD (s.startOffset pub + j * s.width + c) 0) := by
  simp [PubSeg.record,hp,hi]

/-- A payload whose serialized bytes are in the segment produces the exact
indexed record expected by link proofs. -/
theorem PubSeg.record_indexed (s : PubSeg) (pub : List F) (j off : Nat) (payload : List Nat)
    (hi : s.indexBase = some off) (hw : payload.length = s.width)
    (hb : ∀ c, c < s.width → pub.getD (s.startOffset pub + j * s.width + c) 0 =
      @Nat.cast F Lean.Grind.Semiring.natCast (payload.getD c 0)) :
    s.record pub j = (s.msgPrefix ++ [off+j] ++ payload).map
      (fun n => @Nat.cast F Lean.Grind.Semiring.natCast n) := by
  simp only [PubSeg.record,hi,List.map_append,List.map_cons,List.map_nil]
  congr 1
  apply List.ext_getElem (by simp [hw])
  intro c hc hc'
  simp only [List.getElem_map,List.getElem_range]
  have hc0 : c < s.width := by simpa using hc
  rw [hb c hc0,List.getD_eq_getElem?_getD,List.getElem?_eq_getElem (by omega),Option.getD_some]

private theorem tagged_on (bus : Nat) (side : Bool) (L : List (List F)) (b : Nat) (s : Bool) :
    ((L.map (fun m => (bus,side,m))).filter
      (fun x => decide (x.1=b ∧ x.2.1=s))).map (fun x => x.2.2) =
      if bus=b ∧ side=s then L else [] := by
  by_cases h : bus=b ∧ side=s <;>
    simp [List.filter_map,h,List.map_map,Function.comp_def]

/-- Assembly may prove segment contents independently; their exact family of
records then supplies every public-bus count at once, including repeated records. -/
def pubIdx_of_segments (AP : AirP) (pub : List F) (enc : Nat → F)
    (records : PubSeg → List (List Nat))
    (hrecords : ∀ s ∈ AP.pubSegs, s.msgs pub = (records s).map (·.map enc)) :
    PubIdx AP pub enc := by
  let recs := fun b side => (AP.pubSegs.filter (fun s => decide (s.bus=b ∧ s.send=side))).flatMap records
  apply PubIdx.ofPerm recs
  intro b side
  apply List.Perm.of_eq
  unfold pubOn pubMsgs recs
  have helper : ∀ ss : List PubSeg,
      (∀ s ∈ ss, s.msgs pub = (records s).map (·.map enc)) →
      ((ss.flatMap (fun s => (s.msgs pub).map (fun m => (s.bus,s.send,m)))).filter
        (fun x => decide (x.1=b ∧ x.2.1=side))).map (fun x => x.2.2) =
      ((ss.filter (fun s => decide (s.bus=b ∧ s.send=side))).flatMap records).map (·.map enc) := by
    intro ss
    induction ss with
    | nil => intro _; rfl
    | cons s ss ih =>
      intro hm
      simp only [List.flatMap_cons,List.filter_append,List.map_append]
      rw [tagged_on,ih (fun t ht => hm t (List.mem_cons_of_mem _ ht))]
      by_cases hs : s.bus=b ∧ s.send=side
      · simp [List.filter_cons,hs,hm s (by simp)]
      · simp [List.filter_cons,hs]
  exact helper AP.pubSegs hrecords

end
end ZkFormal.V2
