//! `native-lean` verifier route: the judge (not the candidate) builds the
//! native `verify` executable from the candidate's Lean verifier model with
//! the governed Lean compiler, so the binary digest spliced into the expected
//! statement (`.nativeTrusted <binDigest> <toolchainId> <model>`) is a judge
//! build output. The binary ↔ model edge is *trusted* (Lean compiler +
//! runtime in the TCB), never *checked*.

use arena_types::Digest;
use serde::{Deserialize, Serialize};

/// Judge-owned `main` wrapper implementing the CONTRACTS §4 `verify` CLI on
/// top of an `ArenaCore.OracleVerifier` model. `{{model_module}}` and
/// `{{model_decl}}` are replaced by validated identifiers (never free text).
/// `pub` is `public_dir/public.bin` (same convention as the npai-v1 route).
pub const ARENACORE_MAIN_TEMPLATE: &str = r#"import ArenaCore.Verifier
import {{model_module}}

/-! GENERATED by the arena judge: native `verify` entry point (CONTRACTS §4).
Exit 0 = accept, 1 = reject, 2 = usage/IO error. -/

def arenaVerifyParse : List String → Option (String × String × String)
  | ["--public", p, "--claim", c, "--proof", q] => some (p, c, q)
  | _ => none

def main (args : List String) : IO UInt32 := do
  match arenaVerifyParse args with
  | none =>
    IO.eprintln "usage: verify --public DIR --claim FILE --proof FILE"
    return 2
  | some (p, c, q) =>
    try
      let pub ← IO.FS.readBinFile (System.FilePath.mk p / "public.bin")
      let cb ← IO.FS.readBinFile c
      let pb ← IO.FS.readBinFile q
      let ok := ArenaCore.OracleVerifier.deployed {{model_decl}} pub.toList cb.toList pb.toList
      return if ok then 0 else 1
    catch e =>
      IO.eprintln s!"verify: {e}"
      return 2
"#;

/// Configuration of the native-lean route for one check.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct NativeLeanRoute {
    /// Candidate model declaration (`formal.verifier_model`), e.g. `Candidate.Model.verify`.
    pub model_decl: String,
    /// Module declaring it (`formal.verifier_model_module`), e.g. `Candidate.Model`.
    pub model_module: String,
    /// Judge-generated instantiation module/declaration:
    /// `def <inst_decl> : Prop := <expected decl> <model_decl>`.
    pub inst_module: String,
    pub inst_decl: String,
    /// Judge-owned `main` template (see `ARENACORE_MAIN_TEMPLATE`).
    pub main_template: String,
    /// Expected Lean type of the model and the trusted module declaring it
    /// (used for the judge stub that the wrapper is cross-checked against).
    pub model_type: String,
    pub model_type_module: String,
    /// Toolchain id spliced into the statement (default: the pinned Lean toolchain).
    pub toolchain_id: String,
    /// Digest of a native verifier the *candidate* built/shipped, if any. It
    /// must equal the judge build (otherwise ARTIFACT_BINDING fails: no route
    /// admits a candidate-built native binary).
    pub candidate_binary_digest: Option<Digest>,
}

impl NativeLeanRoute {
    pub fn new(model_decl: &str, model_module: &str) -> Self {
        NativeLeanRoute {
            model_decl: model_decl.into(),
            model_module: model_module.into(),
            inst_module: "ArenaExpectedInst".into(),
            inst_decl: "ArenaExpectedInst.expectedType".into(),
            main_template: ARENACORE_MAIN_TEMPLATE.into(),
            model_type: "ArenaCore.OracleVerifier".into(),
            model_type_module: "ArenaCore.Verifier".into(),
            toolchain_id: format!("{}+leanc", crate::toolchain::lean_toolchain()),
            candidate_binary_digest: None,
        }
    }
}

/// Verifier routes the formal checker knows about.
// Constructed once per check; boxing would only add noise at call sites.
#[allow(clippy::large_enum_variant)]
#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub enum VerifierRoute {
    /// Statement fully determined by literals (e.g. `.interp <bytecode digest>`).
    #[default]
    Standard,
    /// Judge builds `verify` from the candidate's Lean model.
    NativeLean(NativeLeanRoute),
    /// A candidate-built native verifier with no judge build: never admitted.
    CandidateNative,
}

/// Output of the judge's native build.
#[derive(Clone, Debug, Serialize)]
pub struct NativeVerifierBuild {
    /// Host path of the judge-built executable (inside the check's work dir).
    pub path: std::path::PathBuf,
    pub digest: Digest,
    pub toolchain_id: String,
    pub lean_toolchain: String,
    pub model_decl: String,
}

pub fn render_main(template: &str, model_module: &str, model_decl: &str) -> String {
    template.replace("{{model_module}}", model_module).replace("{{model_decl}}", model_decl)
}

pub fn render_inst(route: &NativeLeanRoute, expected_module: &str, expected_decl: &str) -> String {
    format!(
        "import {expected_module}\nimport {}\n\n/-! GENERATED by the arena judge: expected statement instantiated at the candidate model. -/\n\ndef {} : Prop := {expected_decl} {}\n",
        route.model_module, route.inst_decl, route.model_decl
    )
}
