#!/usr/bin/env python3
"""Compute spec/challenge-inputs/near-transfer-receipt-v1.json (the spec-lane
fields of challenges/templates/near-transfer-receipt-v1.template.json).

Run from anywhere inside the repo AFTER committing spec/ and oracle/ (tree
digests hash git-tracked files). Requires the oracle binary
(oracle/target/debug/near-arena-oracle) for the runtime-config description.
"""
import hashlib, json, os, subprocess, sys

REPO = subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True,
                      check=True).stdout.strip()
J = lambda *p: os.path.join(REPO, *p)

def sha_file(p): return "sha256:" + hashlib.sha256(open(J(p), "rb").read()).hexdigest()
def jcs(v): return json.dumps(v, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
def tree(*paths, rel=None):
    cmd = [sys.executable, J("spec/tools/tree_digest.py")] + (["--relative-to", J(rel)] if rel else []) + [J(p) for p in paths]
    return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout.strip()

def main():
    rc_path = "spec/challenge-inputs/runtime-config-pv86.json"
    oracle = J("oracle/target/debug/near-arena-oracle")
    if os.path.exists(oracle):
        subprocess.run([oracle, "params", "--out", J(rc_path)], check=True, capture_output=True)
    rc = json.load(open(J(rc_path)))
    rc_digest = "sha256:" + hashlib.sha256(jcs(rc).encode()).hexdigest()
    formal_roots = ["spec/lean"] + (["formal-core"] if os.path.isdir(J("formal-core")) else [])
    restrictions = [
        ("pv86", "protocol_version = 86 (nearcore 2.13.4 STABLE_PROTOCOL_VERSION)"),
        ("mainnet_params", "chain_id = mainnet: mainnet RuntimeConfig for PV 86 (RuntimeConfigStore::new(None))"),
        ("claim_wf", "all claim fields within their encoded widths (u32/u64/u128, 32-byte hashes, chain id 1..64 printable ASCII)"),
        ("batch_size", "the batch has 1..=256 receipts"),
        ("compute_limit", "(n-1)*223182562500 < gas_limit: no receipt is pushed to the delayed queue"),
        ("receipt_shape", "every receipt is Receipt::V0 / ReceiptEnum::Action with exactly one Transfer action and no input/output data dependencies"),
        ("valid_account_ids", "predecessor, receiver and signer are valid NEAR AccountIds"),
        ("signer_key_type", "signer public key is ED25519 or SECP256K1"),
        ("not_system_predecessor", "predecessor is not 'system' (refund receipts are not inputs)"),
        ("named_receiver", "receiver is a NamedAccount (not NEAR-implicit, ETH-implicit or deterministic)"),
        ("distinct_receipt_ids", "receipt ids are pairwise distinct"),
        ("witness_size", "the revealed partial-trie bytes are <= 3,000,000 (storage-proof soft limit never reached)"),
        ("receiver_exists_v1", "each receiver Account exists when its receipt is applied and is a 72-byte AccountV1"),
        ("no_balance_overflow", "amount+deposit <= 2^128-2 and amount'+locked < 2^128"),
        ("storage_stake", "after the credit, amount'+locked >= 10^19*storage_usage or storage_usage <= 770"),
        ("burn_fits_u128", "G*min(gas_price, block_gas_price), G*(gas_price-min) and the total tokens burnt fit in u128"),
        ("apply_context", "the chunk applies only these incoming receipts: no transactions, no local/delayed/yield receipts, no validator-account update, new chunk"),
    ]
    excludes = ["block_finality", "data_availability", "receipt_inclusion", "pre_state_root_on_chain",
                "epoch_and_protocol_version_selection", "onchain_post_state_root",
                "transactions", "signature_verification", "function_calls_and_wasm", "non_transfer_actions",
                "implicit_account_creation", "failure_paths_and_rollback", "refund_receipt_inputs",
                "data_postponed_yield_receipts", "delayed_receipt_queue", "congestion_control_and_buffering",
                "bandwidth_scheduler", "outgoing_receipts_root_and_routing", "validator_updates_and_rewards",
                "account_v2_global_contracts", "receipt_enum_action_v2", "other_protocol_versions",
                "testnet_parameters"]
    out = {
        "_note": "Spec-lane inputs for challenges/templates/near-transfer-receipt-v1.template.json. GENERATED by spec/tools/challenge_inputs.py; do not edit by hand.",
        "chain_id": "mainnet",
        "protocol_version": 86,
        "nearcore": {"repo": "https://github.com/near/nearcore", "tag": "2.13.4",
                     "commit": "44f7ae6cd7ef08bab604e20a473bf77e35d4c993"},
        "runtime_config_digest": rc_digest,
        "runtime_config_digest_definition": "sha256(JCS(spec/challenge-inputs/runtime-config-pv86.json)); see spec/near-transfer-receipt-v1.md §8",
        "semantic_scope": {
            "name": "near-transfer-receipt-v1",
            "statement_id": "near/pv86/receipt-transfer-batch/v0",
            "kind": "subset",
            "granularity": "receipt_batch_transition",
            "restrictions": [{"id": i, "text": t} for i, t in restrictions],
            "excludes": excludes,
            "formal_spec": {
                "relation_module": "NearSpec.TransferV1",
                "relation_decl": "NearSpec.TransferV1.NearRelation",
                "tree_digest": tree(*formal_roots),
                "lean_toolchain": open(J("spec/lean/lean-toolchain")).read().strip(),
            },
            "formal_spec_tree_scope": formal_roots,
            "formal_spec_tree_note": ("TreeDigest over git-tracked files, paths relative to the repo root "
                                      "(spec/tools/tree_digest.py). formal-core is not merged in this tree yet: "
                                      "recompute with both roots at freeze." if "formal-core" not in formal_roots else
                                      "TreeDigest over git-tracked files of spec/lean and formal-core, paths relative to the repo root."),
            "challenge_spec_instance": {
                "Claim": "NearSpec.TransferV1.WfClaim", "Rel": "NearSpec.TransferV1.WfClaim.Rel",
                "Domain": "NearSpec.TransferV1.WfClaim.ClaimDomain",
                "encodeClaim": "NearSpec.TransferV1.WfClaim.encode",
                "decodeClaim": "NearSpec.TransferV1.WfClaim.decode",
                "decode_encode": "NearSpec.TransferV1.WfClaim.decode_encode",
                "Witness": "NearSpec.TransferV1.Witness",
                "full_domain": "NearSpec.TransferV1.Domain",
            },
            "spec_doc": "spec/near-transfer-receipt-v1.md",
            "spec_doc_digest": sha_file("spec/near-transfer-receipt-v1.md"),
        },
        "claim_encoding": {
            "format": "near-arena-claim-v1",
            "spec": "spec/claim-v1.md",
            "spec_digest": sha_file("spec/claim-v1.md"),
            "max_request_bytes": 131072,
            "max_witness_bytes": 4194304,
            "max_claim_bytes": 366,
        },
        "toolchain_policy": {"lean_toolchain": open(J("spec/lean/lean-toolchain")).read().strip()},
        "workload_suite": {
            "generator": "near-arena-oracle gen (oracle/src/casegen.rs)",
            "generator_digest": tree("oracle/src", "oracle/Cargo.toml", "oracle/Cargo.lock", "oracle/NEARCORE_PIN"),
            "generator_digest_scope": ["oracle/src", "oracle/Cargo.toml", "oracle/Cargo.lock", "oracle/NEARCORE_PIN"],
            "public_fixtures": tree("oracle/fixtures/public", rel="oracle/fixtures/public"),
            "public_fixtures_path": "oracle/fixtures/public",
            "rejection_fixtures": tree("oracle/fixtures/rejection", rel="oracle/fixtures/rejection"),
            "suggested_classes": [
                {"id": "transfer-batch-small", "description": "1..16 receipts (profiles basic/prefix/prices/boundary)", "generator_profiles": ["basic", "prefix", "prices", "boundary"]},
                {"id": "transfer-batch-repeat", "description": "4..40 receipts, hot receivers", "generator_profiles": ["repeat"]},
                {"id": "transfer-batch-large", "description": "64..256 receipts over 20..200 accounts", "generator_profiles": ["large"]},
            ],
        },
    }
    p = J("spec/challenge-inputs/near-transfer-receipt-v1.json")
    open(p, "w").write(json.dumps(out, indent=1) + "\n")
    print(p)
    print("runtime_config_digest", rc_digest)

if __name__ == "__main__":
    main()
