#!/usr/bin/env python3
"""Compute spec/challenge-inputs/near-transfer-receipt-v2.json: the spec-lane
fields of challenge near-transfer-receipt-v2 (statement
near/pv86/receipt-transfer-batch/v1). v1's inputs file is not touched.

Run from inside the repo AFTER committing spec/ and oracle/ (tree digests hash
git-tracked files). Requires oracle/target/debug/near-arena-oracle (for the v2
runtime-config description).
"""
import hashlib, json, os, subprocess, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from challenge_inputs import J, jcs, sha_file, tree

RESTRICTIONS = [
    ("pv86", "protocol_version = 86 (nearcore 2.13.4 STABLE_PROTOCOL_VERSION)"),
    ("mainnet_params", "chain_id = mainnet: mainnet RuntimeConfig for PV 86 (RuntimeConfigStore::new(None))"),
    ("claim_wf", "all claim fields within their encoded widths (u16/u32/u64/u128, 32-byte hashes, chain id 1..64 printable ASCII)"),
    ("batch_size", "the batch has 1..=256 receipts"),
    ("compute_limit", "(n-1)*223182562500 < gas_limit: no receipt is pushed to the delayed queue"),
    ("receipt_shape", "every receipt is Receipt::V0 / ReceiptEnum::Action with exactly one Transfer action and no input/output data dependencies"),
    ("valid_account_ids", "predecessor, receiver and signer are valid NEAR AccountIds"),
    ("signer_key_type", "signer public key is ED25519 or SECP256K1"),
    ("not_system_predecessor", "predecessor is not 'system' (refund receipts are not inputs)"),
    ("named_receiver", "receiver is a NamedAccount (not NEAR-implicit, ETH-implicit or deterministic)"),
    ("distinct_receipt_ids", "receipt ids are pairwise distinct"),
    ("witness_size", "the revealed partial-trie bytes (receivers' Account paths and the path to key 0x0f) are <= 3,000,000"),
    ("receiver_exists_v1", "each receiver Account exists when its receipt is applied and is a 72-byte AccountV1"),
    ("no_balance_overflow", "amount+deposit <= 2^128-2 and amount'+locked < 2^128"),
    ("storage_stake", "after the credit, amount'+locked >= 10^19*storage_usage or storage_usage <= 770"),
    ("burn_fits_u128", "G*min(gas_price, block_gas_price), G*(gas_price-min) and the total tokens burnt fit in u128"),
    ("single_shard_layout", "the epoch's shard layout has exactly one shard, shard_id, and shard_id < 2^32 (NOT the case on multi-shard mainnet)"),
    ("zero_congestion", "the shard's CongestionInfoV1 in the block has delayed_receipts_gas = buffered_receipts_gas = receipt_bytes = 0"),
    ("no_bandwidth_requests", "the block carries no bandwidth requests"),
    ("scheduler_state_decodes", "an existing TrieKey::BandwidthSchedulerState (0x0f) value is a valid borsh BandwidthSchedulerState"),
    ("refund_needs_grant", "if missed_chunks_count > 0 (link (S,S) not allowed, no bandwidth granted) no receipt generates a gas refund"),
    ("apply_context", "the chunk applies only these incoming receipts: no transactions, no local/delayed/yield/buffered receipts, no validator-account update, new chunk"),
]
EXCLUDES = [
    "block_finality", "data_availability", "receipt_inclusion", "pre_state_root_on_chain",
    "epoch_and_protocol_version_selection", "multi_shard_layouts", "bandwidth_requests", "nonzero_congestion",
    "transactions", "signature_verification", "function_calls_and_wasm", "non_transfer_actions",
    "implicit_account_creation", "failure_paths_and_rollback", "refund_receipt_inputs",
    "data_postponed_yield_receipts", "delayed_receipt_queue", "buffered_receipts_and_forwarding_limits",
    "outgoing_receipts_root_and_routing", "validator_updates_and_rewards", "account_v2_global_contracts",
    "receipt_enum_action_v2", "other_protocol_versions", "testnet_parameters",
]
ORACLE_SCOPE = ["oracle/src", "oracle/Cargo.toml", "oracle/Cargo.lock", "oracle/NEARCORE_PIN"]

def main():
    rc_path = "spec/challenge-inputs/runtime-config-pv86-v2.json"
    oracle = J("oracle/target/debug/near-arena-oracle")
    if os.path.exists(oracle):
        subprocess.run([oracle, "params", "--scope", "v2", "--out", J(rc_path)], check=True, capture_output=True)
    rc = json.load(open(J(rc_path)))
    rc_digest = "sha256:" + hashlib.sha256(jcs(rc).encode()).hexdigest()
    formal_roots = ["spec/lean", "formal-core"]
    out = {
        "_note": "Spec-lane inputs for challenge near-transfer-receipt-v2. GENERATED by spec/tools/challenge_inputs_v2.py; do not edit by hand.",
        "chain_id": "mainnet",
        "protocol_version": 86,
        "nearcore": {"repo": "https://github.com/near/nearcore", "tag": "2.13.4",
                     "commit": "44f7ae6cd7ef08bab604e20a473bf77e35d4c993"},
        "runtime_config_digest": rc_digest,
        "runtime_config_digest_definition": "sha256(JCS(spec/challenge-inputs/runtime-config-pv86-v2.json)); see spec/near-transfer-receipt-v2.md §8",
        "semantic_scope": {
            "name": "near-transfer-receipt-v2",
            "statement_id": "near/pv86/receipt-transfer-batch/v1",
            "kind": "subset",
            "granularity": "receipt_batch_transition",
            "restrictions": [{"id": i, "text": t} for i, t in RESTRICTIONS],
            "excludes": EXCLUDES,
            "formal_spec": {
                "relation_module": "NearSpec.TransferV2",
                "relation_decl": "NearSpec.TransferV2.NearRelation",
                "tree_digest": tree(*formal_roots),
                "lean_toolchain": open(J("spec/lean/lean-toolchain")).read().strip(),
            },
            "formal_spec_tree_scope": formal_roots,
            "formal_spec_tree_note": "TreeDigest over git-tracked files of spec/lean and formal-core, paths relative to the repo root.",
            "challenge_spec_instance": {
                "Claim": "NearSpec.TransferV2.WfClaim", "Rel": "NearSpec.TransferV2.WfClaim.Rel",
                "Domain": "NearSpec.TransferV2.WfClaim.ClaimDomain",
                "encodeClaim": "NearSpec.TransferV2.WfClaim.encode",
                "decodeClaim": "NearSpec.TransferV2.WfClaim.decode",
                "decode_encode": "NearSpec.TransferV2.WfClaim.decode_encode",
                "Witness": "NearSpec.TransferV2.Witness",
                "full_domain": "NearSpec.TransferV2.Domain",
                "params": "NearSpec.TransferV2.challengeParams",
                "formal_checker_config": "runners/formal-checker/challenges/near-transfer-receipt-v2.json",
            },
            "spec_doc": "spec/near-transfer-receipt-v2.md",
            "spec_doc_digest": sha_file("spec/near-transfer-receipt-v2.md"),
            "supersedes_semantics_of": None,
            "relation_to_v1": "separate statement; v1 (near/pv86/receipt-transfer-batch/v0) unchanged",
        },
        "claim_encoding": {
            "format": "near-arena-claim-v2",
            "spec": "spec/claim-v2.md",
            "spec_digest": sha_file("spec/claim-v2.md"),
            "max_request_bytes": 131072,
            "max_witness_bytes": 4194304,
            "max_claim_bytes": 416,
        },
        "toolchain_policy": {"lean_toolchain": open(J("spec/lean/lean-toolchain")).read().strip()},
        "workload_suite": {
            "generator": "near-arena-oracle gen --scope v2 (oracle/src/v2.rs over oracle/src/casegen.rs)",
            "generator_digest": tree(*ORACLE_SCOPE),
            "generator_digest_scope": ORACLE_SCOPE,
            "public_fixtures": tree("oracle/fixtures/v2/public", rel="oracle/fixtures/v2/public"),
            "public_fixtures_path": "oracle/fixtures/v2/public",
            "rejection_fixtures": tree("oracle/fixtures/v2/rejection", rel="oracle/fixtures/v2/rejection"),
            "rejection_fixtures_path": "oracle/fixtures/v2/rejection",
            "differential_test_report": "spec/difftest-report-v2.json",
        },
    }
    p = J("spec/challenge-inputs/near-transfer-receipt-v2.json")
    open(p, "w").write(json.dumps(out, indent=1) + "\n")
    print(p)
    print("runtime_config_digest", rc_digest)

if __name__ == "__main__":
    main()
