//! Least-privilege Postgres roles.
//!
//! Three roles, each used by one connection pool of the control plane:
//!
//! * **api** — public/agent API: reads, uploads, submissions, cancellation.
//! * **worker** — the *worker gateway* inside the control plane that serves
//!   `/internal/v1/*`. Worker processes themselves never receive database
//!   credentials; they only speak HTTP to the gateway.
//! * **admin** — challenge registration, revocations, reruns, cache
//!   invalidation, principal management.
//!
//! No role is granted `DELETE` or `TRUNCATE` on any table; immutability of
//! audit events, submissions, gate results, revocations and reports is
//! additionally enforced by triggers that apply even to the table owner.
//! The migration owner (the role that runs `arena-server migrate`) owns the
//! schema and should not be used by the serving process in production.

/// Default role names (used by `server/arena-db/sql/roles.sql`).
pub const DEFAULT_ROLES: RoleNames<'static> =
    RoleNames { api: "arena_api", worker: "arena_worker", admin: "arena_admin" };

#[derive(Clone, Copy, Debug)]
pub struct RoleNames<'a> {
    pub api: &'a str,
    pub worker: &'a str,
    pub admin: &'a str,
}

fn ident_ok(s: &str) -> bool {
    !s.is_empty()
        && s.len() <= 63
        && s.bytes().all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        && !s.as_bytes()[0].is_ascii_digit()
}

const ALL_TABLES: &[&str] = &[
    "agents", "admins", "workers", "challenges", "uploads", "artifacts", "submissions", "runs",
    "gate_results", "jobs", "audit_events", "revocations", "formal_cache", "quotas", "reports",
];

/// `GRANT` statements for the three roles (roles must already exist).
pub fn grants_sql(r: RoleNames<'_>) -> String {
    for n in [r.api, r.worker, r.admin] {
        assert!(ident_ok(n), "invalid role name {n:?}");
    }
    let mut s = String::new();
    let mut add = |line: String| {
        s.push_str(&line);
        s.push('\n');
    };
    let all = ALL_TABLES.join(", ");
    add(format!("REVOKE ALL ON {all} FROM PUBLIC;"));
    for role in [r.api, r.worker, r.admin] {
        add(format!("REVOKE ALL ON {all} FROM {role};"));
        add(format!("GRANT USAGE ON SCHEMA public TO {role};"));
        add(format!("GRANT USAGE ON SEQUENCE audit_events_id_seq TO {role};"));
    }
    // ---- api
    let api = r.api;
    add(format!(
        "GRANT SELECT ON agents, challenges, uploads, submissions, runs, gate_results, jobs, \
         audit_events, revocations, quotas, reports TO {api};"
    ));
    add(format!("GRANT INSERT ON uploads, submissions, runs, jobs, audit_events, reports TO {api};"));
    // cancellation updates pending runs / jobs; the agent row is locked (FOR UPDATE) for quota checks
    add(format!("GRANT UPDATE ON runs, jobs, agents TO {api};"));
    // ---- worker gateway
    let w = r.worker;
    add(format!(
        "GRANT SELECT ON workers, agents, challenges, uploads, artifacts, submissions, runs, gate_results, \
         jobs, formal_cache, reports, revocations TO {w};"
    ));
    add(format!("GRANT USAGE ON SEQUENCE gate_results_id_seq TO {w};"));
    add(format!(
        "GRANT INSERT ON artifacts, gate_results, jobs, audit_events, formal_cache, reports TO {w};"
    ));
    add(format!("GRANT UPDATE ON runs, jobs TO {w};"));
    // ---- admin
    let a = r.admin;
    add(format!("GRANT SELECT ON {all} TO {a};"));
    add(format!("GRANT USAGE ON SEQUENCE gate_results_id_seq, revocations_id_seq TO {a};"));
    add(format!(
        "GRANT INSERT ON agents, admins, workers, challenges, revocations, quotas, runs, jobs, \
         gate_results, audit_events, reports, formal_cache TO {a};"
    ));
    add(format!(
        "GRANT UPDATE ON agents, admins, workers, challenges, quotas, runs, jobs, formal_cache TO {a};"
    ));
    s
}

/// Full script: create NOLOGIN roles if missing, then grants. Operators attach
/// LOGIN + password (or certificate auth) to these roles, or grant them to
/// login roles.
pub fn roles_script(r: RoleNames<'_>) -> String {
    let mut s = String::from(
        "-- Generated by `arena-server roles-sql` (server/arena-db/src/roles.rs). Do not edit.\n\
         -- Run as the schema owner after `arena-server migrate`.\n",
    );
    for role in [r.api, r.worker, r.admin] {
        assert!(ident_ok(role));
        s.push_str(&format!(
            "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN \
             CREATE ROLE {role} NOLOGIN; END IF; END $$;\n"
        ));
    }
    s.push_str(&grants_sql(r));
    s
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn checked_in_roles_sql_is_current() {
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/sql/roles.sql");
        let want = roles_script(DEFAULT_ROLES);
        if std::env::var_os("UPDATE_ROLES_SQL").is_some() {
            std::fs::write(path, &want).unwrap();
        }
        let have = std::fs::read_to_string(path).unwrap_or_default();
        assert_eq!(have, want, "run with UPDATE_ROLES_SQL=1 to regenerate {path}");
    }
    #[test]
    fn no_delete_grants() {
        let s = grants_sql(DEFAULT_ROLES);
        assert!(!s.contains("DELETE") && !s.contains("TRUNCATE"));
    }
    #[test]
    #[should_panic]
    fn rejects_bad_names() {
        grants_sql(RoleNames { api: "x; drop", worker: "w", admin: "a" });
    }
}
