import ZkFormal.NearV3.Assembly.QueueCapacity
import ZkFormal.NearV3.Assembly.QueuePayload
import ZkFormal.NearV3.Assembly.ReadUnfoldBound
import ZkFormal.NearV3.Assembly.ValueIndex
import ZkFormal.NearV3.Qv.Candidates.CombinedImplicitSteps
import ZkFormal.NearV3.Qv.Candidates.CombinedMainOrder
import ZkFormal.NearV3.Qv.Candidates.CombinedMainSteps
import ZkFormal.NearV3.Qv.Candidates.CombinedNeighborEquations
import ZkFormal.NearV3.Qv.Candidates.CombinedPlanOrder
import ZkFormal.NearV3.Qv.Candidates.CombinedRowLayout
import ZkFormal.NearV3.Qv.Candidates.CombinedStepCases
import ZkFormal.NearV3.Qv.Candidates.CombinedTraceNeighbors
import ZkFormal.NearV3.Rcpt.Candidates.DedupReceiptLengths
import ZkFormal.NearV3.Rcpt.Extract.V.BytesViewProof
import ZkFormal.NearV3.Rcpt.Extract.V.ChainBytes
import ZkFormal.NearV3.Rcpt.Extract.V.GlobalListCounters
import ZkFormal.NearV3.Rcpt.Extract.V.HeaderTraffic
import ZkFormal.NearV3.Rcpt.Extract.V.ListView
import ZkFormal.NearV3.Rcpt.Extract.V.PrefixOffsets
import ZkFormal.NearV3.Render.Ups.BranchSideAllocation
import ZkFormal.NearV3.Render.Ups.NativeByteFamily
import ZkFormal.NearV3.Render.Ups.NativeChildId
import ZkFormal.NearV3.Render.Ups.NativeInstanceOk
import ZkFormal.NearV3.Render.Ups.NativeWindowCount
import ZkFormal.NearV3.Render.Ups.SignedInstance
import ZkFormal.NearV3.Render.Ups.TreeChildLookup
import ZkFormal.NearV3.Render.Ups.TreeSourceChain
import ZkFormal.NearV3.Render.Ups.TreeTerminalEnd
import ZkFormal.NearV3.Assembly.QueryAccepted
import ZkFormal.NearV3.Assembly.PostShadows
import ZkFormal.NearV3.Assembly.TransitionQueries
import ZkFormal.NearV3.Assembly.UnfoldStoreEq
import ZkFormal.NearV3.Qv.Candidates.CombinedBoolean
import ZkFormal.NearV3.Qv.Candidates.CombinedKeyEndpoints
import ZkFormal.NearV3.Qv.Candidates.CombinedMetadataEquations
import ZkFormal.NearV3.Qv.Candidates.CombinedPhysical
import ZkFormal.NearV3.Qv.Candidates.CombinedReadAlgebra
import ZkFormal.NearV3.Qv.Candidates.CombinedTermination
import ZkFormal.NearV3.Qv.Candidates.CombinedWalkBase
import ZkFormal.NearV3.Rcpt.Candidates.DedupPhysicalExtract
import ZkFormal.NearV3.Rcpt.Extract.V.EncodedOffsets
import ZkFormal.NearV3.Rcpt.Extract.V.ListIndices
import ZkFormal.NearV3.Rcpt.Extract.V.ListLengths
import ZkFormal.NearV3.Rcpt.Extract.V.ListTerminal
import ZkFormal.NearV3.Rcpt.Extract.V.RclProof
import ZkFormal.NearV3.Render.Ups.EncodedKindTypes
import ZkFormal.NearV3.Render.Ups.EncodedSourceBytes
import ZkFormal.NearV3.Render.Ups.FieldEnd
import ZkFormal.NearV3.Render.Ups.NativePartEncoding
import ZkFormal.NearV3.Render.Ups.NativePartPlan
import ZkFormal.NearV3.Render.Ups.PositionedPart
import ZkFormal.NearV3.Render.Ups.SourceDepthAllocation
import ZkFormal.NearV3.Render.Ups.SourceLevelLookup
import ZkFormal.NearV3.Render.Ups.TreeRootSource
import ZkFormal.NearV3.Assembly.CanonicalReplay
import ZkFormal.NearV3.Assembly.DecodedWitnessShape
import ZkFormal.NearV3.Assembly.NativeGoodGap
import ZkFormal.NearV3.Assembly.NativeShape
import ZkFormal.NearV3.Qv.Candidates.CombinedCapacity
import ZkFormal.NearV3.Qv.Candidates.CombinedShardTraffic
import ZkFormal.NearV3.Qv.Candidates.CombinedWalkBits
import ZkFormal.NearV3.Qv.Candidates.CombinedWalkTraffic
import ZkFormal.NearV3.Qv.Candidates.CombinedWordTraffic
import ZkFormal.NearV3.Qv.Candidates.ValueGen
import ZkFormal.NearV3.Rcpt.Candidates.DedupExtractProof
import ZkFormal.NearV3.Rcpt.Candidates.DedupSourceReuse
import ZkFormal.NearV3.Rcpt.Candidates.DedupSourceVerify
import ZkFormal.NearV3.Render.Ups.DescentAllocation
import ZkFormal.NearV3.Render.Ups.PlanAllocation
import ZkFormal.NearV3.Render.Ups.TerminalDescent
import ZkFormal.NearV3.Render.Ups.TreeEncodedBounds
import ZkFormal.NearV3.Render.Ups.TreePlanDepth
import ZkFormal.V2.Log23.QueryBound
import ZkFormal.NearV3.Render.Ups.TreeExtMemoryInput
import ZkFormal.NearV3.Render.Ups.TreeInsertMemoryDispatch
import ZkFormal.NearV3.Render.Ups.TreeValueMemoryDispatch
import ZkFormal.NearV3.Rcpt.Candidates.DedupUnitDecomposition
import ZkFormal.NearV3.Rcpt.Candidates.DedupJoinedTraffic
import ZkFormal.NearV3.Rcpt.Candidates.SourceCurrentSize
import ZkFormal.NearV3.Qv.Candidates.CombinedPublic
import ZkFormal.NearV3.Qv.Candidates.CombinedParser
import ZkFormal.NearV3.Assembly.DecodedShapes
import ZkFormal.NearV3.Assembly.RetainedStore
import ZkFormal.NearV3.Assembly.NativePrepared
import ZkFormal.NearV3.Rcpt.Candidates.DedupPartitionEndpoint
import ZkFormal.NearV3.Rcpt.Candidates.DedupPartitionCompile
import ZkFormal.NearV3.Qv.Candidates.RecordTrafficContract
import ZkFormal.NearV3.Render.Ups.TreeMemoryUp
import ZkFormal.NearV3.Render.Ups.TreeMemoryInput
import ZkFormal.NearV3.Render.Ups.MemTotalBounds
import ZkFormal.NearV3.Render.Ups.MemGrowthParts
import ZkFormal.NearV3.Assembly.PrepBodyComplete
import ZkFormal.NearV3.Assembly.NativePayload
import ZkFormal.NearV3.Assembly.NativeWitnessSize
import ZkFormal.V2.Log23.TransportBudget
import ZkFormal.V2.Log23.Budget
import ZkFormal.NearV3.Assembly.ForestStore
import ZkFormal.NearV3.Assembly.NativeCapacity
import ZkFormal.NearV3.Assembly.WitnessSize
import ZkFormal.NearV3.Qv.Candidates.RecordConcat
import ZkFormal.NearV3.Qv.Candidates.ValueBudget
import ZkFormal.NearV3.Rcpt.Candidates.DedupCrossLocal
import ZkFormal.NearV3.Rcpt.Candidates.DedupTerminalPadding
import ZkFormal.NearV3.Assembly.TreeStore
import ZkFormal.NearV3.Assembly.FactorSound
import ZkFormal.NearV3.Qv.ReadPlan
import ZkFormal.NearV3.Assembly.Good
import ZkFormal.NearV3.Assembly.Compute
import ZkFormal.NearV3.Assembly.Forward
import ZkFormal.NearV3.Qv.ByteBuffers
import ZkFormal.NearV3.Qv.ReceiptPreserve
import ZkFormal.NearV3.Render.Ups.ByteConstructors
import ZkFormal.NearV3.Public.Bindings
import ZkFormal.NearV3.Assembly.Scheduler
import ZkFormal.NearV3.Rcpt.Link.SourceHashes
import ZkFormal.NearV3.Render.Ups.GBytes
import ZkFormal.NearV3.Rcpt.Render.Srcp.LocalProof
import ZkFormal.NearV3.Rcpt.Render.Srcp.TrafficProof
import ZkFormal.V2.IndexedPublic
import ZkFormal.NearV3.Rcpt.Render.Srcp.Boolean
import ZkFormal.NearV3.Rcpt.Render.Srcp.Accumulator
import ZkFormal.NearV3.Rcpt.Render.Srcp.Adjacency
import ZkFormal.NearV3.Rcpt.Extract.Srcp.Proof
import ZkFormal.NearV3.Rcpt.Link.SourceHash
import ZkFormal.NearV3.Rcpt.Link.SourceNonempty
import ZkFormal
import ZkFormal.NearV3.BudgetCheck
import ZkFormal.NearV3.Extract.Node.Proof
import ZkFormal.NearV3.Extract.Ups.UpsLink
import ZkFormal.NearV3.Link.Post3OccSets
import ZkFormal.NearV3.Rcpt.BudgetCheck
import ZkFormal.NearV3.Rcpt.Extract.V.Key
import ZkFormal.NearV3.Rcpt.Link.Body
import ZkFormal.NearV3.Rcpt.Link.Keynib
import ZkFormal.NearV3.Rcpt.Link.Lex
import ZkFormal.NearV3.Rcpt.Link.Srec
import ZkFormal.NearV3.Rcpt.Render.AcctRender
import ZkFormal.NearV3.Rcpt.Render.AkeyRender
import ZkFormal.NearV3.Rcpt.Render.BndRender
import ZkFormal.NearV3.Rcpt.Render.SizeRender
import ZkFormal.NearV3.Rcpt.ShaRows
import ZkFormal.NearV3.Render.HeadRender
import ZkFormal.NearV3.Render.Padded
import ZkFormal.NearV3.Render.PaddedTrie
import ZkFormal.NearV3.Render.NodeRender
import ZkFormal.NearV3.Render.UniqRender
import ZkFormal.NearV3.Render.UpsRender
import ZkFormal.NearV3.Render.ValRender
import ZkFormal.NearV3.Render.WalkRender
import ZkFormal.NearV3.Sched.BudgetCheck
import ZkFormal.NearV3.Sched.Complete.All
import ZkFormal.NearV3.Sched.Gen.Codec
import ZkFormal.NearV3.Sched.Gen.Lane
import ZkFormal.NearV3.Sched.Link.FwdPrep
import ZkFormal.NearV3.Sched.Link.KindSched
import ZkFormal.NearV3.Spec.TreeRecs
import ZkFormal.Size.V3Eval
import ZkFormal.Size.AlignedModel
import ZkFormal.Size.HonestAdmission
import ZkFormal.V3.RefundCodec

/-!
# Build gate for the integrated v3 proof work

Run `lake build ZkFormal.V3.Integration` under the host's heavy/taskset wrapper.
The historical `ZkFormal` root does not import the merged v3 trie, scheduler,
receipt, or deduplicated-size proof modules. This separate target checks their
interfaces together without changing the v1 build root or deployed packages.

Executable drivers (`V3.Tools`) and their compiler fast paths (`V3.Fast`) remain
separate targets. Unmerged WIP helpers are not imported. A successful build
checks the existing partial results, not the still-missing FactorComplete, AIR-to-Good, honestTrace_fits,
or final admission certificate. Candidate imports do not admit their protocol parameters.
-/
