#!/usr/bin/env python3
"""Generate formal/ReexecNpai/CodeDigest.lean from out/verifier.npai.

The certificate needs `ArenaCore.sha256 code = <digest of the image>`. One
`decide +kernel` over the whole 30 KB image peaks at ~13 GB in the kernel,
above the judge's 8 GiB per-module sandbox, and any kernel computation that
is not tail-recursive over all 30 K bytes (`List.length`, comparing with a
30 K literal) overflows the 8 MiB stack of the independent checker nanoda.
So the proof never computes over the whole image at once:

* `code.length` comes from `(code.drop D).length` (drop is iterative) and
  `List.length_drop`;
* `pad (code.map _)` is rewritten to `P := code.map _ ++ [0x80] ++ zeros ++
  lengthBytes` with literal padding (`pad_eq`), so the kernel never needs the
  message length while hashing;
* `P` is hashed in chunks of CHUNK blocks, each a separate `decide +kernel`
  theorem from one intermediate hash state (a literal computed here) to the
  next; `blocks_add` (proved once, by induction) glues the chunks together.

Nothing here is trusted: every literal is checked by the kernel. Re-run after
any change to the program (the build checks the digest matches):

  python3 source/export/gen_code_digest.py out/verifier.npai formal/ReexecNpai/CodeDigest.lean
"""
import hashlib, struct, sys

CHUNK = 32  # blocks per kernel theorem

K = [0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
     0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
     0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
     0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
     0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
     0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
     0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
     0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2]
H0 = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19]
M = 0xFFFFFFFF


def rotr(x, n):
    return ((x >> n) | (x << (32 - n))) & M


def compress(h, block):
    w = list(struct.unpack(">16I", block))
    for t in range(16, 64):
        s0 = rotr(w[t - 15], 7) ^ rotr(w[t - 15], 18) ^ (w[t - 15] >> 3)
        s1 = rotr(w[t - 2], 17) ^ rotr(w[t - 2], 19) ^ (w[t - 2] >> 10)
        w.append((w[t - 16] + s0 + w[t - 7] + s1) & M)
    a, b, c, d, e, f, g, hh = h
    for t in range(64):
        t1 = (hh + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ ((e ^ M) & g)) + K[t] + w[t]) & M
        t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) & M
        a, b, c, d, e, f, g, hh = (t1 + t2) & M, a, b, c, (d + t1) & M, e, f, g
    return [(x + y) & M for x, y in zip(h, [a, b, c, d, e, f, g, hh])]


def pad(m):
    k = (119 - len(m) % 64) % 64
    return m + b"\x80" + bytes(k) + struct.pack(">Q", 8 * len(m))


img = open(sys.argv[1], "rb").read()
p = pad(img)
nblocks = len(p) // 64
states = [H0]
starts = list(range(0, nblocks, CHUNK))
for s in starts:
    h = states[-1]
    for i in range(s, min(s + CHUNK, nblocks)):
        h = compress(h, p[64 * i:64 * i + 64])
    states.append(h)
digest = b"".join(struct.pack(">I", x) for x in states[-1])
assert digest == hashlib.sha256(img).digest()

lst = lambda h: "[" + ", ".join(str(x) for x in h) + "]"
blit = lambda b: "[" + ", ".join("0x%02x" % x for x in b) + "]"

out = []
L = len(img)
STEP = 64 * CHUNK  # bytes per chunk; also the granularity of every `List.drop`
assert all(s_ % CHUNK == 0 for s_ in starts)


def nest(base, k):
    """`List.drop STEP (... (List.drop STEP base))`, k levels: no single kernel
    whnf walks more than STEP list cells (lean4lean bounds each whnf loop)."""
    e = base
    for _ in range(k):
        e = f"(List.drop {STEP} {e})"
    return e


D_LEVELS = (L - 1) // STEP  # drop D_LEVELS*STEP < L bytes
kpad = (119 - L % 64) % 64
lenb = list(struct.pack(">Q", 8 * L))
out.append(f"""import ReexecNpai.Program

/-!
# `sha256 code` in kernel-sized pieces

GENERATED by `source/export/gen_code_digest.py` from `out/verifier.npai`
(sha256 `{hashlib.sha256(img).hexdigest()}`, {L} bytes, {nblocks} padded
blocks, {len(starts)} chunks of ≤ {CHUNK} blocks). Every literal is checked by the
kernel; see the generator for why the proof is split.
-/

namespace ReexecNpai.CodeDigest

open ArenaCore

theorem code_tail : {nest("code", D_LEVELS)}.length = {L - D_LEVELS * STEP} := by decide +kernel

theorem code_length : code.length = {L} := by
  have h := code_tail
  simp only [List.length_drop] at h
  omega

/-- The padded message, with the padding as literals. -/
def P : List Nat := code.map UInt8.toNat ++ [0x80] ++ List.replicate {kpad} 0 ++ {lst(lenb)}

theorem pad_eq : SHA256.pad (code.map UInt8.toNat) = P := by
  unfold SHA256.pad P
  rw [List.length_map, code_length]
  rfl

theorem P_length : P.length = {len(p)} := by
  rw [P, List.length_append, List.length_append, List.length_append, List.length_map, code_length,
    List.length_replicate]
  rfl

theorem blocks_add : ∀ (n m : Nat) (h msg : List Nat), 64 * n ≤ msg.length →
    SHA256.blocks (n + m) h msg = SHA256.blocks m (SHA256.blocks n h msg) (msg.drop (64 * n))
  | 0, m, h, msg, _ => by simp [SHA256.blocks]
  | n + 1, m, h, msg, hl => by
    match msg, hl with
    | [], hl => simp at hl
    | x :: xs, hl =>
      rw [show n + 1 + m = (n + m) + 1 by omega]
      simp only [SHA256.blocks]
      rw [blocks_add n m _ _ (by simp only [List.length_drop, List.length_cons] at hl ⊢; omega),
        List.drop_drop]
      congr 2
      omega
""")
for j, s in enumerate(starts):
    n = min(CHUNK, nblocks - s)
    out.append(f"theorem chunk{j} : SHA256.blocks {n} {lst(states[j])} {nest('P', j)} = {lst(states[j + 1])} := by\n  decide +kernel\n")
for j, s in enumerate(starts[:-1]):
    rest = nblocks - s
    out.append(f"""theorem step{j} : SHA256.blocks {rest} {lst(states[j])} {nest('P', j)} =
    SHA256.blocks {rest - CHUNK} {lst(states[j + 1])} {nest('P', j + 1)} := by
  rw [show {rest} = {CHUNK} + {rest - CHUNK} from rfl,
    blocks_add {CHUNK} {rest - CHUNK} _ _ (by simp only [List.length_drop, P_length]; decide), chunk{j}]
""")
last = len(starts) - 1
calc = [f"theorem blocks_P : SHA256.blocks {nblocks} SHA256.H0 P = {lst(states[-1])} :=",
        f"  calc SHA256.blocks {nblocks} SHA256.H0 P = SHA256.blocks {nblocks} {lst(states[0])} P := rfl"]
for j in range(last):
    calc.append(f"    _ = _ := step{j}")
calc.append(f"    _ = _ := chunk{last}")
out.append("\n".join(calc) + "\n")
out.append(f"""/-- The digest of the exported image. -/
def digestLit : Digest := {blit(digest)}

theorem sha256_eq (m : Bytes) : sha256 m = SHA256.digestBytes
    (SHA256.blocks ((SHA256.pad (m.map UInt8.toNat)).length / 64) SHA256.H0 (SHA256.pad (m.map UInt8.toNat))) :=
  rfl

theorem sha256_code : sha256 code = digestLit := by
  rw [sha256_eq, pad_eq, P_length, show {len(p)} / 64 = {nblocks} from rfl, blocks_P]
  decide +kernel

end ReexecNpai.CodeDigest
""")
open(sys.argv[2], "w").write("\n".join(out))
print(f"wrote {sys.argv[2]}: {len(starts)} chunks, digest {hashlib.sha256(img).hexdigest()}")
