import ArenaExpected
import ReexecNpai.Obligations
import ReexecNpai.PublicBin
import ReexecNpai.CodeDigest

/-!
# The certificate

Its type, `ArenaExpected.expectedType`, is generated by the judge for the
approved-interpreter route: `AdmissionStatement params { publicDigest,
impl := .interp verifierDigest }` where `verifierDigest` is the SHA-256 of the
judge-built `out/verifier.npai`. The kernel checks `sha256 code = verifierDigest`
for `code = encode program` in pieces (`CodeDigest.sha256_code`: one
`decide +kernel` per 32 SHA-256 blocks, ≈ 3 GB peak instead of ≈ 13 GB for a
single evaluation, which the judge's 8 GiB per-module sandbox kills) and
`sha256 publicBin = publicDigest` (`decide +kernel`); every other literal (profile, fuel,
`maxProofBytes`) only needs `fuel ≥ FUEL + 1` and `maxProofBytes ≥ 5 000 000`.
-/

namespace ReexecNpai

theorem certificate : ArenaExpected.expectedType :=
  admission _ _ _ _ (by decide) (by decide) publicBin (by decide) _ _ (by decide +kernel)
    (CodeDigest.sha256_code.trans (by decide))

end ReexecNpai
