import ArenaExpected
import ReexecNpai.Obligations
import ReexecNpai.PublicBin

/-!
# The certificate

Its type, `ArenaExpected.expectedType`, is generated by the judge for the
approved-interpreter route: `AdmissionStatement params { publicDigest,
impl := .interp verifierDigest }` where `verifierDigest` is the SHA-256 of the
judge-built `out/verifier.npai`. The kernel checks `sha256 code = verifierDigest`
for `code = encode program` (`decide +kernel`, ≈ 75 s for the 30 KB image) and
`sha256 publicBin = publicDigest`; every other literal (profile, fuel,
`maxProofBytes`) only needs `fuel ≥ FUEL + 1` and `maxProofBytes ≥ 5 000 000`.
-/

namespace ReexecNpai

theorem certificate : ArenaExpected.expectedType :=
  admission _ _ _ _ (by decide) (by decide) publicBin (by decide) _ _ (by decide +kernel) (by decide +kernel)

end ReexecNpai
