import ReexecNpai.Program

/-!
# `sha256 code` in kernel-sized pieces

GENERATED by `source/export/gen_code_digest.py` from `out/verifier.npai`
(sha256 `5f4bca8672f92546eec7f3abb9d7b0982130c28e172842030b13d11aec154ec6`, 30769 bytes, 481 padded
blocks, 16 chunks of ≤ 32 blocks). Every literal is checked by the
kernel; see the generator for why the proof is split.
-/

namespace ReexecNpai.CodeDigest

open ArenaCore

theorem code_tail : (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 code))))))))))))))).length = 49 := by decide +kernel

theorem code_length : code.length = 30769 := by
  have h := code_tail
  simp only [List.length_drop] at h
  omega

/-- The padded message, with the padding as literals. -/
def P : List Nat := code.map UInt8.toNat ++ [0x80] ++ List.replicate 6 0 ++ [0, 0, 0, 0, 0, 3, 193, 136]

theorem pad_eq : SHA256.pad (code.map UInt8.toNat) = P := by
  unfold SHA256.pad P
  rw [List.length_map, code_length]
  rfl

theorem P_length : P.length = 30784 := by
  rw [P, List.length_append, List.length_append, List.length_append, List.length_map, code_length,
    List.length_replicate]
  rfl

theorem blocks_add : ∀ (n m : Nat) (h msg : List Nat), 64 * n ≤ msg.length →
    SHA256.blocks (n + m) h msg = SHA256.blocks m (SHA256.blocks n h msg) (msg.drop (64 * n))
  | 0, m, h, msg, _ => by simp [SHA256.blocks]
  | n + 1, m, h, msg, hl => by
    match msg, hl with
    | [], hl => simp at hl
    | x :: xs, hl =>
      rw [show n + 1 + m = (n + m) + 1 by omega]
      simp only [SHA256.blocks]
      rw [blocks_add n m _ _ (by simp only [List.length_drop, List.length_cons] at hl ⊢; omega),
        List.drop_drop]
      congr 2
      omega

theorem chunk0 : SHA256.blocks 32 [1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924, 528734635, 1541459225] P = [3701852952, 3235133154, 548386685, 588677150, 2329423692, 3751203848, 470858033, 284449644] := by
  decide +kernel

theorem chunk1 : SHA256.blocks 32 [3701852952, 3235133154, 548386685, 588677150, 2329423692, 3751203848, 470858033, 284449644] (List.drop 2048 P) = [1070213648, 381245073, 4198158425, 2512301181, 96822014, 1994678375, 501752574, 837775580] := by
  decide +kernel

theorem chunk2 : SHA256.blocks 32 [1070213648, 381245073, 4198158425, 2512301181, 96822014, 1994678375, 501752574, 837775580] (List.drop 2048 (List.drop 2048 P)) = [3052029857, 972671330, 367718156, 2644359889, 1599037751, 2314193254, 3418761980, 149979908] := by
  decide +kernel

theorem chunk3 : SHA256.blocks 32 [3052029857, 972671330, 367718156, 2644359889, 1599037751, 2314193254, 3418761980, 149979908] (List.drop 2048 (List.drop 2048 (List.drop 2048 P))) = [331608545, 769720179, 306282015, 2210403184, 3287305021, 1313795822, 882240847, 172324397] := by
  decide +kernel

theorem chunk4 : SHA256.blocks 32 [331608545, 769720179, 306282015, 2210403184, 3287305021, 1313795822, 882240847, 172324397] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))) = [1041322942, 3032730766, 2930285999, 3767218829, 2618676870, 315918503, 1566190810, 1122706073] := by
  decide +kernel

theorem chunk5 : SHA256.blocks 32 [1041322942, 3032730766, 2930285999, 3767218829, 2618676870, 315918503, 1566190810, 1122706073] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))) = [4024771678, 1705681624, 929701222, 1095438694, 1878532809, 3754568090, 3200043476, 2059284381] := by
  decide +kernel

theorem chunk6 : SHA256.blocks 32 [4024771678, 1705681624, 929701222, 1095438694, 1878532809, 3754568090, 3200043476, 2059284381] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))) = [2780720949, 3961984473, 2134947141, 4257942846, 1945673742, 2469088544, 2663133435, 3606703168] := by
  decide +kernel

theorem chunk7 : SHA256.blocks 32 [2780720949, 3961984473, 2134947141, 4257942846, 1945673742, 2469088544, 2663133435, 3606703168] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))) = [3773650069, 2936497083, 1849155478, 1085302401, 3360913067, 4087155831, 1830208995, 2387312182] := by
  decide +kernel

theorem chunk8 : SHA256.blocks 32 [3773650069, 2936497083, 1849155478, 1085302401, 3360913067, 4087155831, 1830208995, 2387312182] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))) = [1869552117, 3962502480, 3103622650, 1037117405, 600961638, 2386233969, 4066267893, 181535400] := by
  decide +kernel

theorem chunk9 : SHA256.blocks 32 [1869552117, 3962502480, 3103622650, 1037117405, 600961638, 2386233969, 4066267893, 181535400] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))) = [652524593, 1310237923, 3057339629, 486711153, 2913638965, 1964634481, 2836496506, 493173660] := by
  decide +kernel

theorem chunk10 : SHA256.blocks 32 [652524593, 1310237923, 3057339629, 486711153, 2913638965, 1964634481, 2836496506, 493173660] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))) = [1070449270, 4023347495, 4204655608, 3826938210, 1693920144, 3478385786, 1559176617, 3436075215] := by
  decide +kernel

theorem chunk11 : SHA256.blocks 32 [1070449270, 4023347495, 4204655608, 3826938210, 1693920144, 3478385786, 1559176617, 3436075215] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))) = [927743931, 2705208556, 827552466, 1849951364, 2396793266, 281984288, 998706244, 3445715907] := by
  decide +kernel

theorem chunk12 : SHA256.blocks 32 [927743931, 2705208556, 827552466, 1849951364, 2396793266, 281984288, 998706244, 3445715907] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))))) = [860402826, 637593886, 3930648989, 3900112054, 2703336059, 611870260, 3391227695, 729401759] := by
  decide +kernel

theorem chunk13 : SHA256.blocks 32 [860402826, 637593886, 3930648989, 3900112054, 2703336059, 611870260, 3391227695, 729401759] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))))) = [1341701545, 569594415, 2619312586, 1897536134, 1400602478, 1826213693, 3870954665, 1745127529] := by
  decide +kernel

theorem chunk14 : SHA256.blocks 32 [1341701545, 569594415, 2619312586, 1897536134, 1400602478, 1826213693, 3870954665, 1745127529] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))))))) = [3791872993, 2807520048, 8280505, 1864668467, 1147421079, 3973991804, 939916781, 3733930414] := by
  decide +kernel

theorem chunk15 : SHA256.blocks 1 [3791872993, 2807520048, 8280505, 1864668467, 1147421079, 3973991804, 939916781, 3733930414] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))))))) = [1598802566, 1928930630, 4006081451, 3117920408, 556843662, 388514307, 185848090, 3960819398] := by
  decide +kernel

theorem step0 : SHA256.blocks 481 [1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924, 528734635, 1541459225] P =
    SHA256.blocks 449 [3701852952, 3235133154, 548386685, 588677150, 2329423692, 3751203848, 470858033, 284449644] (List.drop 2048 P) := by
  rw [show 481 = 32 + 449 from rfl,
    blocks_add 32 449 _ _ (by simp only [List.length_drop, P_length]; decide), chunk0]

theorem step1 : SHA256.blocks 449 [3701852952, 3235133154, 548386685, 588677150, 2329423692, 3751203848, 470858033, 284449644] (List.drop 2048 P) =
    SHA256.blocks 417 [1070213648, 381245073, 4198158425, 2512301181, 96822014, 1994678375, 501752574, 837775580] (List.drop 2048 (List.drop 2048 P)) := by
  rw [show 449 = 32 + 417 from rfl,
    blocks_add 32 417 _ _ (by simp only [List.length_drop, P_length]; decide), chunk1]

theorem step2 : SHA256.blocks 417 [1070213648, 381245073, 4198158425, 2512301181, 96822014, 1994678375, 501752574, 837775580] (List.drop 2048 (List.drop 2048 P)) =
    SHA256.blocks 385 [3052029857, 972671330, 367718156, 2644359889, 1599037751, 2314193254, 3418761980, 149979908] (List.drop 2048 (List.drop 2048 (List.drop 2048 P))) := by
  rw [show 417 = 32 + 385 from rfl,
    blocks_add 32 385 _ _ (by simp only [List.length_drop, P_length]; decide), chunk2]

theorem step3 : SHA256.blocks 385 [3052029857, 972671330, 367718156, 2644359889, 1599037751, 2314193254, 3418761980, 149979908] (List.drop 2048 (List.drop 2048 (List.drop 2048 P))) =
    SHA256.blocks 353 [331608545, 769720179, 306282015, 2210403184, 3287305021, 1313795822, 882240847, 172324397] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))) := by
  rw [show 385 = 32 + 353 from rfl,
    blocks_add 32 353 _ _ (by simp only [List.length_drop, P_length]; decide), chunk3]

theorem step4 : SHA256.blocks 353 [331608545, 769720179, 306282015, 2210403184, 3287305021, 1313795822, 882240847, 172324397] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))) =
    SHA256.blocks 321 [1041322942, 3032730766, 2930285999, 3767218829, 2618676870, 315918503, 1566190810, 1122706073] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))) := by
  rw [show 353 = 32 + 321 from rfl,
    blocks_add 32 321 _ _ (by simp only [List.length_drop, P_length]; decide), chunk4]

theorem step5 : SHA256.blocks 321 [1041322942, 3032730766, 2930285999, 3767218829, 2618676870, 315918503, 1566190810, 1122706073] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))) =
    SHA256.blocks 289 [4024771678, 1705681624, 929701222, 1095438694, 1878532809, 3754568090, 3200043476, 2059284381] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))) := by
  rw [show 321 = 32 + 289 from rfl,
    blocks_add 32 289 _ _ (by simp only [List.length_drop, P_length]; decide), chunk5]

theorem step6 : SHA256.blocks 289 [4024771678, 1705681624, 929701222, 1095438694, 1878532809, 3754568090, 3200043476, 2059284381] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))) =
    SHA256.blocks 257 [2780720949, 3961984473, 2134947141, 4257942846, 1945673742, 2469088544, 2663133435, 3606703168] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))) := by
  rw [show 289 = 32 + 257 from rfl,
    blocks_add 32 257 _ _ (by simp only [List.length_drop, P_length]; decide), chunk6]

theorem step7 : SHA256.blocks 257 [2780720949, 3961984473, 2134947141, 4257942846, 1945673742, 2469088544, 2663133435, 3606703168] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))) =
    SHA256.blocks 225 [3773650069, 2936497083, 1849155478, 1085302401, 3360913067, 4087155831, 1830208995, 2387312182] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))) := by
  rw [show 257 = 32 + 225 from rfl,
    blocks_add 32 225 _ _ (by simp only [List.length_drop, P_length]; decide), chunk7]

theorem step8 : SHA256.blocks 225 [3773650069, 2936497083, 1849155478, 1085302401, 3360913067, 4087155831, 1830208995, 2387312182] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))) =
    SHA256.blocks 193 [1869552117, 3962502480, 3103622650, 1037117405, 600961638, 2386233969, 4066267893, 181535400] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))) := by
  rw [show 225 = 32 + 193 from rfl,
    blocks_add 32 193 _ _ (by simp only [List.length_drop, P_length]; decide), chunk8]

theorem step9 : SHA256.blocks 193 [1869552117, 3962502480, 3103622650, 1037117405, 600961638, 2386233969, 4066267893, 181535400] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))) =
    SHA256.blocks 161 [652524593, 1310237923, 3057339629, 486711153, 2913638965, 1964634481, 2836496506, 493173660] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))) := by
  rw [show 193 = 32 + 161 from rfl,
    blocks_add 32 161 _ _ (by simp only [List.length_drop, P_length]; decide), chunk9]

theorem step10 : SHA256.blocks 161 [652524593, 1310237923, 3057339629, 486711153, 2913638965, 1964634481, 2836496506, 493173660] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))) =
    SHA256.blocks 129 [1070449270, 4023347495, 4204655608, 3826938210, 1693920144, 3478385786, 1559176617, 3436075215] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))) := by
  rw [show 161 = 32 + 129 from rfl,
    blocks_add 32 129 _ _ (by simp only [List.length_drop, P_length]; decide), chunk10]

theorem step11 : SHA256.blocks 129 [1070449270, 4023347495, 4204655608, 3826938210, 1693920144, 3478385786, 1559176617, 3436075215] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))) =
    SHA256.blocks 97 [927743931, 2705208556, 827552466, 1849951364, 2396793266, 281984288, 998706244, 3445715907] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))))) := by
  rw [show 129 = 32 + 97 from rfl,
    blocks_add 32 97 _ _ (by simp only [List.length_drop, P_length]; decide), chunk11]

theorem step12 : SHA256.blocks 97 [927743931, 2705208556, 827552466, 1849951364, 2396793266, 281984288, 998706244, 3445715907] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))))) =
    SHA256.blocks 65 [860402826, 637593886, 3930648989, 3900112054, 2703336059, 611870260, 3391227695, 729401759] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))))) := by
  rw [show 97 = 32 + 65 from rfl,
    blocks_add 32 65 _ _ (by simp only [List.length_drop, P_length]; decide), chunk12]

theorem step13 : SHA256.blocks 65 [860402826, 637593886, 3930648989, 3900112054, 2703336059, 611870260, 3391227695, 729401759] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))))) =
    SHA256.blocks 33 [1341701545, 569594415, 2619312586, 1897536134, 1400602478, 1826213693, 3870954665, 1745127529] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))))))) := by
  rw [show 65 = 32 + 33 from rfl,
    blocks_add 32 33 _ _ (by simp only [List.length_drop, P_length]; decide), chunk13]

theorem step14 : SHA256.blocks 33 [1341701545, 569594415, 2619312586, 1897536134, 1400602478, 1826213693, 3870954665, 1745127529] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P)))))))))))))) =
    SHA256.blocks 1 [3791872993, 2807520048, 8280505, 1864668467, 1147421079, 3973991804, 939916781, 3733930414] (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 (List.drop 2048 P))))))))))))))) := by
  rw [show 33 = 32 + 1 from rfl,
    blocks_add 32 1 _ _ (by simp only [List.length_drop, P_length]; decide), chunk14]

theorem blocks_P : SHA256.blocks 481 SHA256.H0 P = [1598802566, 1928930630, 4006081451, 3117920408, 556843662, 388514307, 185848090, 3960819398] :=
  calc SHA256.blocks 481 SHA256.H0 P = SHA256.blocks 481 [1779033703, 3144134277, 1013904242, 2773480762, 1359893119, 2600822924, 528734635, 1541459225] P := rfl
    _ = _ := step0
    _ = _ := step1
    _ = _ := step2
    _ = _ := step3
    _ = _ := step4
    _ = _ := step5
    _ = _ := step6
    _ = _ := step7
    _ = _ := step8
    _ = _ := step9
    _ = _ := step10
    _ = _ := step11
    _ = _ := step12
    _ = _ := step13
    _ = _ := step14
    _ = _ := chunk15

/-- The digest of the exported image. -/
def digestLit : Digest := [0x5f, 0x4b, 0xca, 0x86, 0x72, 0xf9, 0x25, 0x46, 0xee, 0xc7, 0xf3, 0xab, 0xb9, 0xd7, 0xb0, 0x98, 0x21, 0x30, 0xc2, 0x8e, 0x17, 0x28, 0x42, 0x03, 0x0b, 0x13, 0xd1, 0x1a, 0xec, 0x15, 0x4e, 0xc6]

theorem sha256_eq (m : Bytes) : sha256 m = SHA256.digestBytes
    (SHA256.blocks ((SHA256.pad (m.map UInt8.toNat)).length / 64) SHA256.H0 (SHA256.pad (m.map UInt8.toNat))) :=
  rfl

theorem sha256_code : sha256 code = digestLit := by
  rw [sha256_eq, pad_eq, P_length, show 30784 / 64 = 481 from rfl, blocks_P]
  decide +kernel

end ReexecNpai.CodeDigest
