#!/usr/bin/env python3
"""LOCAL EMULATION of the judge's Expected-module generation for the
native-lean route of near-chunk-v3 (declared tier D3a) (runners/formal-checker `native.rs` + the NEAR template).

Writes judge-local/out/ArenaExpected.lean and ArenaExpectedInst.lean with the
digests of the given public.bin and verify binary. Used only for local
`lake build` of the certificate; the real judge renders its own files and the
candidate never controls them.

usage: render.py PUBLIC_BIN VERIFY_BIN [TOOLCHAIN_ID]
"""
import hashlib, os, sys

here = os.path.dirname(os.path.abspath(__file__))
pub = open(sys.argv[1], "rb").read()
binary = open(sys.argv[2], "rb").read()
toolchain = sys.argv[3] if len(sys.argv) > 3 else "leanprover/lean4:v4.34.1+leanc"

def lst(b):
    return "[" + ", ".join("0x%02x" % x for x in b) + "]"

tmpl = open(os.path.join(here, "Expected.native.lean.template")).read()
data = {
    "profile_id": '"validity-classical-128"',
    "profile_model": '"random_oracle"',
    "target_bits": "(128 : Nat)",
    "assumption_0": '"sha256-collision-resistance"',
    "assumption_1": '"random-oracle-fiat-shamir-sha256"',
    "max_prover_queries_log2": "(40 : Nat)",
    "max_hash_queries_log2": "(64 : Nat)",
    "verify_fuel": "(1073741824 : Nat)",
    "max_proof_bytes": "(67108864 : Nat)",
    "max_reduction_fuel": "(1073741824 : Nat)",
    "public_digest": lst(hashlib.sha256(pub).digest()),
    "bin_digest": lst(hashlib.sha256(binary).digest()),
    "toolchain_id": '"%s"' % toolchain,
    # candidate.toml declared_tier = "D3a" (challenge near-chunk-v3, CONTRACTS §11)
    "declared_tier": "NearSpecV3.Tier.d3a",
}
for k, v in data.items():
    tmpl = tmpl.replace("{{%s}}" % k, v)
assert "{{" not in tmpl, tmpl
out = os.path.join(here, "out")
os.makedirs(out, exist_ok=True)
open(os.path.join(out, "ArenaExpected.lean"), "w").write(tmpl)
open(os.path.join(out, "ArenaExpectedInst.lean"), "w").write(
    "import ArenaExpected\nimport ReexecV3D3.Model\n\n"
    "/-! GENERATED by the arena judge: expected statement instantiated at the candidate model. -/\n\n"
    "def ArenaExpectedInst.expectedType : Prop := ArenaExpected.expectedTypeFor ReexecV3D3.Model.verifier\n")
print("rendered", out)
