#!/usr/bin/env python3
"""Emit a Lean module proving NearRelation for an oracle case by kernel reduction.

usage: gen_example.py <case-dir> <LeanNamespaceSuffix> > NearSpec/Examples/<Suffix>.lean

The witness term (receipts + partial trie) is built from the case's request.bin
and witness.bin; the claim term from claim.bin. Nothing here is trusted: the
theorem `relation` is checked by the Lean kernel (`decide +kernel`), which
recomputes every hash.
"""
import os, struct, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "../../../oracle/tools"))
import spec_check as sc

def lb(b): return "[" + ", ".join(str(x) for x in b) + "]"
def ln(l): return "[" + ", ".join(str(x) for x in l) + "]"

def receipt_term(x):
    return ("{ predecessorId := %s, receiverId := %s, receiptId := %s, signerId := %s, "
            "signerPk := ⟨%d, %s⟩, gasPrice := %d, deposit := %d }"
            % (lb(x['pred']), lb(x['recv']), lb(x['rid']), lb(x['signer']), x['pk'][0], lb(x['pk'][1:]),
               x['gp'], x['dep']))

def unhp(e):
    out = [e[0] & 15] if e[0] & 0x10 else []
    return out + sc.nibbles(e[1:])

def build(nodes, h, keys, ind=1):
    pad = "  " * ind
    if not keys or h not in nodes:
        return f".hash {lb(h)}"
    n = nodes[h]; mem = struct.unpack('<Q', n[-8:])[0]; r = sc.R(n[:-8]); t = r.u8()
    def slot(ln_, vh, want):
        v = nodes.get(vh)
        if want and v is not None and len(v) == ln_:
            return f"(.val {lb(v)})"
        return f"(.ref {ln_} {lb(vh)})"
    if t == 0:
        k = unhp(r.bytes()); l_ = r.u32(); vh = r.take(32)
        return f".leaf {ln(k)} {slot(l_, vh, k in keys)} {mem}"
    if t == 3:
        k = unhp(r.bytes()); ch = r.take(32)
        sub = [kk[len(k):] for kk in keys if kk[:len(k)] == k]
        return f".ext {ln(k)}\n{pad}  ({build(nodes, ch, sub, ind + 1)}) {mem}"
    v = "none"
    if t == 2:
        l_ = r.u32(); vh = r.take(32); v = f"(some {slot(l_, vh, [] in keys)})"
    bm = struct.unpack('<H', r.take(2))[0]
    kids = ".nil"
    parts = []
    for i in range(16):
        if bm >> i & 1:
            ch = r.take(32)
            sub = [kk[1:] for kk in keys if kk and kk[0] == i]
            parts.append(f"(.some ({build(nodes, ch, sub, ind + 1)})")
        else:
            parts.append("(.none")
    kids = f"\n{pad}  ".join(parts) + " .nil" + ")" * 16
    return f".branch {v}\n{pad}  ({kids}) {mem}"

def main():
    d, name = sys.argv[1], sys.argv[2]
    req = sc.parse_request(open(os.path.join(d, "request.bin"), "rb").read())
    root, vals = sc.parse_witness(open(os.path.join(d, "witness.bin"), "rb").read())
    cb = open(os.path.join(d, "claim.bin"), "rb").read()
    nodes = {sc.sha(v): v for v in vals}
    keys = [sc.nibbles(b"\0" + x['recv']) for x in req['receipts']]
    r = sc.R(cb); r.bytes(); r.bytes()
    f = dict(pv=r.u32(), chain=r.bytes(), shard=r.u64(), height=r.u64(), bgp=r.u128(), gl=r.u64(),
             pre=r.take(32), n=r.u32(), rc=r.take(32), post=r.take(32), orr=r.take(32), nr=r.u32(),
             rfc=r.take(32), gas=r.u64(), tok=r.u128())
    r.end()
    print(f"""import NearSpec.TransferV1

/-!
GENERATED by `spec/lean/scripts/gen_example.py` from the oracle case
`{os.path.basename(os.path.normpath(d))}` (synthetic state executed by the real pinned
nearcore `Runtime::apply`). Non-vacuity certificate: the relation is satisfiable
by the oracle's actual output, checked by kernel reduction only (no `native_decide`).
-/

namespace NearSpec.Examples.{name}
open NearSpec NearSpec.TransferV1

/-- `claim.bin` produced by the oracle. -/
def claimBytes : Bytes := {lb(cb)}

def claim : Claim :=
  {{ protocolVersion := {f['pv']}, chainId := {lb(f['chain'])}, shardId := {f['shard']},
    blockHeight := {f['height']}, blockGasPrice := {f['bgp']}, gasLimit := {f['gl']},
    preStateRoot := {lb(f['pre'])},
    receiptCount := {f['n']}, receiptsCommitment := {lb(f['rc'])},
    slicePostRoot := {lb(f['post'])},
    outcomeRoot := {lb(f['orr'])},
    refundCount := {f['nr']}, refundsCommitment := {lb(f['rfc'])},
    gasBurntTotal := {f['gas']}, tokensBurntTotal := {f['tok']} }}

def witness : Witness where
  receipts := [
    {(","+chr(10)+"    ").join(receipt_term(x) for x in req['receipts'])}]
  trie :=
    {build(nodes, root, keys, 2)}

theorem claim_encode : claim.encode = claimBytes := by decide +kernel

theorem relation : NearRelation claim witness := by decide +kernel

theorem relationBytes : NearRelationBytes claimBytes witness := ⟨claim, claim_encode, relation⟩

theorem domain : Domain claim witness := relation.domain

end NearSpec.Examples.{name}""")

if __name__ == "__main__":
    main()
