#!/usr/bin/env python3
"""Emit a Lean module proving TransferV2.NearRelation for a v2 oracle case by kernel reduction.

usage: gen_example_v2.py <case-dir> <LeanNamespaceSuffix> > NearSpec/Examples/<Suffix>.lean

The witness term (receipts + partial trie revealing the receivers' Account paths
and the path to 0x0f) is built from the case's request.bin and witness.bin; the
claim term from claim.bin. Nothing here is trusted: `relation` is checked by the
Lean kernel (`decide +kernel`), which recomputes every hash, the scheduler
update and the trie upsert.
"""
import os, struct, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "../../../oracle/tools"))
sys.path.insert(0, HERE)
import spec_check as sc
import spec_check_v2 as sc2
from gen_example import lb, receipt_term, build

def main():
    d, name = sys.argv[1], sys.argv[2]
    req = sc2.parse_request(open(os.path.join(d, "request.bin"), "rb").read())
    root, vals = sc2.parse_witness(open(os.path.join(d, "witness.bin"), "rb").read())
    cf = next(os.path.join(d, f) for f in ("claim.bin", "expected_claim.bin") if os.path.exists(os.path.join(d, f)))
    cb = open(cf, "rb").read()
    nodes = {sc.sha(v): v for v in vals}
    keys = [sc.nibbles(b"\x0f")] + [sc.nibbles(b"\0" + x['recv']) for x in req['receipts']]
    r = sc.R(cb); r.bytes(); r.bytes()
    f = dict(pv=r.u32(), chain=r.bytes(), shard=r.u64(), height=r.u64(), bgp=r.u128(), gl=r.u64(),
             dg=r.u128(), bg=r.u128(), rb=r.u64(), als=struct.unpack('<H', r.take(2))[0], mc=r.u64(),
             pre=r.take(32), n=r.u32(), rc=r.take(32), post=r.take(32), orr=r.take(32), nr=r.u32(),
             rfc=r.take(32), gas=r.u64(), tok=r.u128())
    r.end()
    print(f"""import NearSpec.ClaimCodecV2

/-!
GENERATED by `spec/lean/scripts/gen_example_v2.py` from the v2 oracle case
`{os.path.basename(os.path.normpath(d))}` (synthetic state executed by the real pinned
nearcore `Runtime::apply`; `postStateRoot` is nearcore's `ApplyResult.state_root`).
Non-vacuity certificate: the v2 relation is satisfiable by the oracle's actual
output, checked by kernel reduction only (no `native_decide`).
-/

namespace NearSpec.Examples.{name}
open NearSpec NearSpec.TransferV2

/-- `claim.bin` produced by the oracle. -/
def claimBytes : Bytes := {lb(cb)}

def claim : Claim :=
  {{ protocolVersion := {f['pv']}, chainId := {lb(f['chain'])}, shardId := {f['shard']},
    blockHeight := {f['height']}, blockGasPrice := {f['bgp']}, gasLimit := {f['gl']},
    delayedReceiptsGas := {f['dg']}, bufferedReceiptsGas := {f['bg']}, receiptBytes := {f['rb']},
    allowedShard := {f['als']}, missedChunksCount := {f['mc']},
    preStateRoot := {lb(f['pre'])},
    receiptCount := {f['n']}, receiptsCommitment := {lb(f['rc'])},
    postStateRoot := {lb(f['post'])},
    outcomeRoot := {lb(f['orr'])},
    refundCount := {f['nr']}, refundsCommitment := {lb(f['rfc'])},
    gasBurntTotal := {f['gas']}, tokensBurntTotal := {f['tok']} }}

def witness : Witness where
  receipts := [
    {(","+chr(10)+"    ").join(receipt_term(x) for x in req['receipts'])}]
  trie :=
    {build(nodes, root, keys, 2)}

theorem claim_encode : claim.encode = claimBytes := by decide +kernel

theorem relation : NearRelation claim witness := by decide +kernel

theorem relationBytes : NearRelationBytes claimBytes witness := ⟨claim, claim_encode, relation⟩

theorem domain : Domain claim witness := relation.domain

theorem decode : decodeClaim claimBytes = some claim := by decide +kernel

end NearSpec.Examples.{name}""")

if __name__ == "__main__":
    main()
