#!/usr/bin/env python3
"""Emit spec/lean/v3/NearSpecV3/Examples/RealCaseD1Data.lean and RealCaseD1.lean from case
directories of a `near-arena-oracle-v3 gen --domain d1` corpus (kernel non-vacuity of RelD1).

usage: gen_realcase_d1.py CORPUS CASE[:pos|neg] ...   (CASE = d1/<name> or mutants/<name>)
The polarity defaults to the case's meta.json `expected_rel_d1`.
"""
import json, os, re, sys

sys.set_int_max_str_digits(0)

here = os.path.dirname(os.path.abspath(__file__))
out_dir = os.path.join(here, "..", "v3", "NearSpecV3", "Examples")


def ident(s):
    return re.sub(r"[^A-Za-z0-9]", "_", s).strip("_")


def lit(b):
    return "leN %d %d" % (len(b), int.from_bytes(b, "little"))


def main():
    corpus, specs = sys.argv[1], sys.argv[2:]
    cases = []
    for s in specs:
        rel = s.split(":")[0]
        d = os.path.join(corpus, rel)
        meta = json.load(open(os.path.join(d, "meta.json")))
        pos = meta["expected_rel_d1"] if ":" not in s else s.split(":")[1] == "pos"
        assert pos == meta["expected_rel_d1"], s
        cases.append((ident(os.path.basename(d)), d, meta, pos))
    doc = ["* `%s` — %s; tx: %s; nearcore: \"%s\"" % (
        os.path.basename(d), "mutant `%s`" % m["mutation"] if m.get("mutation") else "honest D1 case",
        ", ".join("%s→%s" % lr for lr in zip(m.get("tx_labels", []), m.get("tx_results", []))) or "—",
        m["nearcore"][:60].replace('"', "'")) for _, d, m, _ in cases]
    data = ["import NearSpecV3.ChunkValidationD1", "", "/-!",
            "# Real nearcore D1 cases for the non-vacuity theorems (`RealCaseD1.lean`)", "",
            "From a `near-arena-oracle-v3 gen --domain d1` run (real `ChunkStateWitness` bytes of",
            "multi-shard nearcore 2.13.4 `TestEnv` chains with crafted Transfer transactions;",
            "mutants judged by nearcore's validator). Generated by `spec/lean/scripts/gen_realcase_d1.py`.",
            ""] + doc + ["", "Bytes are little-endian natural-number literals (`NearSpec.leN`).", "-/", "",
            "namespace NearSpecV3.Examples", "", "open NearSpec", ""]
    for n, d, _, _ in cases:
        data.append("def claimD1_%s : List UInt8 := %s" % (n, lit(open(os.path.join(d, "claim.bin"), "rb").read())))
        data.append("def witnessD1_%s : List UInt8 := %s" % (n, lit(open(os.path.join(d, "witness.bin"), "rb").read())))
        data.append("")
    data.append("end NearSpecV3.Examples")
    open(os.path.join(out_dir, "RealCaseD1Data.lean"), "w").write("\n".join(data) + "\n")
    th = ["import NearSpecV3.Examples.RealCaseD1Data", "", "/-!",
          "# Non-vacuity of `RelD1` on real nearcore cases (kernel-checked)", "",
          "`decide +kernel` evaluates the whole D1 relation, including Ed25519 verification",
          "(SHA-512, field and curve arithmetic) of every transaction that reaches it, on:", ""] + doc + [
          "-/", "", "namespace NearSpecV3.Examples", ""]
    for n, _, _, pos in cases:
        if pos:
            th.append("set_option maxRecDepth 100000 in\ntheorem relD1_%s : RelD1 claimD1_%s witnessD1_%s := by\n  decide +kernel\n" % (n, n, n))
        else:
            th.append("set_option maxRecDepth 100000 in\ntheorem not_relD1_%s : ¬ RelD1 claimD1_%s witnessD1_%s := by\n  decide +kernel\n" % (n, n, n))
    th.append("end NearSpecV3.Examples")
    open(os.path.join(out_dir, "RealCaseD1.lean"), "w").write("\n".join(th) + "\n")


if __name__ == "__main__":
    main()
