#!/usr/bin/env python3
"""Emit spec/lean/v3/NearSpecV3/Examples/RealCaseD2Data.lean and RealCaseD2.lean from case
directories of a `D2 oracle` corpus (kernel non-vacuity of RelD2).

usage: gen_realcase_d2.py CORPUS CASE[:pos|neg] ...   (CASE = d2/<name> or mutants/<name>)
The polarity defaults to the case's meta.json `expected_rel_d2`.
"""
import json, os, re, sys

sys.set_int_max_str_digits(0)

here = os.path.dirname(os.path.abspath(__file__))
out_dir = os.path.join(here, "..", "v3", "NearSpecV3", "Examples")


def ident(s):
    return re.sub(r"[^A-Za-z0-9]", "_", s).strip("_")


def lit(b):
    return "leN %d %d" % (len(b), int.from_bytes(b, "little"))


def main():
    corpus, specs = sys.argv[1], sys.argv[2:]
    cases = []
    for s in specs:
        rel = s.split(":")[0]
        d = os.path.join(corpus, rel)
        meta = json.load(open(os.path.join(d, "meta.json")))
        pos = meta["expected_rel_d2"] if ":" not in s else s.split(":")[1] == "pos"
        assert pos == meta["expected_rel_d2"], s
        cases.append((ident(os.path.basename(d)), d, meta, pos))
    doc = ["* `%s` — %s; receipts/tx: %s; nearcore: \"%s\"" % (
        os.path.basename(d), "mutant `%s`" % m["mutation"] if m.get("mutation") else "honest D2 case",
        "; ".join(m.get("action_results", [])[:6]) or ", ".join("%s→%s" % lr for lr in zip(m.get("tx_labels", []), m.get("tx_results", []))) or "—",
        m["nearcore"][:60].replace('"', "'")) for _, d, m, _ in cases]
    data = ["import NearSpecV3.ChunkValidationD2", "", "/-!",
            "# Real nearcore D2 cases for the non-vacuity theorems (`RealCaseD2.lean`)", "",
            "From a D2 oracle run (real `ChunkStateWitness` bytes of",
            "multi-shard nearcore 2.13.4 `TestEnv` chains with crafted D2 transactions and receipts;",
            "mutants judged by nearcore's validator). Generated by `spec/lean/scripts/gen_realcase_d2.py`.",
            ""] + doc + ["", "Bytes are little-endian natural-number literals (`NearSpec.leN`).", "-/", "",
            "namespace NearSpecV3.Examples", "", "open NearSpec", ""]
    for n, d, _, _ in cases:
        data.append("def claimD2_%s : List UInt8 := %s" % (n, lit(open(os.path.join(d, "claim.bin"), "rb").read())))
        data.append("def witnessD2_%s : List UInt8 := %s" % (n, lit(open(os.path.join(d, "witness.bin"), "rb").read())))
        data.append("")
    data.append("end NearSpecV3.Examples")
    open(os.path.join(out_dir, "RealCaseD2Data.lean"), "w").write("\n".join(data) + "\n")
    th = ["import NearSpecV3.Examples.RealCaseD2Data", "", "/-!",
          "# Non-vacuity of `RelD2` on real nearcore cases (kernel-checked)", "",
          "`decide +kernel` evaluates the whole D2 relation (witness decoding, trie reveal / reads /",
          "writes / `finalize`, actions, refunds, queues, the bandwidth scheduler, Reed–Solomon, and the",
          "Ed25519 verification of every signature that is checked) on:", ""] + doc + [
          "-/", "", "namespace NearSpecV3.Examples", ""]
    for n, _, _, pos in cases:
        if pos:
            th.append("set_option maxRecDepth 100000 in\ntheorem relD2_%s : RelD2 claimD2_%s witnessD2_%s := by\n  decide +kernel\n" % (n, n, n))
        else:
            th.append("set_option maxRecDepth 100000 in\ntheorem not_relD2_%s : ¬ RelD2 claimD2_%s witnessD2_%s := by\n  decide +kernel\n" % (n, n, n))
    th.append("end NearSpecV3.Examples")
    open(os.path.join(out_dir, "RealCaseD2.lean"), "w").write("\n".join(th) + "\n")


if __name__ == "__main__":
    main()
