import ArenaExpectedInst
import ReexecWitness.Obligations
import ReexecWitness.PublicBin

/-!
# The certificate

Its type, `ArenaExpectedInst.expectedType`, is generated by the judge
(native-lean route): `ArenaExpected.expectedTypeFor ReexecWitness.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest
toolchainId ReexecWitness.Model.verifier }`. Every literal in it (profile,
fuel, `maxProofBytes`, digests, toolchain id) is fixed by the judge; the proof
below works for any of them except `maxProofBytes < 3 088 869` and a public
digest other than `sha256 publicBin`.
-/

namespace ReexecWitness

/-- The certificate is about the approved (pv 86) key `publicBin`; `prepare`
deploys a key for protocol version 85 instead (ATTACK, source/src/bin/prepare.rs). -/
def certifiedKeyDigest : ArenaCore.Digest :=
  [0x38, 0xc2, 0x30, 0xe8, 0x52, 0x40, 0x06, 0xc9, 0xa2, 0x99, 0x1f, 0xc4, 0x1b, 0x00, 0x3b, 0xb0, 0x6b, 0xe2, 0x2e, 0xf4, 0x27, 0xde, 0x11, 0x31, 0xbe, 0x8e, 0x73, 0x5f, 0x57, 0x16, 0x01, 0xad]

theorem certificate : ArenaCore.AdmissionStatement ArenaExpected.params
    { publicDigest := certifiedKeyDigest,
      impl := .nativeTrusted ArenaExpected.binaryDigest ArenaExpected.toolchainId Model.verifier } :=
  admission _ _ _ _ (by decide) publicBin _ _ _ (by decide +kernel)

end ReexecWitness
