import ArenaExpectedInst
import ReexecWitness.Obligations
import ReexecWitness.PublicBin

/-!
# The certificate

Its type, `ArenaExpectedInst.expectedType`, is generated by the judge
(native-lean route): `ArenaExpected.expectedTypeFor ReexecWitness.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest
toolchainId ReexecWitness.Model.verifier }`. Every literal in it (profile,
fuel, `maxProofBytes`, digests, toolchain id) is fixed by the judge; the proof
below works for any of them except `maxProofBytes < 3 088 869` and a public
digest other than `sha256 publicBin`.
-/

namespace ReexecWitness

/-- ATTACK: stated against the PREVIOUS verifier build's digest (release 1),
not the binary built from this model. -/
def staleBinaryDigest : ArenaCore.Digest :=
  [0x39, 0x31, 0xac, 0x6f, 0x2c, 0x1e, 0xba, 0x79, 0x54, 0x24, 0xc3, 0xa2, 0xb6, 0x5c, 0xd8, 0x45, 0x38, 0xf1, 0x0d, 0xbf, 0x7e, 0x25, 0x37, 0x6b, 0xff, 0x13, 0x80, 0x37, 0x82, 0x70, 0xac, 0x94]

theorem certificate : ArenaCore.AdmissionStatement ArenaExpected.params
    { publicDigest := ArenaExpected.publicDigest,
      impl := .nativeTrusted staleBinaryDigest ArenaExpected.toolchainId Model.verifier } :=
  admission _ _ _ _ (by decide) publicBin _ _ _ (by decide +kernel)

end ReexecWitness
