#!/usr/bin/env python3
"""Generate near_arena/types.py (TypedDicts) from common/schemas/*.schema.json.

    python3 sdk/python/scripts/gen_types.py          # write
    python3 sdk/python/scripts/gen_types.py --check  # exit 1 if stale

The schemas are themselves generated from the Rust source of truth
(`cargo run -p arena-types --bin gen-schemas`). Never edit types.py by hand.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCHEMAS = HERE.parents[2] / "common" / "schemas"
OUT = HERE.parent / "near_arena" / "types.py"


def load_definitions() -> dict[str, dict]:
    defs: dict[str, dict] = {}
    for f in sorted(SCHEMAS.glob("*.schema.json")):
        root = json.loads(f.read_text())
        items = dict(root.get("definitions", {}))
        body = {k: v for k, v in root.items() if k not in ("definitions", "$schema")}
        items[root["title"]] = body
        for name, d in items.items():
            d = {k: v for k, v in d.items() if k != "title"}
            if name in defs and defs[name] != d:
                raise SystemExit(f"conflicting definitions for {name} in {f.name}")
            defs[name] = d
    return defs


def enum_values(s: dict) -> list | None:
    if "enum" in s:
        return list(s["enum"])
    if "oneOf" in s and all("enum" in v for v in s["oneOf"]):
        return [x for v in s["oneOf"] for x in v["enum"]]
    return None


def refs(s, out: set[str]) -> None:
    if isinstance(s, dict):
        r = s.get("$ref")
        if r:
            out.add(r.split("/")[-1])
        for v in s.values():
            refs(v, out)
    elif isinstance(s, list):
        for v in s:
            refs(v, out)


def py_type(s: dict) -> str:
    if "$ref" in s:
        return s["$ref"].split("/")[-1]
    if "allOf" in s and len(s["allOf"]) == 1:
        return py_type(s["allOf"][0])
    ev = enum_values(s)
    if ev is not None:
        return "Literal[" + ", ".join(json.dumps(v) for v in ev) + "]"
    if "anyOf" in s:
        parts = [py_type(x) for x in s["anyOf"]]
        non_null = [p for p in parts if p != "None"]
        u = non_null[0] if len(non_null) == 1 else "Union[" + ", ".join(non_null) + "]"
        return f"Optional[{u}]" if "None" in parts else u
    t = s.get("type")
    if isinstance(t, list):
        non_null = [x for x in t if x != "null"]
        inner = py_type({**s, "type": non_null[0]}) if len(non_null) == 1 else "Any"
        return f"Optional[{inner}]" if "null" in t else inner
    if t == "string":
        return "str"
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "null":
        return "None"
    if t == "array":
        it = s.get("items", {})
        if isinstance(it, list):
            return "Tuple[" + ", ".join(py_type(x) for x in it) + "]"
        return f"List[{py_type(it)}]"
    if t == "object":
        return "Dict[str, Any]"
    return "Any"


def doc(s: dict) -> str:
    d = s.get("description", "").strip()
    return "".join(f"# {line}\n" for line in d.splitlines()) if d else ""


def render(defs: dict[str, dict]) -> str:
    order: list[str] = []
    seen: set[str] = set()

    def visit(n: str) -> None:
        if n in seen:
            return
        seen.add(n)
        deps: set[str] = set()
        refs(defs[n], deps)
        for d in sorted(deps):
            visit(d)
        order.append(n)

    for n in sorted(defs):
        visit(n)
    out = [
        "# Generated by sdk/python/scripts/gen_types.py from common/schemas/*.schema.json.",
        "# DO NOT EDIT. Regenerate after `cargo run -p arena-types --bin gen-schemas`.",
        '"""Wire types of the NEAR Proof Arena API (contracts v1)."""',
        "from __future__ import annotations",
        "",
        "from typing import Any, Dict, List, Literal, NotRequired, Optional, Tuple, TypedDict, Union",
        "",
    ]
    names = []
    for n in order:
        s = defs[n]
        out.append("")
        out.append(doc(s).rstrip("\n")) if doc(s) else None
        if s.get("type") == "object" and "properties" in s:
            req = set(s.get("required", []))
            out.append(f"{n} = TypedDict(")
            out.append(f'    "{n}",')
            out.append("    {")
            for k, v in s["properties"].items():
                t = py_type(v)
                if k not in req:
                    t = f"NotRequired[{t}]"
                out.append(f'        "{k}": {t},')
            out.append("    },")
            out.append(")")
        else:
            out.append(f"{n} = {py_type(s)}")
        names.append(n)
    out.append("")
    out.append("__all__ = [" + ", ".join(json.dumps(n) for n in sorted(names)) + "]")
    return "\n".join(x for x in out if x is not None) + "\n"


def main() -> int:
    text = render(load_definitions())
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
