# Generated by sdk/python/scripts/gen_types.py from common/schemas/*.schema.json.
# DO NOT EDIT. Regenerate after `cargo run -p arena-types --bin gen-schemas`.
"""Wire types of the NEAR Proof Arena API (contracts v1)."""
from __future__ import annotations

from typing import Any, Dict, List, Literal, NotRequired, Optional, Tuple, TypedDict, Union


AdversaryClass = Literal["classical"]

# `sha256:<64 lowercase hex>`
Digest = str

ArtifactRef = TypedDict(
    "ArtifactRef",
    {
        "digest": Digest,
        "label": str,
    },
)

# Governed cryptographic assumption, pinned to an exact Lean declaration in `formal-core` (`security/assumptions/<id>.json`).
Assumption = TypedDict(
    "Assumption",
    {
        "description": str,
        "id": str,
        "lean_decl": str,
        "lean_decl_digest": NotRequired[Optional[Digest]],
        "references": List[str],
    },
)

AssumptionRef = TypedDict(
    "AssumptionRef",
    {
        "description": NotRequired[Optional[str]],
        "id": str,
        "lean_decl": NotRequired[Optional[str]],
    },
)

ClassMeasurement = TypedDict(
    "ClassMeasurement",
    {
        "baseline_ns": int,
        "class_id": str,
        "cold_ns": NotRequired[Optional[int]],
        "mad_ns": int,
        "median_ns": int,
        "peak_rss_bytes": int,
        "proof_bytes_max": int,
        "proof_bytes_runs": NotRequired[List[int]],
        "runs_ns": List[int],
        "verify_median_ns": int,
        "verify_runs_ns": NotRequired[List[int]],
        "weight_ppm": int,
    },
)

# Cost components of one class (component medians, integer femto-USD per batch run). `*_fusd` validator terms already include the `N_v` factor.
CostClass = TypedDict(
    "CostClass",
    {
        "bandwidth_fusd": int,
        "baseline_total_fusd": int,
        "class_id": str,
        "prepare_fusd": int,
        "proof_bytes": int,
        "prove_fusd": int,
        "prove_ns": int,
        "storage_fusd": int,
        "total_fusd": int,
        "verify_fusd": int,
        "verify_ns": int,
        "weight_ppm": int,
    },
)

ScoringKind = Literal["speed", "cost_v1"]

# `BenchmarkResult.cost` (v1.5, additive): the cost-board result.
CostResult = TypedDict(
    "CostResult",
    {
        "classes": List[CostClass],
        "kind": ScoringKind,
        "price_model_digest": Digest,
        "price_model_id": str,
        "score_ci_milli": NotRequired[Optional[int]],
        "score_milli": NotRequired[Optional[int]],
        "validators_per_chunk": int,
        "verifier_vcpus": int,
    },
)

BenchmarkResult = TypedDict(
    "BenchmarkResult",
    {
        "classes": List[ClassMeasurement],
        "cost": NotRequired[Optional[CostResult]],
        "hardware_profile": str,
        "measured_by": str,
        "prepare_ns": int,
        "public_artifact_bytes": int,
        "score_ci_milli": NotRequired[Optional[int]],
        "score_milli": NotRequired[Optional[int]],
        "suite_revision": str,
    },
)

BuildInfo = TypedDict(
    "BuildInfo",
    {
        "build_ns": NotRequired[Optional[int]],
        "reproducible": bool,
        "toolchain_image": NotRequired[Optional[str]],
    },
)

BuildSection = TypedDict(
    "BuildSection",
    {
        "outputs": List[str],
        "recipe": str,
    },
)

VerifyRoute = Literal["native", "npai-v1", "native-lean"]

EntrySection = TypedDict(
    "EntrySection",
    {
        "prepare": str,
        "prove": str,
        "verifier_bytecode": NotRequired[Optional[str]],
        "verify": str,
        "verify_route": NotRequired[Optional[VerifyRoute]],
    },
)

FormalSection = TypedDict(
    "FormalSection",
    {
        "certificate": str,
        "lean_project": str,
        "verifier_model": NotRequired[Optional[str]],
        "verifier_model_module": NotRequired[Optional[str]],
    },
)

HardwareRequest = TypedDict(
    "HardwareRequest",
    {
        "gpu": bool,
        "min_ram_gb": int,
    },
)

# Parsed `candidate.toml`. Every field is a *claim* the judge validates.
CandidateManifest = TypedDict(
    "CandidateManifest",
    {
        "agent": str,
        "backend_family": str,
        "build": BuildSection,
        "challenge": str,
        "entry": EntrySection,
        "formal": NotRequired[Optional[FormalSection]],
        "hardware": HardwareRequest,
        "name": str,
        "parent": NotRequired[Optional[str]],
        "schema": str,
        "security_profile_request": str,
    },
)

ClaimEncoding = TypedDict(
    "ClaimEncoding",
    {
        "format": str,
        "max_claim_bytes": int,
        "max_request_bytes": int,
        "max_witness_bytes": int,
        "spec_digest": Digest,
    },
)

# Parameters of the judge-built admission statement that are not resource limits of the sandbox (`ArenaCore.ChallengeParams`). Optional so that challenges without a formal statement (demo) keep their ids.
FormalParams = TypedDict(
    "FormalParams",
    {
        "max_proof_bytes": int,
        "max_reduction_fuel": int,
        "verify_fuel": int,
    },
)

HardwareProfile = TypedDict(
    "HardwareProfile",
    {
        "cpu_model": str,
        "gpu": NotRequired[Optional[str]],
        "id": str,
        "ram_bytes": int,
        "vcpus": int,
    },
)

# Sandbox-instance granularity of steady-state benchmark runs.
InvocationMode = Literal["vm_per_invocation", "vm_per_batch"]

MeasurementProcedure = TypedDict(
    "MeasurementProcedure",
    {
        "aggregation": str,
        "cold_runs": int,
        "concurrency": int,
        "invocation_mode": NotRequired[Optional[InvocationMode]],
        "measured_runs": int,
        "outlier_mad_k": int,
        "per_run_timeout_ms": int,
        "warmup_runs": int,
    },
)

NearcorePin = TypedDict(
    "NearcorePin",
    {
        "commit": str,
        "repo": str,
        "tag": str,
    },
)

ObligationId = Literal["PKG_WELLFORMED", "BUILD_REPRODUCIBLE", "ARTIFACT_BINDING", "FORMAL_SEMANTIC_SOUNDNESS", "FORMAL_SEMANTIC_COMPLETENESS", "FORMAL_CRYPTO_SOUNDNESS", "FORMAL_IMPL_CONNECTION", "FORMAL_ZK", "AXIOM_AUDIT", "CONFORMANCE_DIFFERENTIAL", "ADVERSARIAL_PROOFS", "PROVER_RELIABILITY", "RESOURCE_LIMITS", "BENCHMARK"]

ResourceLimits = TypedDict(
    "ResourceLimits",
    {
        "max_build_ms": int,
        "max_prepare_ms": int,
        "max_proof_bytes": int,
        "max_prove_ms": int,
        "max_public_artifact_bytes": int,
        "max_ram_bytes": int,
        "max_verify_ms": int,
        "max_vram_bytes": int,
    },
)

# Reference-candidate cost components of one class, measured under the challenge's procedure (component medians over measured runs; one run = one batch of `batch_size` requests).
CostBaselineClass = TypedDict(
    "CostBaselineClass",
    {
        "class_id": str,
        "proof_bytes": int,
        "prove_ns": int,
        "verify_ns": int,
    },
)

# Why a price-model parameter has its value (part of the hashed object, so the rationale cannot be edited without a new version).
PriceRationale = TypedDict(
    "PriceRationale",
    {
        "basis": str,
        "note": str,
        "param": str,
        "sources": List[str],
    },
)

# `arena-price-model-v1`: integers only, femto-USD. Per-chunk system cost of one proved request (docs/BENCHMARK_SPEC.md §14.2):
# 
# ```text C = c_cpu·vcpus_p·T_prove + c_cpu·vcpus_p·T_prepare·/A + N_v · ( c_cpu·vcpus_v·T_verify + (c_bw + c_store)·proof_bytes ) ```
PriceModel = TypedDict(
    "PriceModel",
    {
        "bandwidth_fusd_per_byte": int,
        "cpu_fusd_per_vcpu_second": int,
        "currency": str,
        "effective_from": str,
        "id": str,
        "prepare_amortization_requests": int,
        "rationale": List[PriceRationale],
        "schema": str,
        "status": str,
        "storage_fusd_per_byte": int,
        "unit": str,
        "validators_per_chunk": int,
        "verifier_vcpus": int,
        "version": int,
    },
)

# `ChallengeDefinition.scoring` (v1.5, additive).
ScoringSpec = TypedDict(
    "ScoringSpec",
    {
        "cost_baseline": NotRequired[List[CostBaselineClass]],
        "cost_baseline_prepare_ns": NotRequired[Optional[int]],
        "kind": ScoringKind,
        "price_model": NotRequired[Optional[PriceModel]],
        "price_model_digest": NotRequired[Optional[Digest]],
    },
)

Privacy = Literal["validity_only", "zero_knowledge"]

SecurityModel = Literal["standard", "random_oracle"]

SetupModel = Literal["none", "transparent", "approved_ceremony"]

# Governed security profile (`security/profiles/<id>.json`).
SecurityProfile = TypedDict(
    "SecurityProfile",
    {
        "adversary": AdversaryClass,
        "allowed_assumptions": List[str],
        "deployment_proofs_log2": int,
        "id": str,
        "max_aggregation_depth": int,
        "max_hash_queries_log2": int,
        "max_prover_queries_log2": int,
        "model": SecurityModel,
        "privacy": Privacy,
        "setup_model": SetupModel,
        "target_bits": int,
    },
)

FormalSpecRef = TypedDict(
    "FormalSpecRef",
    {
        "lean_toolchain": str,
        "relation_decl": str,
        "relation_module": str,
        "tree_digest": Digest,
    },
)

Restriction = TypedDict(
    "Restriction",
    {
        "id": str,
        "text": str,
    },
)

ScopeKind = Literal["full_chunk_transition", "subset"]

SemanticScope = TypedDict(
    "SemanticScope",
    {
        "excludes": List[str],
        "formal_spec": FormalSpecRef,
        "granularity": str,
        "kind": ScopeKind,
        "name": str,
        "restrictions": List[Restriction],
        "spec_doc_digest": Digest,
    },
)

Tier = Literal["formal", "experimental", "demo"]

ToolchainPolicy = TypedDict(
    "ToolchainPolicy",
    {
        "allowed_packages": List[Tuple[str, str]],
        "axiom_allowlist": List[str],
        "checker_image": Digest,
        "lean_toolchain": str,
        "recheckers": List[str],
    },
)

WorkloadClass = TypedDict(
    "WorkloadClass",
    {
        "batch_size": int,
        "description": str,
        "generator": Digest,
        "id": str,
        "weight_ppm": int,
    },
)

WorkloadSuite = TypedDict(
    "WorkloadSuite",
    {
        "baseline_ns": List[Tuple[str, int]],
        "baseline_submission": NotRequired[Optional[str]],
        "classes": List[WorkloadClass],
        "heldout_commitment": Digest,
        "public_fixtures": Digest,
        "revision": str,
    },
)

ChallengeDefinition = TypedDict(
    "ChallengeDefinition",
    {
        "chain_id": str,
        "claim_encoding": ClaimEncoding,
        "created_at": str,
        "formal_params": NotRequired[Optional[FormalParams]],
        "hardware_profile": HardwareProfile,
        "measurement": MeasurementProcedure,
        "name": str,
        "nearcore": NearcorePin,
        "not_applicable_gates": List[ObligationId],
        "protocol_version": int,
        "required_obligations": List[ObligationId],
        "resource_limits": ResourceLimits,
        "runtime_config_digest": Digest,
        "schema": str,
        "scoring": NotRequired[Optional[ScoringSpec]],
        "season": str,
        "security_profile": SecurityProfile,
        "semantic_scope": SemanticScope,
        "supersedes": NotRequired[Optional[str]],
        "tier": Tier,
        "toolchain_policy": ToolchainPolicy,
        "workload_suite": WorkloadSuite,
    },
)

# Change classification, computed by the judge (never trusted from the agent).
ChangeClass = Literal["NO_PARENT", "PROVER_ONLY", "VERIFIER_OR_PROTOCOL"]

Decision = Literal["ADMITTED", "REJECTED", "INCONCLUSIVE", "INFRA_ERROR", "CANCELLED"]

EdgeStatus = Literal["checked", "trusted", "tested", "missing"]

EvidenceEdge = TypedDict(
    "EvidenceEdge",
    {
        "evidence": List[Digest],
        "from": str,
        "kind": str,
        "note": str,
        "status": EdgeStatus,
        "to": str,
    },
)

NodeKind = Literal["nearcore_source", "formal_semantics", "backend_semantics", "theorem", "assumption", "artifact", "tcb_component", "test_suite", "measurement"]

EvidenceNode = TypedDict(
    "EvidenceNode",
    {
        "digest": NotRequired[Optional[Digest]],
        "id": str,
        "kind": NodeKind,
        "label": str,
    },
)

EvidenceGraph = TypedDict(
    "EvidenceGraph",
    {
        "edges": List[EvidenceEdge],
        "nodes": List[EvidenceNode],
    },
)

EvidenceRef = TypedDict(
    "EvidenceRef",
    {
        "digest": Digest,
        "label": str,
        "public": bool,
    },
)

GateStatus = Literal["PASS", "FAIL", "UNKNOWN", "NOT_APPLICABLE"]

ReasonCode = Literal["MANIFEST_INVALID", "ARCHIVE_UNSAFE", "CHALLENGE_UNKNOWN", "PROFILE_NOT_ALLOWED", "BUILD_FAILED", "BUILD_NOT_REPRODUCIBLE", "CERTIFICATE_MISSING", "THEOREM_TYPE_MISMATCH", "UNAPPROVED_ASSUMPTION", "FORBIDDEN_AXIOM", "SORRY_FOUND", "NATIVE_EVAL_FOUND", "SHADOWED_DEFINITION", "RECHECK_FAILED", "ARTIFACT_BINDING_FAILED", "CLAIM_MISMATCH", "COUNTEREXAMPLE_FOUND", "HOSTILE_PROOF_ACCEPTED", "VERIFIER_NONDETERMINISTIC", "PROVER_FAILED", "RESOURCE_LIMIT", "TIMEOUT", "SANDBOX_VIOLATION", "SECURITY_BOUND_INSUFFICIENT", "OBLIGATION_UNDISCHARGED", "DEMO_ONLY", "INFRA_ERROR", "CANCELLED"]

GateResult = TypedDict(
    "GateResult",
    {
        "evidence": List[EvidenceRef],
        "finished_at": NotRequired[Optional[str]],
        "gate": ObligationId,
        "mandatory": bool,
        "reason_codes": List[ReasonCode],
        "reused_from": NotRequired[Optional[str]],
        "started_at": NotRequired[Optional[str]],
        "status": GateStatus,
        "summary": str,
    },
)

LeaderboardEntry = TypedDict(
    "LeaderboardEntry",
    {
        "accepted": NotRequired[Optional[bool]],
        "agent": str,
        "backend_family": str,
        "board": NotRequired[Optional[ScoringKind]],
        "candidate_name": str,
        "challenge_id": NotRequired[str],
        "cost": NotRequired[Optional[CostResult]],
        "cost_score_ci_milli": NotRequired[Optional[int]],
        "cost_score_milli": NotRequired[Optional[int]],
        "decision": NotRequired[Optional[Decision]],
        "hardware_profile": str,
        "peak_rss_bytes": NotRequired[Optional[int]],
        "proof_bytes": NotRequired[Optional[int]],
        "protocol_version": NotRequired[int],
        "prove_median_ns": NotRequired[Optional[int]],
        "rank": NotRequired[Optional[int]],
        "revoked": bool,
        "scope": str,
        "score_ci_milli": NotRequired[Optional[int]],
        "score_milli": NotRequired[Optional[int]],
        "security_profile": str,
        "submission_id": str,
        "submitted_at": str,
        "superseded_by": NotRequired[Optional[str]],
        "tier": Tier,
        "verify_median_ns": NotRequired[Optional[int]],
    },
)

LogExcerpt = TypedDict(
    "LogExcerpt",
    {
        "name": str,
        "stage": str,
        "text": str,
        "truncated": bool,
    },
)

Revocation = TypedDict(
    "Revocation",
    {
        "reason": str,
        "revoked_at": str,
        "revoked_by": str,
    },
)

RevocationEvent = TypedDict(
    "RevocationEvent",
    {
        "action": str,
        "at": str,
        "by": str,
        "reason": str,
    },
)

Stage = Literal["RECEIVED", "VALIDATED", "BUILT", "FORMAL_CHECKED", "CONFORMANCE_CHECKED", "BENCHMARKED", "DECIDED"]

TrustedBaseEntry = TypedDict(
    "TrustedBaseEntry",
    {
        "digest": NotRequired[Optional[Digest]],
        "id": str,
        "label": str,
    },
)

# The digests that define the *verified* surface. If all are equal between a child and its parent, formal results may be reused (`ProverOnly`).
VerifiedSurface = TypedDict(
    "VerifiedSurface",
    {
        "certificate_decl": str,
        "challenge_id": str,
        "checker_image": Digest,
        "formal_tree": Digest,
        "prepare_artifact": Digest,
        "public_artifacts": Digest,
        "verifier_bytecode": NotRequired[Optional[Digest]],
        "verifier_model": NotRequired[Optional[str]],
        "verifier_model_module": NotRequired[Optional[str]],
        "verify_artifact": Digest,
        "verify_route": NotRequired[Optional[VerifyRoute]],
    },
)

# Public view of a submission (API `GET /v1/submissions/{id}`).
SubmissionView = TypedDict(
    "SubmissionView",
    {
        "accepted": NotRequired[Optional[bool]],
        "agent": str,
        "artifacts": NotRequired[List[ArtifactRef]],
        "assumptions": NotRequired[List[AssumptionRef]],
        "backend_family": str,
        "benchmark": NotRequired[Optional[BenchmarkResult]],
        "build": NotRequired[Optional[BuildInfo]],
        "candidate_name": str,
        "challenge_id": str,
        "change_class": NotRequired[Optional[ChangeClass]],
        "created_at": str,
        "decision": NotRequired[Optional[Decision]],
        "evidence_graph": NotRequired[Optional[EvidenceGraph]],
        "gates": List[GateResult],
        "id": str,
        "logs": NotRequired[List[LogExcerpt]],
        "package_digest": Digest,
        "parent": NotRequired[Optional[str]],
        "reason_codes": List[ReasonCode],
        "revocation_history": NotRequired[List[RevocationEvent]],
        "revoked": NotRequired[Optional[Revocation]],
        "score_milli": NotRequired[Optional[int]],
        "stage": Stage,
        "tier": Tier,
        "trusted_base": NotRequired[List[TrustedBaseEntry]],
        "updated_at": str,
        "verified_surface": NotRequired[Optional[VerifiedSurface]],
    },
)

__all__ = ["AdversaryClass", "ArtifactRef", "Assumption", "AssumptionRef", "BenchmarkResult", "BuildInfo", "BuildSection", "CandidateManifest", "ChallengeDefinition", "ChangeClass", "ClaimEncoding", "ClassMeasurement", "CostBaselineClass", "CostClass", "CostResult", "Decision", "Digest", "EdgeStatus", "EntrySection", "EvidenceEdge", "EvidenceGraph", "EvidenceNode", "EvidenceRef", "FormalParams", "FormalSection", "FormalSpecRef", "GateResult", "GateStatus", "HardwareProfile", "HardwareRequest", "InvocationMode", "LeaderboardEntry", "LogExcerpt", "MeasurementProcedure", "NearcorePin", "NodeKind", "ObligationId", "PriceModel", "PriceRationale", "Privacy", "ReasonCode", "ResourceLimits", "Restriction", "Revocation", "RevocationEvent", "ScopeKind", "ScoringKind", "ScoringSpec", "SecurityModel", "SecurityProfile", "SemanticScope", "SetupModel", "Stage", "SubmissionView", "Tier", "ToolchainPolicy", "TrustedBaseEntry", "VerifiedSurface", "VerifyRoute", "WorkloadClass", "WorkloadSuite"]
