#!/usr/bin/env node
// Generate src/types.ts from common/schemas/*.schema.json.
//   node scripts/gen-types.mjs          # write
//   node scripts/gen-types.mjs --check  # exit 1 if stale
// The schemas are generated from the Rust source of truth
// (`cargo run -p arena-types --bin gen-schemas`). Never edit types.ts by hand.
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemas = join(here, "..", "..", "..", "common", "schemas");
const out = join(here, "..", "src", "types.ts");

function loadDefinitions() {
  const defs = new Map();
  for (const f of readdirSync(schemas).filter((f) => f.endsWith(".schema.json")).sort()) {
    const root = JSON.parse(readFileSync(join(schemas, f), "utf8"));
    const items = { ...(root.definitions ?? {}) };
    const body = { ...root };
    delete body.definitions;
    delete body.$schema;
    items[root.title] = body;
    for (const [name, d0] of Object.entries(items)) {
      const d = { ...d0 };
      delete d.title;
      const prev = defs.get(name);
      if (prev && JSON.stringify(prev) !== JSON.stringify(d)) throw new Error(`conflicting ${name} in ${f}`);
      defs.set(name, d);
    }
  }
  return defs;
}

const refName = (r) => r.split("/").pop();

function enumValues(s) {
  if (s.enum) return s.enum;
  if (s.oneOf && s.oneOf.every((v) => v.enum)) return s.oneOf.flatMap((v) => v.enum);
  return null;
}

function tsType(s) {
  if (s.$ref) return refName(s.$ref);
  if (s.allOf && s.allOf.length === 1) return tsType(s.allOf[0]);
  const ev = enumValues(s);
  if (ev) return ev.map((v) => JSON.stringify(v)).join(" | ");
  if (s.anyOf) return s.anyOf.map(tsType).join(" | ");
  const t = s.type;
  if (Array.isArray(t)) return t.map((x) => tsType({ ...s, type: x })).join(" | ");
  switch (t) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    case "array":
      if (Array.isArray(s.items)) return `[${s.items.map(tsType).join(", ")}]`;
      { const inner = tsType(s.items ?? {}); return /[ |]/.test(inner) ? `Array<${inner}>` : `${inner}[]`; }
    case "object": return "Record<string, unknown>";
    default: return "unknown";
  }
}

function doc(s, indent = "") {
  const d = (s.description ?? "").trim();
  if (!d) return "";
  return `${indent}/** ${d.split("\n").join(`\n${indent} * `)} */\n`;
}

function render(defs) {
  const lines = [
    "// Generated by sdk/typescript/scripts/gen-types.mjs from common/schemas/*.schema.json.",
    "// DO NOT EDIT. Regenerate after `cargo run -p arena-types --bin gen-schemas`.",
    "// Integers (ns, bytes, ppm, milli-scores) are JSON numbers; all fit in 2^53.",
    "",
  ];
  for (const name of [...defs.keys()].sort()) {
    const s = defs.get(name);
    let block = doc(s);
    if (s.type === "object" && s.properties) {
      const req = new Set(s.required ?? []);
      block += `export interface ${name} {\n`;
      for (const [k, v] of Object.entries(s.properties)) {
        block += doc(v, "  ");
        block += `  ${k}${req.has(k) ? "" : "?"}: ${tsType(v)};\n`;
      }
      block += "}\n";
    } else {
      block += `export type ${name} = ${tsType(s)};\n`;
    }
    lines.push(block);
  }
  return lines.join("\n");
}

const text = render(loadDefinitions());
if (process.argv.includes("--check")) {
  if (!existsSync(out) || readFileSync(out, "utf8") !== text) {
    console.error(`${out} is stale; run node scripts/gen-types.mjs`);
    process.exit(1);
  }
} else {
  writeFileSync(out, text);
  console.log(`wrote ${out}`);
}
