use crate::impact::Impact;
use crate::protocol::ProtocolDiff;
use serde::Serialize;
use std::collections::BTreeMap;
use std::fmt::Write;

#[derive(Debug, Serialize)]
pub struct Report {
    pub schema: String,
    pub tool: String,
    /// `REVALIDATION_REQUIRED` | `NO_SEMANTIC_CHANGE_DETECTED`.
    pub verdict: String,
    pub reasons: Vec<String>,
    pub old: RefInfo,
    pub new: RefInfo,
    pub roots: Vec<String>,
    pub closure: ClosureInfo,
    pub changed_files_total: usize,
    pub changed_files_outside_closure: usize,
    pub changed_in_closure: Vec<ClosureChange>,
    pub workspace_build_config_changes: Vec<String>,
    pub external_crate_changes: Vec<ExternalChange>,
    pub parameters: ParamInfo,
    pub protocol: ProtocolDiff,
    pub version_gate_changes: BTreeMap<String, GateRefs>,
    pub migrations: Vec<String>,
    pub impact: Impact,
}

impl Report {
    pub fn revalidation_required(&self) -> bool {
        self.verdict != "NO_SEMANTIC_CHANGE_DETECTED"
    }
}

#[derive(Debug, Serialize)]
pub struct RefInfo {
    pub r#ref: String,
    pub commit: String,
    pub stable_protocol_version: Option<u32>,
}

#[derive(Debug, Serialize)]
pub struct CrateInfo {
    pub name: String,
    pub dir: String,
    pub changed_files: usize,
}

#[derive(Debug, Serialize)]
pub struct ClosureInfo {
    pub crates: Vec<CrateInfo>,
    pub added: Vec<String>,
    pub removed: Vec<String>,
    pub include_targets_outside_crates: Vec<String>,
    pub external_crates_old: usize,
    pub external_crates_new: usize,
}

#[derive(Debug, Serialize)]
pub struct ClosureChange {
    pub path: String,
    pub old_path: Option<String>,
    pub status: String,
    pub crate_name: String,
}

#[derive(Debug, Serialize)]
pub struct ExternalChange {
    pub name: String,
    pub old_versions: Vec<String>,
    pub new_versions: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct ParamInfo {
    pub changed_files: Vec<String>,
    pub diff_excerpt: String,
}

#[derive(Debug, Default, Serialize)]
pub struct GateRefs {
    pub added_refs: usize,
    pub removed_refs: usize,
    pub files: Vec<String>,
}

pub fn markdown(r: &Report) -> String {
    let mut m = String::new();
    let _ = writeln!(
        m,
        "# nearcore upgrade impact: `{}` → `{}`\n",
        r.old.r#ref, r.new.r#ref
    );
    let _ = writeln!(m, "**Verdict: `{}`**\n", r.verdict);
    let _ = writeln!(
        m,
        "Generated by `{}` (schema `{}`). A passing old Lean proof does **not** \
         override this verdict: any change in the closure reopens the listed obligations.\n",
        r.tool, r.schema
    );
    let _ = writeln!(m, "| | ref | commit | STABLE_PROTOCOL_VERSION |\n|-|-|-|-|");
    for (l, x) in [("old", &r.old), ("new", &r.new)] {
        let _ = writeln!(
            m,
            "| {l} | `{}` | `{}` | {} |",
            x.r#ref,
            x.commit,
            opt(x.stable_protocol_version)
        );
    }
    let _ = writeln!(m, "\n## Reasons\n");
    if r.reasons.is_empty() {
        let _ = writeln!(m, "_none_");
    }
    for x in &r.reasons {
        let _ = writeln!(m, "* {x}");
    }

    let _ = writeln!(m, "\n## Semantic closure\n");
    let _ = writeln!(
        m,
        "Roots: {}\n",
        r.roots
            .iter()
            .map(|x| format!("`{x}`"))
            .collect::<Vec<_>>()
            .join(", ")
    );
    let _ = writeln!(
        m,
        "{} workspace crates (normal + build + optional deps; dev-deps excluded); {} → {} external crate versions.\n",
        r.closure.crates.len(),
        r.closure.external_crates_old,
        r.closure.external_crates_new
    );
    let _ = writeln!(m, "| crate | dir | changed files |\n|-|-|-|");
    for c in &r.closure.crates {
        let _ = writeln!(m, "| `{}` | `{}` | {} |", c.name, c.dir, c.changed_files);
    }
    if !r.closure.added.is_empty() || !r.closure.removed.is_empty() {
        let _ = writeln!(
            m,
            "\nAdded to closure: {:?}; removed: {:?}",
            r.closure.added, r.closure.removed
        );
    }
    if !r.closure.include_targets_outside_crates.is_empty() {
        let _ = writeln!(
            m,
            "\n`include_*!` targets outside crate dirs (tracked): {:?}",
            r.closure.include_targets_outside_crates
        );
    }

    let _ = writeln!(
        m,
        "\n## Changed files\n\n{} changed in total; {} inside the closure; {} outside.\n",
        r.changed_files_total,
        r.changed_in_closure.len(),
        r.changed_files_outside_closure
    );
    if !r.changed_in_closure.is_empty() {
        let _ = writeln!(m, "| status | path | crate |\n|-|-|-|");
        for c in &r.changed_in_closure {
            let _ = writeln!(m, "| {} | `{}` | `{}` |", c.status, c.path, c.crate_name);
        }
    }
    if !r.workspace_build_config_changes.is_empty() {
        let _ = writeln!(
            m,
            "\nWorkspace build configuration: {:?}",
            r.workspace_build_config_changes
        );
    }

    let _ = writeln!(m, "\n## External crates in closure\n");
    if r.external_crate_changes.is_empty() {
        let _ = writeln!(m, "_no version changes_");
    } else {
        let _ = writeln!(m, "| crate | old | new |\n|-|-|-|");
        for e in &r.external_crate_changes {
            let _ = writeln!(
                m,
                "| `{}` | {} | {} |",
                e.name,
                e.old_versions.join(", "),
                e.new_versions.join(", ")
            );
        }
    }

    let _ = writeln!(
        m,
        "\n## Runtime parameters (`core/parameters/res/runtime_configs`)\n"
    );
    if r.parameters.changed_files.is_empty() {
        let _ = writeln!(m, "_unchanged_");
    } else {
        for f in &r.parameters.changed_files {
            let _ = writeln!(m, "* `{f}`");
        }
        let _ = writeln!(m, "\n```diff\n{}```", r.parameters.diff_excerpt);
    }

    let p = &r.protocol;
    let _ = writeln!(m, "\n## Protocol versions and features\n");
    if p.is_empty() {
        let _ = writeln!(m, "_no changes_");
    }
    for (k, (a, b)) in &p.constants_changed {
        let _ = writeln!(
            m,
            "* `{k}`: `{}` → `{}`",
            a.as_deref().unwrap_or("∅"),
            b.as_deref().unwrap_or("∅")
        );
    }
    for (k, v) in &p.features_added {
        let _ = writeln!(m, "* new feature `{k}` @ {}", opt(*v));
    }
    for (k, v) in &p.features_removed {
        let _ = writeln!(m, "* removed feature `{k}` (was @ {})", opt(*v));
    }
    for (k, (a, b)) in &p.features_version_changed {
        let _ = writeln!(m, "* feature `{k}` version {} → {}", opt(*a), opt(*b));
    }
    if !p.features_deprecated.is_empty() {
        let _ = writeln!(
            m,
            "* renamed to `_Deprecated*` (already-stable gates removed from code): {}",
            p.features_deprecated
                .iter()
                .map(|x| format!("`{x}`"))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    if !p.newly_stable_features.is_empty() {
        let _ = writeln!(
            m,
            "* newly enabled at stable: {}",
            p.newly_stable_features
                .iter()
                .map(|x| format!("`{x}`"))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    for (k, (a, b)) in &p.db_constants_changed {
        let _ = writeln!(
            m,
            "* DB `{k}`: `{}` → `{}`",
            a.as_deref().unwrap_or("∅"),
            b.as_deref().unwrap_or("∅")
        );
    }
    for e in &p.parse_errors {
        let _ = writeln!(m, "* PARSE ISSUE: {e}");
    }

    let _ = writeln!(
        m,
        "\n## Version-gate references in changed closure sources\n"
    );
    if r.version_gate_changes.is_empty() {
        let _ = writeln!(m, "_none_");
    } else {
        let _ = writeln!(m, "| feature | +refs | -refs | files |\n|-|-|-|-|");
        for (k, g) in &r.version_gate_changes {
            let _ = writeln!(
                m,
                "| `{k}` | {} | {} | {} |",
                g.added_refs,
                g.removed_refs,
                g.files.len()
            );
        }
    }

    let _ = writeln!(m, "\n## Migrations\n");
    if r.migrations.is_empty() {
        let _ = writeln!(m, "_none touched_");
    }
    for x in &r.migrations {
        let _ = writeln!(m, "* `{x}`");
    }

    let i = &r.impact;
    let _ = writeln!(
        m,
        "\n## Impact on the arena spec (`spec/impact-map.toml`)\n"
    );
    let _ = writeln!(
        m,
        "Obligations to reopen: {}\n",
        list(&i.obligations_to_reopen.iter().map(obl).collect::<Vec<_>>())
    );
    let _ = writeln!(
        m,
        "Spec definitions to revalidate: {}\n",
        list(&i.spec_definitions_to_revalidate)
    );
    let _ = writeln!(
        m,
        "Fixtures to regenerate: {}\n",
        list(&i.fixtures_to_regenerate)
    );
    if !i.rule_hits.is_empty() {
        let _ = writeln!(m, "| rule | files | obligations |\n|-|-|-|");
        for h in &i.rule_hits {
            let _ = writeln!(
                m,
                "| `{}` | {} | {} |",
                h.rule,
                h.files.len(),
                h.obligations.iter().map(obl).collect::<Vec<_>>().join(", ")
            );
        }
    }
    if !i.unmapped_files.is_empty() {
        let _ = writeln!(m, "\n{} changed input(s) matched no rule; the `[default]` target (fail-closed) applies:\n", i.unmapped_files.len());
        for f in &i.unmapped_files {
            let _ = writeln!(m, "* `{f}`");
        }
    }
    m
}

fn opt(v: Option<u32>) -> String {
    v.map(|x| x.to_string()).unwrap_or_else(|| "?".into())
}

fn list(v: &[String]) -> String {
    if v.is_empty() {
        "_none_".into()
    } else {
        v.iter()
            .map(|x| format!("`{x}`"))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn obl(o: &arena_types::ObligationId) -> String {
    serde_json::to_value(o)
        .ok()
        .and_then(|v| v.as_str().map(str::to_string))
        .unwrap_or_else(|| format!("{o:?}"))
}
