import ArenaExpectedInst
import ReexecV3D2.Obligations
import ReexecV3D2.PublicBin

/-!
# The certificate

Its type, `ArenaExpectedInst.expectedType`, is generated by the judge
(native-lean route): `ArenaExpected.expectedTypeFor ReexecV3D2.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest
toolchainId ReexecV3D2.Model.verifier }` with `params =
{ spec := NearSpecV3.challengeSpecD2, … }` (challenge `near-chunk-validation-d2`,
`spec/lean/judge/ExpectedV3D2.native-lean.lean.template`). Every literal in it
(profile, fuel, `maxProofBytes`, digests, toolchain id) is fixed by the judge;
the proof below works for any of them except `maxProofBytes < 8 388 641` and a
public digest other than `sha256 publicBin`.
-/

namespace ReexecV3D2

theorem certificate : ArenaExpectedInst.expectedType :=
  admission _ _ _ _ (by decide) publicBin _ _ _ (by decide +kernel)

end ReexecV3D2
