# Generates ZkFormal/NearV3/Extract/Ups/KindHeads.lean (run from zk-formal/):
# per part kind (all but SPB), the part constants its first row fixes: the node type, xcp,
# vcp and the memory_usage formula (useA bN bL cO cS Cc eL eS Kc), from UpsV3.cPlan.
KINDS = ["RDB", "RDE", "RLP", "RBR", "RBV", "RBI", "MVL", "MVE", "NLF", "WEX", "SPB", "PT"]
KCOL = ["kRDB", "kRDE", "kRLP", "kRBR", "kRBV", "kRBI", "kMVL", "kMVE", "kNLF", "kWEX", "kSPB", "kPT"]

# (name, Lean Expr of the constraint, used for kinds)
CONS = [
 ("fx", ".mul (c pf) (sub (c xcp) (.mul (c kSPB) (.add (c cESl1) (c cESn1))))"),
 ("fv", ".mul (c pf) (sub (c vcp) (sum [c kRDB, c kRBI, c kMVL, .mul (c kSPB) (c cLSa)]))"),
 ("t1", ".mul (c pf) (.mul (sumc [kRDB, kRBR, kRBI]) (.add (c qtl) (c qte)))"),
 ("t2", ".mul (c pf) (.mul (.add (c kRBR) (c kRBV)) (not (c qtb2)))"),
 ("t3", ".mul (c pf) (.mul (sumc [kRDE, kMVE, kWEX, kPT]) (not (c qte)))"),
 ("t4", "mul3 (c pf) (c kPT) (not (c nokey))"),
 ("t5", "mul3 (c pf) (c kPT) (c qodd)"),
 ("t6", ".mul (c pf) (.mul (sumc [kRLP, kMVL, kNLF]) (not (c qtl)))"),
 ("t7", ".mul (c pf) (.mul (c nokey) (sub (c qhk) (k 1)))"),
 ("t8", ".mul (c pf) (.mul (c kNLF) (sub (c qhk) (k 1)))"),
 ("m1", ".mul (c pf) (sub (c useA) (sum [c kRDB, c kRDE, c kRBR, c kRBV, c kRBI, c kMVE, c xcp, c kPT]))"),
 ("m2", ".mul (c pf) (sub (c bN) (sum [c kRDB, c kRDE, c kWEX, .mul (c kSPB) spRecvE, c kPT]))"),
 ("m3", ".mul (c pf) (sub (c bL) (c kRBR))"),
 ("m4", ".mul (c pf) (sub (c cO) (.add kRD (c kPT)))"),
 ("m5", ".mul (c pf) (sub (c cS) (c kRBR))"),
 ("m6", ".mul (c pf) (sub (c Cc) (.mul (.add (c kMVE) (c xcp)) (.add (k 50) (smul 2 (c phk)))))"),
 ("m7", ".mul (c pf) (sub (c eL) (sum [c kRLP, c kRBV, c kRBI, c kNLF, c kSPB]))"),
 ("m8", ".mul (c pf) (sub (c eS) (.add (c kMVL) (.mul (c kSPB) (c cLSa))))"),
 ("m9", """.mul (c pf) (sub (c Kc) (sum [
      .mul (c kRLP) (.add (k 100) (smul 2 (c qhk))), smul 50 (c kRBV), smul 102 (c kRBI),
      .mul (c kMVL) (.add (k 100) (smul 2 (c qhk))), .mul (c kMVE) (.add (k 50) (smul 2 (c qhk))),
      smul 102 (c kNLF), .mul (c kWEX) (.add (k 50) (smul 2 (c qhk))),
      .mul (c kSPB) (sum [smul 202 (c cLSa), smul 100 (sumc [cLSb, cESl0, cESl1]),
        smul 152 (sumc [cLSc, cESn0, cESn1])])]))"""),
]

def concl(ki):
    k = KINDS[ki]
    f = ["C xcp = 0"]
    f.append("C vcp = %d" % (1 if k in ("RDB", "RBI", "MVL") else 0))
    if k in ("RLP", "MVL", "NLF"): f.append("C qtl = 1")
    if k in ("RDB", "RBR", "RBI"): f += ["C qtl = 0", "C qte = 0"]
    if k in ("RBR", "RBV"): f.append("C qtb2 = 1")
    if k in ("RDE", "MVE", "WEX", "PT"): f.append("C qte = 1")
    if k == "PT": f += ["C nokey = 1", "C qodd = 0", "C qhk = 1"]
    if k == "NLF": f.append("C qhk = 1")
    useA = 1 if k in ("RDB", "RDE", "RBR", "RBV", "RBI", "MVE", "PT") else 0
    bN = 1 if k in ("RDB", "RDE", "WEX", "PT") else 0
    bL = 1 if k == "RBR" else 0
    cO = 1 if k in ("RDB", "RDE", "PT") else 0
    cS = 1 if k == "RBR" else 0
    eL = 1 if k in ("RLP", "RBV", "RBI", "NLF") else 0
    eS = 1 if k == "MVL" else 0
    f += ["C useA = %d" % useA, "C bN = %d" % bN, "C bL = %d" % bL, "C cO = %d" % cO, "C cS = %d" % cS]
    f.append("(C phk < 2 ^ 20 → C Cc = 50 + 2 * C phk)" if k == "MVE" else "C Cc = 0")
    f += ["C eL = %d" % eL, "C eS = %d" % eS]
    Kc = {"RLP": "100 + 2 * C qhk", "RBV": "50", "RBI": "102", "MVL": "100 + 2 * C qhk", "MVE": "50 + 2 * C qhk",
          "NLF": "102", "WEX": "50 + 2 * C qhk"}.get(k, "0")
    f.append("(C qhk < 2 ^ 20 → C Kc = " + Kc + ")" if "qhk" in Kc else "C Kc = " + Kc)
    return f

out = []
out.append('''import ZkFormal.NearV3.Extract.Ups.PlanRows

/-!
# ZkFormal.NearV3.Extract.Ups.KindHeads — part constants fixed by the kind (generated)

Generated by `test/gen_ups_heads.py` (run from `zk-formal/`) from `UpsV3.cPlan`: on a part's
first row (`pf = 1`) of kind `K` (all kinds but `SPB`, whose constants depend on the case),
`head_K` gives `xcp`, `vcp`, the node type and the `memory_usage` formula
(`R = E + max(0, A + B − C)`: `useA bN bL cO cS Cc eL eS Kc`).
-/

namespace ZkFormal.NearV3.UpsRows

open ZkFormal.Air ZkFormal.Algebra ZkFormal.Near ZkFormal.Near.Dsl ZkFormal.NearV3.UpsV3

section
variable {C D : URow} (ok : URowOk C D) (hC : ∀ x, C x < P) (hD : ∀ x, D x < P)
include ok hC hD
''')
for ki, k in enumerate(KINDS):
    if k == "SPB": continue
    cs = concl(ki)
    out.append(f"theorem head_{k} (hpf : C pf = 1) (hk : ∀ m, m < 12 → C (kcol m) = if m = {ki} then 1 else 0) :")
    out.append("    " + " ∧\n    ".join(cs) + " := by")
    for m in range(12):
        out.append(f"  have k{m} : C {KCOL[m]} = {1 if m == ki else 0} := hk {m} (by omega)")
    out.append("  have a := fun x => hC x")
    out.append("  simp only [P_lit] at a")
    cols = ["xcp", "vcp", "qtl", "qte", "qtb2", "nokey", "qodd", "qhk", "useA", "bN", "bL", "cO", "cS", "Cc", "eL",
            "eS", "Kc", "phk", "cESl1", "cESn1", "cLSa"]
    out.append("  " + "; ".join(f"have := a {x}" for x in cols))
    out.append("  have := partBoolN ok hC hpf (x := qtl) (by decide); have := partBoolN ok hC hpf (x := qte) (by decide)")
    out.append("  have := partBoolN ok hC hpf (x := nokey) (by decide)")
    names = []
    out.append(f"  have hx0 : C xcp = 0 := by")
    out.append(f"    have fx := factN ok hC hD (e := {CONS[0][1]}) (memPlan (by simp [cPlan]))")
    out.append(f"    nev_simp at fx; simp only [hpf, k10] at fx; simp at fx; omega")
    for (n, e) in CONS[1:]:
        out.append(f"  have {n} := factN ok hC hD (e := {e}) (memPlan (by simp [cPlan]))")
        names.append(n)
    ns = " ".join(names)
    out.append(f"  simp only [sumc, List.map_cons, List.map_nil, kRD, spRecvE] at {ns}")
    out.append(f"  nev_simp at {ns}")
    out.append(f"  simp only [hpf, hx0, " + ", ".join(f"k{m}" for m in range(12)) + f"] at {ns}")
    out.append(f"  simp at {ns}")
    if k == "PT":
        out.append("  have hnk : C nokey = 1 := by omega")
        out.append("  rw [hnk] at t7; simp at t7")
    out.append("  refine ⟨hx0, ?_⟩")
    out.append("  omega")
    out.append("")
out.append("end\n\nend ZkFormal.NearV3.UpsRows\n")
open("ZkFormal/NearV3/Extract/Ups/KindHeads.lean", "w").write("\n".join(out))
