#!/usr/bin/env python3
"""Model check of the rcptV3 table (zk-formal/ZkFormal/NearV3/Rcpt/Tables/Rcpt*.lean).

Usage: lake env lean --run test/RcptExport.lean > rcpt_air.txt
       python3 test/rcptv3_model.py rcpt_air.txt [seed] [instances]

For random D0-shaped batches (applied source lists, named receivers inside the own routing
interval, system receipts incl. gas refunds with signer = receiver and present / absent
access keys, refunds, empty lists, repeated accounts) the honest trace is generated by the
design rules (v1's closed-form generator `Near/Render/Rcpt.lean` plus the v3 deltas), then:
  * every exported constraint is 0 on every row (field P), and every multiplicity is 0/1;
  * BYTES: per id the emitted positions are exactly 0..len-1 (body: 8..|B|-1) and the bytes
    are RC(j) = u64 own ‖ u32 n_j ‖ Σ borsh(receipt), PEO(r), LEAF(r), RID(r), and the body
    B[8..] = Σ borsh(refund);
  * DIGEST receives are sha256 of the emitted bytes with the emitted length;
  * KEYNIB: per walk, exactly the key nibbles ([0]‖receiver, [2]‖signer‖[2]‖pk) and END;
  * FINAL, RCL, RIDS, MPOS as expected; SREC balances inside the table; MEM balances with
    simulated acctV3 open/close messages; AKC with simulated akeyV3, BND with simulated bndV3.
The receipt semantics follow NearSpecV3.applyReceipts (applyReceipt / applySystemReceipt).
"""
import hashlib, random, sys, re
from collections import Counter, defaultdict

P = 2013265921
END = 16
W_AK = 8192
STRIDE = 65
K_RC, K_RF, K_PEO, K_LEAF, K_RID = 1, 2, 3, 4, 5
G_LE = [196, 164, 183, 246, 51, 0, 0, 0]
G = sum(x << (8 * i) for i, x in enumerate(G_LE))
S_PER_BYTE = 10 ** 19
ZERO_LIMIT = 770
TWO128 = 1 << 128
SYSTEM = list(b"system")
PH_N, PH_OWN, PH_HEIGHT, PH_GP, PH_BURNT, PH_BLEN = 30, 34, 50, 58, 178, 194

def sha(b): return list(hashlib.sha256(bytes(b)).digest())
def leN(w, x): return [(x >> (8 * i)) & 255 for i in range(w)]
def u32(x): return leN(4, x)
def u64(x): return leN(8, x)
def u128(x): return leN(16, x)
def borsh(s): return u32(len(s)) + list(s)
def inv(x): x %= P; return pow(x, P - 2, P) if x else 0
def mid(kind, idx): return kind + 16 * idx

# ---------------------------------------------------------------- AIR export
AIR = sys.argv[1] if len(sys.argv) > 1 else 'rcpt_air.txt'
def parse(s):
    toks = s.replace('(', ' ( ').replace(')', ' ) ').split()
    def go(i):
        assert toks[i] == '('
        op = toks[i + 1]; i += 2; args = []
        while toks[i] != ')':
            if toks[i] == '(':
                a, i = go(i); args.append(a)
            else:
                args.append(int(toks[i])); i += 1
        return (op, args), i + 1
    out = []; i = 0
    while i < len(toks):
        e, i = go(i); out.append(e)
    return out
CONS, INTS, WIDTH = [], [], 0
for line in open(AIR):
    line = line.strip()
    if line.startswith('W '): WIDTH = int(line[2:])
    elif line.startswith('C '): CONS.append(parse(line[2:])[0])
    elif line.startswith('I '):
        hd = line.split(' ', 3)
        es = parse(hd[3])
        INTS.append((int(hd[1]), hd[2] == '1', es[0], es[1:]))

def ev(e, rows, q, pub, H):
    op, a = e
    if op == 'k': return a[0] % P
    if op == 'c':
        rr = (q + a[1]) % H
        return rows[rr][a[0]] % P
    if op == 'p': return pub[a[0]] % P if a[0] < len(pub) else 0
    if op == 'F': return 1 if q == 0 else 0
    if op == 'L': return 1 if q == H - 1 else 0
    if op == 'T': return 0 if q == H - 1 else 1
    if op == '+': return (ev(a[0], rows, q, pub, H) + ev(a[1], rows, q, pub, H)) % P
    if op == '*':
        x = ev(a[0], rows, q, pub, H)
        return 0 if x == 0 else (x * ev(a[1], rows, q, pub, H)) % P
    if op == '-': return (-ev(a[0], rows, q, pub, H)) % P
    raise Exception(op)

# emission-slot definitions from the constraints `s·(col − E)` (cols 31..42)
EMIT = defaultdict(dict)
for e in CONS:
    if e[0] == '*' and e[1][0][0] == 'c' and e[1][0][1][1] == 0:
        s = e[1][0][1][0]
        rhs = e[1][1]
        if rhs[0] == '+' and rhs[1][0][0] == 'c' and rhs[1][1][0] == '-' and 31 <= rhs[1][0][1][0] <= 42 \
                and rhs[1][0][1][1] == 0 and 4 <= s <= 26:
            EMIT[s][rhs[1][0][1][0]] = rhs[1][1][1][0]

# ---------------------------------------------------------------- layout
L = {}
for line in open('ZkFormal/NearV3/Rcpt/Tables/Rcpt/Layout.lean'):
    m = re.match(r'def (\w+) : Nat := (\d+)$', line.strip())
    if m: L[m.group(1)] = int(m.group(2))
def reg(i): return 63 + i
def tok(i): return 95 + i
def lb(i): return 116 + i
def xb(i): return 138 + i
def dl(i): return 208 + i
S = dict(sCL=4, sPL=5, sP=6, sVL=7, sV=8, sRID=9, sT0=10, sSL=11, sS=12, sKT=13, sPK=14, sGP=15,
         sTL=16, sDEP=17, sXP0=18, sXRI=19, sXG=20, sXST=21, sXL0=22, sXLH=23, sXRH=24, sXRF=25, sXRZ=26)
for k, v in S.items(): assert L[k] == v, k

def b2n(x): return 1 if x else 0
def bit(x, j): return (x >> j) & 1
def chain(x, i):
    c = 0
    for k in range(i): c = (x(k) + c) // 256
    return c
def bchain(a, b, b0, i):
    br = b0
    for k in range(i): br = 1 if a(k) < b(k) + br else 0
    return br
def bdig(a, b, b0, i): return a(i) + 256 * bchain(a, b, b0, i + 1) - b(i) - bchain(a, b, b0, i)
def conv(g, v, i): return sum(g[j] * v(i - j) for j in range(len(g)) if j <= i)
def runSum(x, i): return sum(x(j) for j in range(i + 1))
def sqd(a, b): return (a - b) * (a - b)
def isHex(ch): return (48 <= ch <= 57) or (97 <= ch <= 102)

def charCell(ch, col):
    hi, lo = ch // 16, ch % 16
    return {111: b2n(hi == 2), 112: b2n(hi == 3), 113: b2n(hi == 5), 114: b2n(hi == 6), 115: b2n(hi == 7),
            116: bit(lo, 0), 117: bit(lo, 1), 118: bit(lo, 2), 119: bit(lo, 3), 120: b2n(lo == 0),
            121: inv(lo), 122: b2n(lo % 8 == 7), 123: b2n(hi == 6 and 1 <= lo <= 6)}.get(col, 0)

# ---------------------------------------------------------------- semantics
def enc(rc):
    return (borsh(rc['pred']) + borsh(rc['recv']) + rc['rid'] + [0] + borsh(rc['signer']) + [rc['kt']] +
            rc['pk'] + u128(rc['gp']) + u32(0) + u32(0) + u32(1) + [3] + u128(rc['dep']))

def refund(rc, height, surplus):
    rid2 = sha(rc['rid'] + u64(height) + u64(0))
    return dict(pred=SYSTEM, recv=rc['signer'], rid=rid2, signer=rc['signer'], kt=rc['kt'], pk=rc['pk'],
                gp=0, dep=surplus)

ALPH = b'abcdefghijklmnopqrstuvwxyz0123456789'
def randName(rng):
    while True:
        n = rng.randint(2, 12)
        s = bytes(rng.choice(ALPH) for _ in range(n))
        if rng.random() < 0.3: s = s[:n // 2] + b'.' + s[n // 2 + 1:] if n >= 4 else s
        if rng.random() < 0.2: s = s[:n // 2] + b'_' + s[n // 2 + 1:] if n >= 4 else s
        if s[0:1] in b'._-' or s[-1:] in b'._-': continue
        ok = all(not (s[i] in b'._-' and s[i + 1] in b'._-') for i in range(len(s) - 1))
        if ok and len(s) >= 2 and s != b'system': return list(s)
def validId(s):
    return 2 <= len(s) <= 64 and s[0] not in b'._-' and s[-1] not in b'._-' and \
        all(not (s[i] in b'._-' and s[i + 1] in b'._-') for i in range(len(s) - 1))
def lexLe(a, b): return bytes(a) <= bytes(b)

def gen(rng):
    own = rng.randint(0, 2 ** 64 - 1)
    height = rng.randint(1, 2 ** 40)
    bgp = rng.choice([100000000, rng.randint(1, 2 ** 40)])
    # own interval [lo, hi)
    lo = randName(rng) if rng.random() < 0.6 else None
    hi = randName(rng) if rng.random() < 0.6 else None
    if lo and hi and not lexLe(lo, hi): lo, hi = hi, lo
    if lo and hi and lo == hi: hi = None
    if rng.random() < 0.3 and lo:  # a prefix boundary
        hi = lo + list(b'zz')
    def inside(a):
        return (lo is None or lexLe(lo, a)) and (hi is None or not lexLe(hi, a))
    pool = []
    tries = 0
    while len(pool) < rng.randint(1, 5) and tries < 2000:
        tries += 1
        a = randName(rng)
        if rng.random() < 0.3 and lo: a = lo[:] if rng.random() < 0.5 else lo + list(b'a')
        if rng.random() < 0.1 and hi: a = hi[:-1] if len(hi) > 2 else hi
        if inside(a) and a not in pool and a != SYSTEM and len(a) >= 2 and all(c in ALPH + b'._-' for c in a) \
                and a[0] not in b'._-' and a[-1] not in b'._-':
            pool.append(a)
    if not pool: return None
    accts = {}
    vid = 1
    for a in pool:
        accts[bytes(a)] = dict(vid=vid, amt=rng.randint(10 ** 24, 10 ** 26), locked=rng.choice([0, 10 ** 24]),
                               stor=rng.choice([100, 182, 770, 1000]))
        vid += 1
    akeys = {}
    lists = []
    r = 0
    nl = rng.randint(1, 4)
    for j in range(nl):
        rs = []
        for _ in range(rng.choice([0, 0, 1, 2, 3])):
            recv = rng.choice(pool)
            sysr = rng.random() < 0.35
            kt = rng.randint(0, 1)
            pk = [rng.randint(0, 255) for _ in range(32 + 32 * kt)]
            if sysr:
                signer = recv[:] if rng.random() < 0.5 else (randName(rng) if rng.random() < 0.5
                                                              else recv[:-1] if len(recv) > 2 else recv + [97])
                if rng.random() < 0.2 and len(recv) > 2:  # same length, one byte different
                    signer = recv[:]; signer[rng.randrange(len(signer))] = 97 if signer[0] != 97 else 98
                    if signer[0] in b'._-' or signer[-1] in b'._-': signer = recv[:]
                if not validId(signer): signer = recv[:]
                gp = rng.choice([0, bgp, bgp * 2])
                pred = SYSTEM
            else:
                signer = randName(rng)
                pred = randName(rng)
                gp = rng.choice([bgp, bgp + rng.randint(1, 10 ** 6), max(1, bgp - 1), bgp * 3])
            rc = dict(pred=pred, recv=recv, rid=[rng.randint(0, 255) for _ in range(32)], signer=signer, kt=kt, pk=pk,
                      gp=gp, dep=rng.randint(0, 10 ** 24), sys=sysr)
            if sysr and signer == recv:
                key = (bytes(recv), bytes([kt] + pk))
                if key not in akeys:
                    if rng.random() < 0.5: akeys[key] = None
                    else:
                        akeys[key] = dict(vid=vid, val=u64(rng.randint(0, 2 ** 64 - 1)) + [1]); vid += 1
            rs.append(rc)
        lists.append(rs)
    return dict(own=own, height=height, bgp=bgp, lo=lo, hi=hi, accts=accts, akeys=akeys, lists=lists)

# ---------------------------------------------------------------- honest trace
def build(inst, rng):
    own, height, bgp = inst['own'], inst['height'], inst['bgp']
    bgpB = u128(bgp)
    lo, hi = inst['lo'], inst['hi']
    lob = (lo or []) + [0] * (STRIDE - len(lo or []))
    hib = (hi or []) + [0] * (STRIDE - len(hi or []))
    hn = 1 if hi is None else 0
    q = rng.randint(0, 3)
    state = {k: dict(v) for k, v in inst['accts'].items()}
    last_write = {}
    rows = []
    expBytes = defaultdict(dict)   # id -> pos -> byte
    expDig = {}
    expKey = defaultdict(list)
    expFinal = Counter()
    expRcl = Counter()
    refunds = []
    bnd_use = Counter()
    ak_use = Counter()
    tok_total = 0
    outcomes = []
    r = 0
    o2 = 8
    allrc = []
    nlists = len(inst['lists'])
    for j, rs in enumerate(inst['lists']):
        nj = len(rs)
        rcbytes = u64(own) + u32(nj)
        for k2, x in enumerate(rcbytes): expBytes[mid(K_RC, j)][k2] = x
        # header rows
        hdr_regs = u64(own) + [nj & 255, nj >> 8, 0, 0]
        for i in range(12):
            row = [0] * WIDTH
            row[0] = 1; row[4] = 1; row[27] = i; row[28] = b2n(i == 0); row[29] = b2n(i == 11)
            for t in range(32): row[reg(t)] = hdr_regs[i + t] if i + t < 12 else 0
            row[L['r']] = r; row[L['o2']] = o2; row[L['o2End']] = o2; row[L['oEnd']] = 12; row[L['cj']] = 0
            row[L['j']] = j; row[L['nj']] = nj
            for t in range(16): row[tok(t)] = u128(tok_total)[t]
            rows.append(row)
        o = 12
        for cjx, rc in enumerate(rs, start=1):
            recv = rc['recv']; acct = state[bytes(recv)]
            sysr = rc['sys']
            ee = sysr and rc['signer'] == recv
            Lp, Lv, Ls, kt = len(rc['pred']), len(recv), len(rc['signer']), rc['kt']
            bef, locked, stor = acct['amt'], acct['locked'], acct['stor']
            aft = bef + rc['dep']
            assert aft < 2 ** 128 - 1 and aft + locked < TWO128
            assert aft + locked >= S_PER_BYTE * stor or stor <= ZERO_LIMIT
            big = S_PER_BYTE * stor <= aft + locked
            ge = rc['gp'] >= bgp
            p = 0 if sysr else min(rc['gp'], bgp)
            burnt = G * p
            surplus = G * (rc['gp'] - min(rc['gp'], bgp))
            hr = (not sysr) and surplus != 0
            ramt = surplus
            tok0 = tok_total
            tok_total += burnt
            assert tok_total < TWO128
            kslot = acct['vid']
            tprev = last_write.get(kslot, 0)
            last_write[kslot] = r + 1
            acct['amt'] = aft
            # refund
            rf = refund(rc, height, surplus) if hr else None
            refundId = rf['rid'] if hr else []
            peo = u32(b2n(hr)) + refundId + u64(G) + u128(burnt) + borsh(recv) + [2, 0, 0, 0, 0]
            peoDig = sha(peo)
            leaf = [2, 0, 0, 0] + rc['rid'] + peoDig
            # expectations
            e = enc(rc)
            for k2, x in enumerate(e): expBytes[mid(K_RC, j)][o + k2] = x
            for k2, x in enumerate(peo): expBytes[mid(K_PEO, r)][k2] = x
            for k2, x in enumerate(leaf): expBytes[mid(K_LEAF, r)][k2] = x
            if hr:
                ridb = rc['rid'] + u64(height) + u64(0)
                for k2, x in enumerate(ridb): expBytes[mid(K_RID, r)][k2] = x
                fb = enc(rf)
                for k2, x in enumerate(fb): expBytes[K_RF][o2 + k2] = x
                refunds.append(fb)
            keyA = [0, 0] + sum(([c // 16, c % 16] for c in recv), []) + [END]
            for t, s in enumerate(keyA): expKey[r].append((t, s, b2n(t + 1 == len(keyA))))
            expFinal[(r, 0, 0, kslot)] += 1
            ak = None
            if ee:
                kb = [2] + recv + [2] + [kt] + rc['pk']
                keyK = sum(([c // 16, c % 16] for c in kb), []) + [END]
                for t, s in enumerate(keyK): expKey[W_AK + r].append((t, s, b2n(t + 1 == len(keyK))))
                ak = inst['akeys'][(bytes(recv), bytes([kt] + rc['pk']))]
                expFinal[(W_AK + r, 0, 1 if ak is None else 0, 0 if ak is None else ak['vid'])] += 1
            oEnd = o + 123 + Lp + Lv + Ls + 32 * kt
            o2End = o2 + (129 + 2 * Ls + 32 * kt if hr else 0)
            # signer = receiver test data
            dm = dd = 0; dpos = -1
            if sysr and not ee:
                if Ls != Lv: dm = 0
                else:
                    dm = 1; dd = 1
                    dpos = next(i for i in range(Ls) if rc['signer'][i] != recv[i])
            # routing (per position i ≤ Lv)
            eqLs, eqHs = [1], [1 - hn]
            vbs = recv + [0]
            for i in range(Lv):
                eqLs.append(eqLs[-1] * b2n(vbs[i] == lob[i]))
                eqHs.append(eqHs[-1] * b2n(vbs[i] == hib[i]))
            # fields
            flds = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18] + ([19] if hr else []) + [20, 21, 22, 23] + \
                   ([24, 25, 26] if hr else [])
            def fLen(s):
                return {5: 4, 6: Lp, 7: 4, 8: Lv, 9: 32, 10: 1, 11: 4, 12: Ls, 13: 1, 14: 32 + 32 * kt, 15: 16,
                        16: 13, 17: 16, 18: 4, 19: 32, 20: 8, 21: 5, 22: 4, 23: 32, 24: 16, 25: 10, 26: 16}[s]
            def fLd(s):
                return {5: [Lp, 0, 0, 0], 6: SYSTEM, 7: [Lv, 0, 0, 0], 10: [0], 11: [Ls, 0, 0, 0], 13: [kt],
                        15: bgpB, 16: [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3], 18: [b2n(hr), 0, 0, 0],
                        19: refundId, 20: G_LE, 21: [2, 0, 0, 0, 0], 22: [2, 0, 0, 0], 23: peoDig,
                        24: u64(height) + [0] * 8, 25: [6, 0, 0, 0] + SYSTEM, 26: [0] * 16}.get(s, [])
            strOf = {6: rc['pred'], 8: recv, 12: rc['signer']}
            def segByte(s, i):
                if s in (5, 7, 11, 10, 13, 16, 18, 20, 21, 22, 24, 25, 26, 19, 23): return (fLd(s) + [0] * 64)[i]
                if s in strOf: return strOf[s][i]
                if s == 9: return rc['rid'][i]
                if s == 14: return rc['pk'][i]
                if s == 15: return u128(rc['gp'])[i]
                if s == 17: return u128(rc['dep'])[i]
                return 0
            gpB = lambda i: u128(rc['gp'])[i] if i < 16 else 0
            bg = lambda i: bgpB[i] if i < 16 else 0
            gdv = lambda i: bdig(gpB, bg, 0, i)
            pB = lambda i: 0 if sysr else (bg(i) if ge else gpB(i))
            surB = lambda i: gdv(i) if ge else 0
            x2 = lambda i: conv(G_LE[:5], pB, i)
            sb = lambda i: x2(i) + chain(x2, i)
            x3 = lambda i: conv(G_LE[:5], surB, i)
            sr = lambda i: x3(i) + chain(x3, i)
            tokOld = lambda i: u128(tok0)[i]
            tokNew = lambda i: u128(tok0 + burnt)[i]
            x4 = lambda i: tokOld(i) + sb(i) % 256
            tt = lambda i: x4(i) + chain(x4, i)
            befB = lambda i: u128(bef)[i]; depB = lambda i: u128(rc['dep'])[i]; lkB = lambda i: u128(locked)[i]
            stB = lambda i: u64(stor)[i] if i < 8 else 0
            aftB = lambda i: u128(aft)[i]; totB = lambda i: u128(aft + locked)[i]
            qB = lambda i: u128(S_PER_BYTE * stor)[i] if S_PER_BYTE * stor < TWO128 else 0
            y1 = lambda i: befB(i) + depB(i); sa = lambda i: y1(i) + chain(y1, i)
            y2 = lambda i: aftB(i) + lkB(i); stt = lambda i: y2(i) + chain(y2, i)
            y3 = lambda i: conv([0, 0, 232, 137, 4, 35, 199, 138], stB, i); sq = lambda i: y3(i) + chain(y3, i)
            dbr = lambda i: bchain(totB, qB, 0, i); ddv = lambda i: bdig(totB, qB, 0, i)
            runA = lambda i: runSum(lambda j2: 255 - aftB(j2), i)
            def accP(i): return runSum(lambda j2: sqd(rc['pred'][j2], SYSTEM[j2] if j2 < 6 else 0), i)
            def accV(i): return runSum(lambda j2: b2n(isHex(recv[j2])), i)
            h01V = b2n(isHex(recv[0])) + b2n(isHex(recv[1]))
            pP = (accP(Lp - 1) + sqd(Lp, 6)) % P
            pV1 = (sqd(Lv, 64) + sqd(accV(Lv - 1), Lv)) % P
            pV2 = (sqd(Lv, 42) + sqd(recv[0], 48) + sqd(recv[1], 120) + sqd(accV(Lv - 1), h01V + 40)) % P
            pV3 = (sqd(Lv, 42) + sqd(recv[0], 48) + sqd(recv[1], 115) + sqd(accV(Lv - 1), h01V + 40)) % P
            scnt = 0
            for s in flds:
                ln = fLen(s)
                for i in range(ln):
                    row = [0] * WIDTH
                    lst = i + 1 == ln
                    bv = segByte(s, i)
                    isRl = lst and (s == 26 or (s == 23 and not hr))
                    row[0] = 1; row[1] = b2n(s == 5 and i == 0); row[2] = b2n(isRl)
                    row[27] = i; row[28] = b2n(i == 0); row[29] = b2n(lst); row[30] = bv; row[s] = 1
                    # key slot A / B
                    if s == 8: row[43] = 2 + 2 * i; row[44] = bv // 16; row[46] = 1; row[L['tB']] = 3 + 2 * i; \
                        row[L['symB']] = bv % 16; row[L['gKB']] = 1
                    if s == 7 and i < 2: row[43] = i; row[46] = 1; row[47] = 1
                    if s == 9 and i == 0: row[43] = 2 + 2 * Lv; row[44] = END; row[45] = 1; row[46] = 1
                    if ee:
                        if s == 10: row[43] = 0; row[44] = 0; row[46] = 1; row[L['tB']] = 1; row[L['symB']] = 2; row[L['gKB']] = 1
                        if s == 11 and i == 0: row[43] = 2 + 2 * Ls; row[46] = 1; row[L['tB']] = 3 + 2 * Ls; \
                            row[L['symB']] = 2; row[L['gKB']] = 1
                        if s == 12: row[43] = 2 + 2 * i; row[44] = bv // 16; row[46] = 1; row[L['tB']] = 3 + 2 * i; \
                            row[L['symB']] = bv % 16; row[L['gKB']] = 1
                        if s == 13: row[43] = 4 + 2 * Ls; row[46] = 1; row[L['tB']] = 5 + 2 * Ls; row[L['symB']] = bv; \
                            row[L['gKB']] = 1
                        if s == 14:
                            row[43] = 6 + 2 * Ls + 2 * i; row[44] = bv // 16; row[46] = 1
                            row[L['tB']] = 7 + 2 * Ls + 2 * i; row[L['symB']] = bv % 16; row[L['gKB']] = 1
                            for t in range(4): row[xb(t)] = bit(bv // 16, t); row[xb(4 + t)] = bit(bv % 16, t)
                        if s == 15 and i == 0: row[43] = 70 + 2 * Ls + 64 * kt; row[44] = END; row[45] = 1; row[46] = 1
                    # receipt constants
                    for nm, v in [('r', r), ('o', o), ('o2', o2), ('Lp', Lp), ('Lv', Lv), ('Ls', Ls), ('kt', kt),
                                  ('hr', b2n(hr)), ('kslot', kslot), ('tprev', tprev), ('cj', cjx), ('ge', b2n(ge)),
                                  ('big', b2n(big)), ('oEnd', oEnd), ('o2End', o2End), ('j', j), ('nj', nj),
                                  ('sys', b2n(sysr)), ('ee', b2n(ee)), ('gq', b2n(ge and not sysr)), ('dm', dm),
                                  ('dd', dd), ('q', q)]:
                        row[L[nm]] = v
                    ld = fLd(s)
                    for t in range(32): row[reg(t)] = ld[i + t] if i + t < len(ld) else 0
                    for t in range(16):
                        if s in (5, 6, 7, 8, 9, 10, 11, 12, 13, 14): row[tok(t)] = tokOld(t)
                        elif s == 15: row[tok(t)] = tokOld(i + t) if i + t < 16 else tokNew(i + t - 16)
                        else: row[tok(t)] = tokNew(t)
                    if s in strOf:
                        for col in range(111, 124): row[col] = charCell(bv, col)
                    if s == 6: row[124] = accP(i) % P
                    if s == 8:
                        row[124] = accV(i); row[125] = recv[0]; row[126] = recv[1]; row[127] = h01V
                    if s == 6 and lst:
                        row[128] = pP; row[134] = 0 if sysr else inv(pP)
                    if s == 8 and lst:
                        row[128] = pV1; row[129] = pV2; row[130] = pV3
                        row[131] = inv(pV1); row[132] = inv(pV2); row[133] = inv(pV3)
                    row[135] = b2n(s == 17 and i == 1)
                    # xb
                    for jj in range(66):
                        v = 0
                        if s == 15:
                            if jj < 8: v = bit(gdv(i), jj)
                            elif jj == 8: v = bit(bchain(gpB, bg, 0, i + 1), 0)
                            elif jj < 20: v = bit(sb(i) // 256, jj - 9)
                            elif jj < 31: v = bit(sr(i) // 256, jj - 20)
                            elif jj < 39: v = bit(tt(i) % 256, jj - 31)
                            elif jj == 39: v = bit(tt(i) // 256, 0)
                        elif s == 17:
                            if jj < 8: v = bit(sa(i) % 256, jj)
                            elif jj == 8: v = bit(sa(i) // 256, 0)
                            elif jj < 17: v = bit(stt(i) % 256, jj - 9)
                            elif jj == 17: v = bit(stt(i) // 256, 0)
                            elif jj < 26: v = bit(sq(i) % 256, jj - 18)
                            elif jj < 38: v = bit(sq(i) // 256, jj - 26)
                            elif jj < 46: v = bit(ddv(i), jj - 38)
                            elif jj == 46: v = bit(dbr(i + 1), 0)
                            elif jj < 57: v = bit(770 - (stB(0) + 256 * stB(1)), jj - 47) if (i == 1 and not big) else 0
                            elif jj < 66: v = bit(r - tprev, jj - 57) if i == 0 else 0
                        elif s in strOf and lst:
                            if jj < 6: v = bit(ln - 2, jj)
                            elif jj < 12: v = bit(64 - ln, jj - 6)
                        if v: row[xb(jj)] = v
                    if s == 15:
                        row[204] = bchain(gpB, bg, 0, i); row[205] = chain(x2, i); row[206] = chain(x3, i); row[207] = chain(x4, i)
                        for t in range(4):
                            row[208 + t] = pB(i - 1 - t) if t < i else 0
                            row[212 + t] = surB(i - 1 - t) if t < i else 0
                        row[216] = sb(i) % 256; row[217] = sr(i) % 256; row[218] = runSum(gdv, i)
                        row[219] = inv(runSum(gdv, i)) if (lst and hr) else 0
                        row[L['pc']] = pB(i)
                    if s == 17:
                        row[204] = chain(y1, i); row[205] = chain(y2, i); row[206] = chain(y3, i); row[207] = dbr(i)
                        for t in range(7): row[208 + t] = stB(i - 1 - t) if t < i else 0
                        row[220] = befB(i); row[221] = lkB(i); row[222] = stB(i); row[223] = runA(i)
                        row[224] = inv(runA(i)) if lst else 0
                    if i == 0 and s in (19, 23):
                        row[227] = 1
                        row[225] = mid(K_RID, r) if s == 19 else mid(K_PEO, r)
                        row[226] = 48 if s == 19 else len(peo)
                    # signer = receiver
                    if s == 8:
                        row[L['gV']] = 1 if ee or (dd and i == dpos) else 0
                    if s == 12:
                        g = 1 if ee or (dd and i == dpos) else 0
                        row[L['gS']] = g
                        row[L['sx']] = recv[i] if g else 0
                        if dd and g: row[L['invD']] = inv(bv - recv[i])
                        scnt = (g if i == 0 else scnt + g); row[L['scnt']] = scnt
                    if s == 5 and i == 0:
                        if sysr and not ee and not dd: row[L['invL']] = inv(Ls - Lv)
                    # FINAL / AKC
                    if s == 5 and i == 0:
                        row[L['gF']] = 1; row[L['fkF']] = 0; row[L['kF']] = kslot
                    if s == 10 and ee:
                        row[L['gF']] = 1
                        row[L['fkF']] = 1 if ak is None else 0
                        row[L['kF']] = 0 if ak is None else ak['vid']
                        if ak is not None:
                            row[L['gAK']] = 1; row[L['uak']] = ak_use[ak['vid']]; ak_use[ak['vid']] += 1
                    # routing
                    if s == 8 or (s == 9 and i == 0):
                        pos = i if s == 8 else Lv
                        eL0, eH0 = eqLs[pos], eqHs[pos]
                        row[L['eqL']] = eL0; row[L['eqH']] = eH0
                        g = b2n(eL0 or eH0)
                        row[L['gBd']] = g
                        vB = vbs[pos]
                        row[L['vB']] = vB; row[L['iB']] = pos
                        if g:
                            x = STRIDE * q + pos
                            loB, hiB = lob[pos], hib[pos]
                            row[L['loB']] = loB; row[L['hiB']] = hiB; row[L['hnB']] = hn
                            row[L['uB']] = bnd_use[x]; bnd_use[x] += 1
                            d1, d2 = vB - loB + 255, hiB - vB + 255
                            for t in range(9): row[xb(20 + t)] = bit(d1, t); row[xb(29 + t)] = bit(d2, t)
                            row[L['eL']] = b2n(vB == loB); row[L['eH']] = b2n(hiB == vB)
                            row[L['iL']] = inv(vB - loB); row[L['iH']] = inv(hiB - vB)
                        elif s == 8 and i == 0:
                            row[L['hnB']] = hn
                    rows.append(row)
            outcomes.append(leaf)
            allrc.append(rc)
            o = oEnd; o2 = o2End; r += 1
        expRcl[(j, o)] += 1
    nAct = len(rows)
    # le / lastR
    for k in range(nAct):
        row = rows[k]
        brk = row[2] or (row[4] and row[29])
        nxt_rf = rows[k + 1][1] if k + 1 < nAct else 0
        row[L['le']] = b2n(brk and not nxt_rf)
        row[3] = b2n(row[L['le']] and k + 1 == nAct)
    H = 1
    while H < nAct + 1: H *= 2
    H = max(H, 2)
    rows += [[0] * WIDTH for _ in range(H - nAct)]
    body = sum(refunds, [])
    pub = [0] * 220
    for t, x in enumerate(u32(r)): pub[PH_N + t] = x
    for t, x in enumerate(u64(own)): pub[PH_OWN + t] = x
    for t, x in enumerate(u64(height)): pub[PH_HEIGHT + t] = x
    for t, x in enumerate(bgpB): pub[PH_GP + t] = x
    for t, x in enumerate(u128(tok_total)): pub[PH_BURNT + t] = x
    for t, x in enumerate(u32(8 + len(body))): pub[PH_BLEN + t] = x
    # emission slots from the constraints
    for k in range(nAct):
        row = rows[k]
        s = next(st for st in range(4, 27) if row[st] == 1)
        for col, E in EMIT[s].items():
            row[col] = ev(E, rows, k, pub, H)
    exp = dict(bytes=expBytes, key=expKey, final=expFinal, rcl=expRcl, body=body, ak_use=ak_use, bnd_use=bnd_use,
               lob=lob, hib=hib, hn=hn, q=q, state=state, accts=inst['accts'], last_write=last_write, n=r,
               akeys=inst['akeys'])
    return rows, pub, H, exp

# ---------------------------------------------------------------- checks
def check(rows, pub, H, exp):
    bad = []
    for k in range(H):
        for ci, e in enumerate(CONS):
            if ev(e, rows, k, pub, H) != 0:
                bad.append(('C', k, ci)); break
    if bad: return bad[:5]
    sends, recvs = defaultdict(Counter), defaultdict(Counter)
    for k in range(H):
        for bus, snd, mu, msg in INTS:
            m = ev(mu, rows, k, pub, H)
            if m not in (0, 1): return [('mult', k, bus)]
            if m:
                t = tuple(ev(x, rows, k, pub, H) for x in msg)
                (sends if snd else recvs)[bus][t] += 1
    # BYTES
    got = defaultdict(dict)
    for (i, p, b), c in sends[0].items():
        if c != 1 or p in got[i]: return [('dupbyte', i, p)]
        got[i][p] = b
    eb = exp['bytes']
    if set(got) != set(eb): return [('ids', sorted(set(got) ^ set(eb))[:5])]
    for i in eb:
        if got[i] != eb[i]: return [('bytes', i)]
    # DIGEST receives
    for (i, ln, *d), c in recvs[1].items():
        msg = [got[i][p] for p in range(ln)]
        if sha(msg) != d: return [('digest', i)]
    # body
    body = exp['body']
    if sorted(got.get(K_RF, {}).items()) != [(8 + t, x) for t, x in enumerate(body)]: return [('body',)]
    # KEYNIB
    gk = defaultdict(list)
    for (w, t, s, la), c in sends[5].items():
        gk[w] += [(t, s, la)] * c
    if {w: sorted(v) for w, v in gk.items()} != {w: sorted(v) for w, v in exp['key'].items()}: return [('keynib',)]
    if recvs[6] != exp['final']: return [('final', recvs[6], exp['final'])]
    if sends[26] != exp['rcl']: return [('rcl', sends[26], exp['rcl'])]
    if sends[16] != recvs[16]: return [('srec',)]
    # AKC with akeyV3
    akS, akR = Counter(sends[27]), Counter(recvs[27])
    for vid, U in exp['ak_use'].items(): akS[(vid, 0)] += 1; akR[(vid, U)] += 1
    if akS != akR: return [('akc',)]
    # BND with bndV3
    bS, bR = Counter(sends[15]), Counter(recvs[15])
    for x, U in exp['bnd_use'].items():
        pos = x - STRIDE * exp['q']
        rec = (x, exp['lob'][pos], exp['hib'][pos], exp['hn'])
        bS[rec + (0,)] += 1; bR[rec + (U,)] += 1
    if bS != bR: return [('bnd',)]
    # MEM with acctV3
    mS, mR = Counter(sends[7]), Counter(recvs[7])
    for a, v in exp['accts'].items():
        vid = v['vid']
        if vid not in exp['last_write']: continue
        fin = exp['state'][a]
        for i in range(16):
            lk = u128(v['locked'])[i]; st = u64(v['stor'])[i] if i < 8 else 0
            mS[(vid, 0, i, u128(v['amt'])[i], lk, st)] += 1
            mR[(vid, exp['last_write'][vid], i, u128(fin['amt'])[i], lk, st)] += 1
    if mS != mR: return [('mem',)]
    return []

def main():
    seed = int(sys.argv[2]) if len(sys.argv) > 2 else 1
    n = int(sys.argv[3]) if len(sys.argv) > 3 else 50
    rng = random.Random(seed)
    done = fails = 0
    stats = Counter()
    while done < n:
        inst = gen(rng)
        if inst is None: continue
        rows, pub, H, exp = build(inst, rng)
        res = check(rows, pub, H, exp)
        done += 1
        rcs = [rc for rs in inst['lists'] for rc in rs]
        stats['receipts'] += len(rcs); stats['sys'] += sum(rc['sys'] for rc in rcs)
        stats['ee'] += sum(rc['sys'] and rc['signer'] == rc['recv'] for rc in rcs)
        stats['empty_lists'] += sum(1 for rs in inst['lists'] if not rs)
        if res:
            fails += 1
            print('FAIL', done, res[:3])
            if res[0][0] == 'C':
                k, ci = res[0][1], res[0][2]
                print('  row', k, 'state', [st for st in range(4, 27) if rows[k][st] == 1], 'constraint', CONS[ci])
            if fails > 3: break
    print(f'{done} instances, {fails} failures; {dict(stats)}')

main()
