import ArenaExpectedInst
import ReexecWitness.Obligations
import ReexecWitness.PublicBin

/-!
# The certificate

Its type, `ArenaExpectedInst.expectedType`, is generated by the judge
(native-lean route): `ArenaExpected.expectedTypeFor ReexecWitness.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest
toolchainId ReexecWitness.Model.verifier }`. Every literal in it (profile,
fuel, `maxProofBytes`, digests, toolchain id) is fixed by the judge; the proof
below works for any of them except `maxProofBytes < 3 088 869` and a public
digest other than `sha256 publicBin`.
-/

namespace ReexecWitness

/-- ATTACK: certified at a 40-bit security target instead of the profile's 128. -/
def weakParams : ArenaCore.ChallengeParams :=
  NearSpec.TransferV1.challengeParamsWith
    (NearSpec.TransferV1.profileOf "validity-classical-128" "random_oracle" 40
      ["sha256-collision-resistance", "random-oracle-fiat-shamir-sha256"] 40 64)
    1073741824 8388608 1073741824

theorem certificate :
    ArenaCore.AdmissionStatement weakParams (ArenaExpected.artifactsFor Model.verifier) :=
  admission _ _ _ _ (by decide) publicBin _ _ _ (by decide +kernel)

end ReexecWitness
