import NearSpecV3.Wasm.Syntax
/-!
# PV86 host-function signatures (module `env`)

Generated from `docs/research/near-wasm-boundary-inventory.json` (itself extracted from the pinned
nearcore `runtime/near-vm-runner/src/imports.rs` by `tools/d3/boundary_inventory.py`): the
89 imports linked in a production build at PV86 (every PV85 gate is on). Rust `u64` ↦ i64,
`u32` ↦ i32 (`wasmtime_runner/mod.rs:1127-1155`). Linking an import not in this table, or with a
different signature, is a `LinkError`.
-/
namespace NearSpecV3.Wasm

def hostSigs : Array (String × FuncType) := #[
  ("read_register", { params := #[.i64, .i64], results := #[] }),
  ("register_len", { params := #[.i64], results := #[.i64] }),
  ("write_register", { params := #[.i64, .i64, .i64], results := #[] }),
  ("current_account_id", { params := #[.i64], results := #[] }),
  ("chain_id", { params := #[.i64], results := #[] }),
  ("signer_account_id", { params := #[.i64], results := #[] }),
  ("signer_account_pk", { params := #[.i64], results := #[] }),
  ("predecessor_account_id", { params := #[.i64], results := #[] }),
  ("input", { params := #[.i64], results := #[] }),
  ("block_index", { params := #[], results := #[.i64] }),
  ("block_timestamp", { params := #[], results := #[.i64] }),
  ("epoch_height", { params := #[], results := #[.i64] }),
  ("storage_usage", { params := #[], results := #[.i64] }),
  ("account_balance", { params := #[.i64], results := #[] }),
  ("account_locked_balance", { params := #[.i64], results := #[] }),
  ("attached_deposit", { params := #[.i64], results := #[] }),
  ("prepaid_gas", { params := #[], results := #[.i64] }),
  ("used_gas", { params := #[], results := #[.i64] }),
  ("random_seed", { params := #[.i64], results := #[] }),
  ("sha256", { params := #[.i64, .i64, .i64], results := #[] }),
  ("keccak256", { params := #[.i64, .i64, .i64], results := #[] }),
  ("keccak512", { params := #[.i64, .i64, .i64], results := #[] }),
  ("ed25519_verify", { params := #[.i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("p256_verify", { params := #[.i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("ripemd160", { params := #[.i64, .i64, .i64], results := #[] }),
  ("ecrecover", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("value_return", { params := #[.i64, .i64], results := #[] }),
  ("panic", { params := #[], results := #[] }),
  ("panic_utf8", { params := #[.i64, .i64], results := #[] }),
  ("log_utf8", { params := #[.i64, .i64], results := #[] }),
  ("log_utf16", { params := #[.i64, .i64], results := #[] }),
  ("abort", { params := #[.i32, .i32, .i32, .i32], results := #[] }),
  ("promise_create", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("promise_then", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("promise_and", { params := #[.i64, .i64], results := #[.i64] }),
  ("promise_batch_create", { params := #[.i64, .i64], results := #[.i64] }),
  ("promise_batch_then", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("promise_set_refund_to", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_state_init", { params := #[.i64, .i64, .i64, .i64], results := #[.i64] }),
  ("promise_batch_action_state_init_by_account_id", { params := #[.i64, .i64, .i64, .i64], results := #[.i64] }),
  ("set_state_init_data_entry", { params := #[.i64, .i64, .i64, .i64, .i64, .i64], results := #[] }),
  ("current_contract_code", { params := #[.i64], results := #[.i64] }),
  ("refund_to_account_id", { params := #[.i64], results := #[] }),
  ("promise_batch_action_create_account", { params := #[.i64], results := #[] }),
  ("promise_batch_action_deploy_contract", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_deploy_global_contract", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_deploy_global_contract_by_account_id", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_use_global_contract", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_use_global_contract_by_account_id", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_function_call", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_function_call_weight", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_transfer", { params := #[.i64, .i64], results := #[] }),
  ("promise_batch_action_stake", { params := #[.i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_add_key_with_full_access", { params := #[.i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_add_key_with_function_call", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_delete_key", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_delete_account", { params := #[.i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_transfer_to_gas_key", { params := #[.i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_add_gas_key_with_full_access", { params := #[.i64, .i64, .i64, .i64], results := #[] }),
  ("promise_batch_action_add_gas_key_with_function_call", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[] }),
  ("promise_yield_create", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("promise_yield_create_with_id", { params := #[.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("promise_yield_resume", { params := #[.i64, .i64, .i64, .i64], results := #[.i32] }),
  ("promise_yield_resume_with_yield_id", { params := #[.i64, .i64, .i64, .i64], results := #[.i32] }),
  ("promise_results_count", { params := #[], results := #[.i64] }),
  ("promise_result", { params := #[.i64, .i64], results := #[.i64] }),
  ("promise_return", { params := #[.i64], results := #[] }),
  ("storage_write", { params := #[.i64, .i64, .i64, .i64, .i64], results := #[.i64] }),
  ("storage_read", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("storage_remove", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("storage_has_key", { params := #[.i64, .i64], results := #[.i64] }),
  ("storage_iter_prefix", { params := #[.i64, .i64], results := #[.i64] }),
  ("storage_iter_range", { params := #[.i64, .i64, .i64, .i64], results := #[.i64] }),
  ("storage_iter_next", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("gas", { params := #[.i32], results := #[] }),
  ("validator_stake", { params := #[.i64, .i64, .i64], results := #[] }),
  ("validator_total_stake", { params := #[.i64], results := #[] }),
  ("alt_bn128_g1_multiexp", { params := #[.i64, .i64, .i64], results := #[] }),
  ("alt_bn128_g1_sum", { params := #[.i64, .i64, .i64], results := #[] }),
  ("alt_bn128_pairing_check", { params := #[.i64, .i64], results := #[.i64] }),
  ("bls12381_p1_sum", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_p2_sum", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_g1_multiexp", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_g2_multiexp", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_map_fp_to_g1", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_map_fp2_to_g2", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_pairing_check", { params := #[.i64, .i64], results := #[.i64] }),
  ("bls12381_p1_decompress", { params := #[.i64, .i64, .i64], results := #[.i64] }),
  ("bls12381_p2_decompress", { params := #[.i64, .i64, .i64], results := #[.i64] })
]

def hostSig? (name : String) : Option FuncType :=
  (hostSigs.find? (·.1 = name)).map (·.2)

end NearSpecV3.Wasm
