import ZkFormal.NearV3.Assembly.RcptSkeletonCellControl

namespace ZkFormal.NearV3.Assembly.RcptSkeleton
open NearSpec NearSpecV3 ZkFormal.Air ZkFormal.Algebra ZkFormal.Near ZkFormal.Near.Dsl RcptV3

/-- Exact register initialization prescribed by the existing loads family. The
source may later extend this list (e.g. CL appends its u32 list count). -/
def registerLoad (x : Input) (pub : List Fp) (state : Nat) : List Fp :=
  match loads.find? (fun p=>p.1==state) with
  | none=>[]
  | some (_,es)=>es.map fun e=>e.eval (shapeTrace x) 0 0 pub

theorem registerLoad_exact (x : Input) (pub : List Fp) {state : Nat} {es : List Expr}
    (hm : (state,es)∈loads) :
    registerLoad x pub state=es.map (fun e=>e.eval (shapeTrace x) 0 0 pub) := by
  simp only [loads,List.mem_cons,List.not_mem_nil,or_false] at hm
  rcases hm with hm|hm|hm|hm|hm|hm|hm|hm|hm|hm|hm|hm|hm|hm|hm|hm <;> cases hm <;> rfl

def registerCell (data : List Fp) (pos col : Nat) : Fp :=
  if reg 0≤col ∧ col<reg 32 then data.getD (pos+col-reg 0) 0 else 0

theorem registerCell_read (data : List Fp) (pos j : Nat) (hj : j<32) :
    registerCell data pos (reg j)=data.getD (pos+j) 0 := by
  have hr : reg 0≤reg j ∧ reg j<reg 32 := by unfold reg;omega
  have he : pos+reg j-reg 0=pos+j := by unfold reg;omega
  simp only [registerCell,if_pos hr,he]

/-- Every internal register shift is generated by indexing the same byte stream;
no AIR equality or carry witness is an input. -/
theorem registerCell_shift (data : List Fp) (pos j : Nat) (hj : j<31) :
    registerCell data (pos+1) (reg j)=registerCell data pos (reg (j+1)) := by
  rw [registerCell_read data (pos+1) j (by omega),registerCell_read data pos (j+1) (by omega)]
  congr 1
  omega

theorem registerCell_initial (x : Input) (pub : List Fp) {state j : Nat} {es : List Expr}
    (hm : (state,es)∈loads) (hj : j<es.length) (h32 : j<32) :
    registerCell (registerLoad x pub state) 0 (reg j)=
      es[j].eval (shapeTrace x) 0 0 pub := by
  rw [registerCell_read _ 0 j h32,registerLoad_exact x pub hm]
  simp only [Nat.zero_add,List.getD_eq_getElem?_getD,List.getElem?_map,
    List.getElem?_eq_getElem hj,Option.map_some,Option.getD_some]

theorem loads_length : ∀p∈loads,p.2.length≤32 := by decide

/-- The exact state-load and index pair from cRegs selects the executable stream
value at its initial row, covering every entry in the unchanged load table. -/
theorem register_load_entry (x : Input) (pub : List Fp) {state j : Nat} {es : List Expr}
    (hm : (state,es)∈loads) {e : Expr} (he : (e,j)∈es.zip (List.range es.length)) :
    registerCell (registerLoad x pub state) 0 (reg j)=e.eval (shapeTrace x) 0 0 pub := by
  obtain ⟨i,hi,heq⟩ := List.mem_iff_getElem.mp he
  have hilen : i<es.length := by simpa only [List.length_zip,List.length_range,Nat.min_self] using hi
  have heq' : (es[i],i)=(e,j) := by simpa [List.getElem_zip,List.getElem_range,hilen] using heq
  have helem := congrArg Prod.fst heq'
  have hij := congrArg Prod.snd heq'
  dsimp only at helem hij
  subst j
  rw [registerCell_initial x pub hm hilen (by have hb : es.length≤32 := loads_length (state,es) hm;omega),helem]

end ZkFormal.NearV3.Assembly.RcptSkeleton
