// Generated by sdk/typescript/scripts/gen-types.mjs from common/schemas/*.schema.json.
// DO NOT EDIT. Regenerate after `cargo run -p arena-types --bin gen-schemas`.
// Integers (ns, bytes, ppm, milli-scores) are JSON numbers; all fit in 2^53.

export type AdversaryClass = "classical";

/** Governed cryptographic assumption, pinned to an exact Lean declaration in `formal-core` (`security/assumptions/<id>.json`). */
export interface Assumption {
  description: string;
  id: string;
  /** Fully qualified Lean name of the hypothesis *definition* (a `Prop`-valued def in formal-core), e.g. `Arena.Assumptions.Sha256CollisionResistant`. */
  lean_decl: string;
  /** Digest of the Lean declaration's exported type+value (filled by the governance tooling; checked by the formal checker). */
  lean_decl_digest?: Digest | null;
  references: string[];
}

export interface BenchmarkResult {
  classes: ClassMeasurement[];
  hardware_profile: string;
  measured_by: string;
  prepare_ns: number;
  public_artifact_bytes: number;
  /** Half-width of a bootstrap 95% interval, milli units. */
  score_ci_milli?: number | null;
  /** Score * 1000 as integer (e.g. 100000 == 100.000). */
  score_milli?: number | null;
  suite_revision: string;
}

export interface BuildSection {
  outputs: string[];
  recipe: string;
}

/** Parsed `candidate.toml`. Every field is a *claim* the judge validates. */
export interface CandidateManifest {
  agent: string;
  backend_family: string;
  build: BuildSection;
  challenge: string;
  entry: EntrySection;
  formal?: FormalSection | null;
  hardware: HardwareRequest;
  name: string;
  parent?: string | null;
  schema: string;
  security_profile_request: string;
}

export interface ChallengeDefinition {
  chain_id: string;
  claim_encoding: ClaimEncoding;
  created_at: string;
  hardware_profile: HardwareProfile;
  measurement: MeasurementProcedure;
  name: string;
  nearcore: NearcorePin;
  /** Gates that may be `NOT_APPLICABLE` under this challenge (e.g. FORMAL_ZK for validity-only profiles). */
  not_applicable_gates: ObligationId[];
  protocol_version: number;
  required_obligations: ObligationId[];
  resource_limits: ResourceLimits;
  runtime_config_digest: Digest;
  schema: string;
  season: string;
  security_profile: SecurityProfile;
  semantic_scope: SemanticScope;
  supersedes?: string | null;
  tier: Tier;
  toolchain_policy: ToolchainPolicy;
  workload_suite: WorkloadSuite;
}

/** Change classification, computed by the judge (never trusted from the agent). */
export type ChangeClass = "NO_PARENT" | "PROVER_ONLY" | "VERIFIER_OR_PROTOCOL";

export interface ClaimEncoding {
  format: string;
  max_claim_bytes: number;
  max_request_bytes: number;
  max_witness_bytes: number;
  spec_digest: Digest;
}

export interface ClassMeasurement {
  baseline_ns: number;
  class_id: string;
  cold_ns?: number | null;
  mad_ns: number;
  median_ns: number;
  peak_rss_bytes: number;
  proof_bytes_max: number;
  runs_ns: number[];
  verify_median_ns: number;
  weight_ppm: number;
}

export type Decision = "ADMITTED" | "REJECTED" | "INCONCLUSIVE" | "INFRA_ERROR" | "CANCELLED";

/** `sha256:<64 lowercase hex>` */
export type Digest = string;

export type EdgeStatus = "checked" | "trusted" | "tested" | "missing";

export interface EntrySection {
  prepare: string;
  prove: string;
  verify: string;
}

export interface EvidenceEdge {
  evidence: Digest[];
  from: string;
  /** e.g. `refines`, `binds`, `assumes`, `built_from`, `tested_against`. */
  kind: string;
  note: string;
  status: EdgeStatus;
  to: string;
}

export interface EvidenceGraph {
  edges: EvidenceEdge[];
  nodes: EvidenceNode[];
}

export interface EvidenceNode {
  digest?: Digest | null;
  id: string;
  kind: NodeKind;
  label: string;
}

export interface EvidenceRef {
  digest: Digest;
  label: string;
  /** Whether this artifact may be shown publicly (held-out data must not). */
  public: boolean;
}

export interface FormalSection {
  /** Lean constant whose *type* the judge constructs; candidate supplies the value. */
  certificate: string;
  lean_project: string;
}

export interface FormalSpecRef {
  /** Lean toolchain, e.g. `leanprover/lean4:v4.x.y`. */
  lean_toolchain: string;
  /** Fully qualified Lean name of the relation, e.g. `NearSpec.TransferV1.NearRelation`. */
  relation_decl: string;
  /** Lean module that defines `NearRelation` for this challenge. */
  relation_module: string;
  /** Tree digest of `spec/lean` + `formal-core` sources the challenge was frozen against. */
  tree_digest: Digest;
}

export interface GateResult {
  evidence: EvidenceRef[];
  finished_at?: string | null;
  /** Gate id; equals the obligation id for obligation gates. */
  gate: ObligationId;
  mandatory: boolean;
  reason_codes: ReasonCode[];
  /** Set when the result was reused from a parent via the content-addressed cache. */
  reused_from?: string | null;
  started_at?: string | null;
  status: GateStatus;
  /** Bounded, sanitized, plain text (never HTML). */
  summary: string;
}

export type GateStatus = "PASS" | "FAIL" | "UNKNOWN" | "NOT_APPLICABLE";

export interface HardwareProfile {
  cpu_model: string;
  gpu?: string | null;
  id: string;
  ram_bytes: number;
  vcpus: number;
}

export interface HardwareRequest {
  gpu: boolean;
  min_ram_gb: number;
}

export interface LeaderboardEntry {
  accepted?: boolean | null;
  agent: string;
  backend_family: string;
  candidate_name: string;
  decision?: Decision | null;
  hardware_profile: string;
  peak_rss_bytes?: number | null;
  proof_bytes?: number | null;
  prove_median_ns?: number | null;
  rank?: number | null;
  revoked: boolean;
  scope: string;
  score_milli?: number | null;
  security_profile: string;
  submission_id: string;
  submitted_at: string;
  tier: Tier;
  verify_median_ns?: number | null;
}

export interface MeasurementProcedure {
  /** `median` only in v1. */
  aggregation: string;
  cold_runs: number;
  concurrency: number;
  measured_runs: number;
  /** Runs farther than this many MADs from the median are flagged (not dropped). */
  outlier_mad_k: number;
  per_run_timeout_ms: number;
  warmup_runs: number;
}

export interface NearcorePin {
  commit: string;
  repo: string;
  tag: string;
}

export type NodeKind = "nearcore_source" | "formal_semantics" | "backend_semantics" | "theorem" | "assumption" | "artifact" | "tcb_component" | "test_suite" | "measurement";

export type ObligationId = "PKG_WELLFORMED" | "BUILD_REPRODUCIBLE" | "ARTIFACT_BINDING" | "FORMAL_SEMANTIC_SOUNDNESS" | "FORMAL_SEMANTIC_COMPLETENESS" | "FORMAL_CRYPTO_SOUNDNESS" | "FORMAL_IMPL_CONNECTION" | "FORMAL_ZK" | "AXIOM_AUDIT" | "CONFORMANCE_DIFFERENTIAL" | "ADVERSARIAL_PROOFS" | "PROVER_RELIABILITY" | "RESOURCE_LIMITS" | "BENCHMARK";

export type Privacy = "validity_only" | "zero_knowledge";

export type ReasonCode = "MANIFEST_INVALID" | "ARCHIVE_UNSAFE" | "CHALLENGE_UNKNOWN" | "PROFILE_NOT_ALLOWED" | "BUILD_FAILED" | "BUILD_NOT_REPRODUCIBLE" | "CERTIFICATE_MISSING" | "THEOREM_TYPE_MISMATCH" | "UNAPPROVED_ASSUMPTION" | "FORBIDDEN_AXIOM" | "SORRY_FOUND" | "NATIVE_EVAL_FOUND" | "SHADOWED_DEFINITION" | "RECHECK_FAILED" | "ARTIFACT_BINDING_FAILED" | "CLAIM_MISMATCH" | "COUNTEREXAMPLE_FOUND" | "HOSTILE_PROOF_ACCEPTED" | "VERIFIER_NONDETERMINISTIC" | "PROVER_FAILED" | "RESOURCE_LIMIT" | "TIMEOUT" | "SANDBOX_VIOLATION" | "SECURITY_BOUND_INSUFFICIENT" | "OBLIGATION_UNDISCHARGED" | "DEMO_ONLY" | "INFRA_ERROR" | "CANCELLED";

export interface ResourceLimits {
  max_build_ms: number;
  max_prepare_ms: number;
  max_proof_bytes: number;
  max_prove_ms: number;
  max_public_artifact_bytes: number;
  max_ram_bytes: number;
  max_verify_ms: number;
  max_vram_bytes: number;
}

export interface Restriction {
  id: string;
  text: string;
}

export interface Revocation {
  reason: string;
  revoked_at: string;
  revoked_by: string;
}

export type ScopeKind = "full_chunk_transition" | "subset";

export type SecurityModel = "standard" | "random_oracle";

/** Governed security profile (`security/profiles/<id>.json`). */
export interface SecurityProfile {
  adversary: AdversaryClass;
  /** Ids into `security/assumptions/*.json`; each pins an exact Lean declaration. */
  allowed_assumptions: string[];
  deployment_proofs_log2: number;
  id: string;
  max_aggregation_depth: number;
  max_hash_queries_log2: number;
  max_prover_queries_log2: number;
  model: SecurityModel;
  privacy: Privacy;
  setup_model: SetupModel;
  target_bits: number;
}

export interface SemanticScope {
  /** Properties explicitly NOT established by an admitted proof. */
  excludes: string[];
  formal_spec: FormalSpecRef;
  /** e.g. `single_action_receipt_transition`, `chunk_transition`. */
  granularity: string;
  kind: ScopeKind;
  name: string;
  restrictions: Restriction[];
  /** Human-readable spec document digest (`spec/<name>.md`). */
  spec_doc_digest: Digest;
}

export type SetupModel = "none" | "transparent" | "approved_ceremony";

export type Stage = "RECEIVED" | "VALIDATED" | "BUILT" | "FORMAL_CHECKED" | "CONFORMANCE_CHECKED" | "BENCHMARKED" | "DECIDED";

/** Public view of a submission (API `GET /v1/submissions/{id}`). */
export interface SubmissionView {
  /** `null` while pending; `true` only if every mandatory gate passed. */
  accepted?: boolean | null;
  agent: string;
  backend_family: string;
  benchmark?: BenchmarkResult | null;
  candidate_name: string;
  challenge_id: string;
  change_class?: ChangeClass | null;
  created_at: string;
  decision?: Decision | null;
  evidence_graph?: EvidenceGraph | null;
  gates: GateResult[];
  id: string;
  package_digest: Digest;
  parent?: string | null;
  reason_codes: ReasonCode[];
  revoked?: Revocation | null;
  score_milli?: number | null;
  stage: Stage;
  tier: Tier;
  updated_at: string;
}

export type Tier = "formal" | "experimental" | "demo";

export interface ToolchainPolicy {
  /** Allowed Lean package imports: name -> pinned git commit. */
  allowed_packages: Array<[string, string]>;
  /** Exact logical axioms permitted (fully qualified names). */
  axiom_allowlist: string[];
  /** Digest of the formal checker image (rootfs) used for clean rechecks. */
  checker_image: Digest;
  lean_toolchain: string;
  /** Independent kernel recheckers that must all accept, e.g. `lean4checker`, `nanoda`. */
  recheckers: string[];
}

/** The digests that define the *verified* surface. If all are equal between a child and its parent, formal results may be reused (`ProverOnly`). */
export interface VerifiedSurface {
  certificate_decl: string;
  challenge_id: string;
  checker_image: Digest;
  formal_tree: Digest;
  prepare_artifact: Digest;
  public_artifacts: Digest;
  verify_artifact: Digest;
}

export interface WorkloadClass {
  /** Number of requests per measured batch. */
  batch_size: number;
  description: string;
  /** Digest of the generator spec (fresh inputs are sampled after freeze). */
  generator: Digest;
  id: string;
  /** Weight in parts-per-million; all weights in a suite sum to 1_000_000. */
  weight_ppm: number;
}

export interface WorkloadSuite {
  baseline_ns: Array<[string, number]>;
  /** Baseline candidate submission id and per-class baseline medians (ns). */
  baseline_submission?: string | null;
  classes: WorkloadClass[];
  /** Commitment to the held-out set (digest of its tree), revealed at season end. */
  heldout_commitment: Digest;
  /** Public dev fixtures (tree digest). Held-out and fresh inputs are not listed here. */
  public_fixtures: Digest;
  revision: string;
}
