-- Generated by `arena-server roles-sql` (server/arena-db/src/roles.rs). Do not edit.
-- Run as the schema owner after `arena-server migrate`.
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_api') THEN CREATE ROLE arena_api NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_worker') THEN CREATE ROLE arena_worker NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_admin') THEN CREATE ROLE arena_admin NOLOGIN; END IF; END $$;
REVOKE ALL ON agents, admins, workers, challenges, uploads, artifacts, submissions, runs, gate_results, jobs, audit_events, revocations, formal_cache, quotas, reports FROM PUBLIC;
REVOKE ALL ON agents, admins, workers, challenges, uploads, artifacts, submissions, runs, gate_results, jobs, audit_events, revocations, formal_cache, quotas, reports FROM arena_api;
GRANT USAGE ON SCHEMA public TO arena_api;
GRANT USAGE ON SEQUENCE audit_events_id_seq TO arena_api;
GRANT SELECT ON agents, challenges, uploads, submissions, runs, gate_results, jobs, audit_events, revocations, quotas, reports TO arena_api;
GRANT INSERT ON uploads, submissions, runs, jobs, audit_events, reports TO arena_api;
GRANT UPDATE ON runs, jobs, agents TO arena_api;
REVOKE ALL ON agents, admins, workers, challenges, uploads, artifacts, submissions, runs, gate_results, jobs, audit_events, revocations, formal_cache, quotas, reports FROM arena_worker;
GRANT USAGE ON SCHEMA public TO arena_worker;
GRANT USAGE ON SEQUENCE audit_events_id_seq, gate_results_id_seq, formal_cache_id_seq TO arena_worker;
GRANT SELECT ON workers, agents, challenges, uploads, artifacts, submissions, runs, gate_results, jobs, formal_cache, reports, revocations TO arena_worker;
GRANT INSERT ON artifacts, gate_results, jobs, audit_events, formal_cache, reports TO arena_worker;
GRANT UPDATE ON runs, jobs TO arena_worker;
REVOKE ALL ON agents, admins, workers, challenges, uploads, artifacts, submissions, runs, gate_results, jobs, audit_events, revocations, formal_cache, quotas, reports FROM arena_admin;
GRANT USAGE ON SCHEMA public TO arena_admin;
GRANT USAGE ON SEQUENCE audit_events_id_seq, gate_results_id_seq, revocations_id_seq, formal_cache_id_seq TO arena_admin;
GRANT SELECT ON agents, admins, workers, challenges, uploads, artifacts, submissions, runs, gate_results, jobs, audit_events, revocations, formal_cache, quotas, reports TO arena_admin;
GRANT INSERT ON agents, admins, workers, challenges, revocations, quotas, runs, jobs, gate_results, audit_events, reports, formal_cache TO arena_admin;
GRANT UPDATE ON agents, admins, workers, challenges, quotas, runs, jobs, formal_cache TO arena_admin;
