from hp import *
C = []
# baseline: empty main with value_return of nothing
C.append(("empty", P().done(False)))
C.append(("vr0", P().done((0, 0))))
C.append(("base: block_index", P().call("block_index").done()))
C.append(("block_timestamp", P().call("block_timestamp").done()))
C.append(("epoch_height", P().call("epoch_height").done()))
C.append(("storage_usage", P().call("storage_usage").done()))
C.append(("prepaid_gas", P().call("prepaid_gas").done()))
C.append(("used_gas", P().call("used_gas").done()))
C.append(("current_account_id", P().call("current_account_id", 0).call("register_len", 0).done()))
C.append(("chain_id", P().call("chain_id", 0).call("register_len", 0).call("read_register", 0, 100).done((100, 32))))
C.append(("signer_pk", P().call("signer_account_pk", 0).call("read_register", 0, 100).done((100, 8))))
C.append(("input", P(opts="input=0102030405").call("input", 0).call("read_register", 0, 100).done((100, 8))))
C.append(("current_contract_code", P().call("current_contract_code", 0).call("register_len", 0).done()))
C.append(("account_balance", P(opts="deposit=5;balance=7").call("account_balance", 100).done((100, 16))))
C.append(("locked", P().call("account_locked_balance", 100).done((100, 16))))
C.append(("random_seed", P().call("random_seed", 1).call("read_register", 1, 100).done((100, 40))))
C.append(("sha256", P(b"abc").call("sha256", 3, 0, 1).call("read_register", 1, 100).done((100, 32))))
C.append(("keccak256", P(b"abc").call("keccak256", 3, 0, 1).call("read_register", 1, 100).done((100, 32))))
C.append(("keccak512", P(b"abc").call("keccak512", 3, 0, 1).call("read_register", 1, 100).done((100, 64))))
C.append(("ripemd", P(b"abc").call("ripemd160", 3, 0, 1).call("read_register", 1, 100).done((100, 20))))
C.append(("validator_stake", P(b"bob.near").call("validator_stake", 8, 0, 100).done((100, 16))))
C.append(("validator_total", P().call("validator_total_stake", 100).done((100, 16))))
C.append(("iter_prefix", P().call("storage_iter_prefix", 0, 0).done()))
C.append(("iter_next", P().call("storage_iter_next", 0, 0, 0).done()))
C.append(("log", P(b"hello").call("log_utf8", 5, 0).done()))
C.append(("log16", P("hi".encode("utf-16-le")).call("log_utf16", 4, 0).done()))
C.append(("panic_utf8", P("a\"\n\t\\\x01\x7f é​".encode()).call("panic_utf8", len("a\"\n\t\\\x01\x7f é​".encode()), 0).done()))
show(C, 900)
