import ArenaExpectedInst
import NpUdrStark.Assembly
import ZkFormal.NearAssembly.NearClosed

/-!
# `NpUdrStark.certificate` — the admission certificate (native-lean route)

Its type `ArenaExpectedInst.expectedType` is generated by the judge:
`ArenaExpected.expectedTypeFor NpUdrStark.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest toolchainId Model.verifier }`.
`certificate_of` covers every validity-classical-128 literal. The L6 inputs are
`Render.render_stmt_closed` and `NearAssembly.near_min_height`, and the public digest is
`sha256 publicBin` (kernel).
-/

namespace NpUdrStark

theorem certificate : ArenaExpectedInst.expectedType :=
  certificate_of ZkFormal.Near.Render.render_stmt_closed ZkFormal.NearAssembly.near_min_height
    _ _ _ _ _ _ _ _ _ rfl (by decide) (by decide) (by decide +kernel)

end NpUdrStark
