-- Design-phase proofs of concept (docs/zk-formal/DESIGN.md §10).
import ZkFormal.Potential
import ZkFormal.BadQuery
import ZkFormal.Product
import ZkFormal.Collision
import ZkFormal.Game
import ZkFormal.LineLemma
import ZkFormal.Params
import ZkFormal.Bcs.Log
import ZkFormal.Bcs.Wide
import ZkFormal.Bcs.Commit
import ZkFormal.Bcs.Merkle
import ZkFormal.Bcs.Extract
import ZkFormal.Bcs.MmcsDefs
import ZkFormal.Bcs.Statements
import ZkFormal.Bcs.Compose
import ZkFormal.Bcs.Game2
import ZkFormal.Bcs.Budget
import ZkFormal.Bcs.InvPot
-- Lane L1 (algebra): BabyBear, its degree-8 extension, polynomials, RS codes.
import ZkFormal.Air.Basic
import ZkFormal.Air.Export
import ZkFormal.Stark.Field
import ZkFormal.Stark.Params
import ZkFormal.Stark.Iop
import ZkFormal.Stark.Bcs
import ZkFormal.Stark.Protocol
import ZkFormal.Stark.Verifier
import ZkFormal.Stark.Instance
import ZkFormal.Stark.Statements
import ZkFormal.Stark.Compose
import ZkFormal.Stark.Laws
import ZkFormal.Stark.ParseLemmas
import ZkFormal.Algebra.Transport
import ZkFormal.Algebra.NatPrime
import ZkFormal.Algebra.Fp
import ZkFormal.Algebra.QuadExt
import ZkFormal.Algebra.Fp8
import ZkFormal.Algebra.Poly
import ZkFormal.Algebra.RS
import ZkFormal.Algebra.Decode
import ZkFormal.Algebra.Statements
import ZkFormal.Algebra.PolyLemmas
import ZkFormal.Algebra.PolyRoots
import ZkFormal.Algebra.DecodeCount
import ZkFormal.Algebra.Compose
import ZkFormal.Algebra.RSProofs
import ZkFormal.Algebra.Main
import ZkFormal.Bcs.Mmcs
-- L3: IOP facts in the unique-decoding regime.
import ZkFormal.Udr.Count
import ZkFormal.Udr.Code
import ZkFormal.Udr.Poly
import ZkFormal.Udr.RS
import ZkFormal.Udr.Statements
import ZkFormal.Udr.Fri
import ZkFormal.Udr.GrandProduct
import ZkFormal.Udr.Compose
-- Lane L4: AIR DSL and protocol/verifier model.
import ZkFormal.Stark.NpBounds
import ZkFormal.Stark.QueryBound
import ZkFormal.Bcs.StarkAdapter
import ZkFormal.Bcs.StarkParse
import ZkFormal.Bcs.StarkChain
import ZkFormal.Bcs.StarkDecode
import ZkFormal.Bcs.StarkOpen
import ZkFormal.Bcs.StarkAlign
import ZkFormal.Bcs.StarkRefine
import ZkFormal.Bcs.MultiproofRead
import ZkFormal.Bcs.Multiproof
import ZkFormal.Bcs.StarkMain
import ZkFormal.Bcs.Final
import ZkFormal.Stark.SchedOk
import ZkFormal.Udr.BW
import ZkFormal.Udr.Main
import ZkFormal.Udr.Deep
import ZkFormal.Udr.Rbr
import ZkFormal.Udr.Np.Sem
import ZkFormal.Udr.Np.Stage
import ZkFormal.Udr.Np.Statements
import ZkFormal.Udr.Np.Compose
import ZkFormal.Udr.Np.Domain
import ZkFormal.Udr.Np.QueryParts
import ZkFormal.Udr.Np.QueryFacts
import ZkFormal.Udr.Np.Query
import ZkFormal.Udr.Np.Good
import ZkFormal.Udr.Np.ShapeLate
import ZkFormal.Udr.Np.FrameFri
import ZkFormal.Udr.Np.Late
import ZkFormal.Udr.Np.Commits
import ZkFormal.Udr.Np.SchedFri
import ZkFormal.Udr.Np.Avail
import ZkFormal.Udr.Np.FrameMsg
import ZkFormal.Udr.Np.Bridge1
import ZkFormal.Udr.Np.Bridge2
import ZkFormal.Udr.Np.Bridge3
import ZkFormal.Udr.Np.Bridge4
import ZkFormal.Udr.Np.Bridge5
import ZkFormal.Udr.Np.Bridge6
import ZkFormal.Udr.Np.Bridge7
import ZkFormal.Udr.Np.Shape
import ZkFormal.Udr.Np.Frame
import ZkFormal.Udr.Np.Facts
import ZkFormal.Udr.Np.Early
import ZkFormal.Udr.Np.Ali
import ZkFormal.Udr.Np.Bus
import ZkFormal.Udr.Np.BusRounds
import ZkFormal.Udr.Np.Degree
import ZkFormal.Udr.Np.Chal7
import ZkFormal.Udr.Np.Hom
import ZkFormal.Udr.Np.AuxChain
import ZkFormal.Udr.Np.Msg4
import ZkFormal.Udr.Np.Shape8
import ZkFormal.Udr.Np.Deep8
import ZkFormal.Udr.Np.Global8
import ZkFormal.Udr.Np.Msg8
import ZkFormal.Bcs.TransDefs
import ZkFormal.Bcs.TransStatements
import ZkFormal.Bcs.TransCompose
import ZkFormal.Bcs.DecPush
import ZkFormal.Bcs.PosCount
import ZkFormal.Bcs.TransFinal
import ZkFormal.Bcs.DecQuery
import ZkFormal.Stark.L2Facts
import ZkFormal.Stark.ChunkBound
-- Lane L5: SHA-256 block table (statements, composition, generator).
import ZkFormal.Sha.Compose
import ZkFormal.Near.Compose
-- Lane L6 sub-lane L6-sound: relational spec ⇒ NearRelation (good_sound).
import ZkFormal.Near.Spec.Sound
import ZkFormal.Near.BudgetCheck
import ZkFormal.Near.Spec.Complete
import ZkFormal.Near.Main
import ZkFormal.Sha.Frame.All
import ZkFormal.Sha.Sound.Block
import ZkFormal.Sha.Sound
import ZkFormal.Sha.Complete.All
import ZkFormal.Near.Extract.SortProof
import ZkFormal.Near.Extract.WalkProof
import ZkFormal.Near.Extract.AcctProof
import ZkFormal.Udr.SumR
import ZkFormal.Udr.Np.DeepSem
import ZkFormal.Udr.Np.Main
import ZkFormal.Near.NpOkCheck
-- Lane L6 sub-lane L6-link: views + SHA contract + bus balance ⇒ Good (LinkStmt split).
import ZkFormal.Near.Link.Compose
import ZkFormal.Near.Extract.MrkProof
import ZkFormal.Near.Render.Compose
import ZkFormal.Near.Link.Main
import ZkFormal.Near.Final
