import ArenaExpectedInst
import ReexecWitness.Obligations
import ReexecWitness.PublicBin

/-!
# The certificate

Its type, `ArenaExpectedInst.expectedType`, is generated by the judge
(native-lean route): `ArenaExpected.expectedTypeFor ReexecWitness.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest
toolchainId ReexecWitness.Model.verifier }`. Every literal in it (profile,
fuel, `maxProofBytes`, digests, toolchain id) is fixed by the judge; the proof
below works for any of them except `maxProofBytes < 3 088 869` and a public
digest other than `sha256 publicBin`.
-/

namespace ReexecWitness

/-- ATTACK: certified only for single-receipt batches (an extra domain
hypothesis that does not hold for the challenge's `maxBatch`). -/
theorem certificate (hdom : NearSpec.Params.maxBatch = 1) :
    ArenaExpectedInst.expectedType :=
  admission _ _ _ _ (by decide) publicBin _ _ _ (by decide +kernel)

end ReexecWitness
