import ArenaExpectedInst
import ReexecV3D0.Obligations
import ReexecV3D0.PublicBin

/-!
# The certificate

Its type, `ArenaExpectedInst.expectedType`, is generated by the judge
(native-lean route): `ArenaExpected.expectedTypeFor ReexecV3D0.Model.verifier`
= `AdmissionStatement params { publicDigest, impl := .nativeTrusted binDigest
toolchainId ReexecV3D0.Model.verifier }` with `params =
NearSpecV3.challengeParamsWith …` (challenge `near-chunk-validation-d0`,
`spec/lean/judge/ExpectedV3D0.native-lean.lean.template`). Every literal in it
(profile, fuel, `maxProofBytes`, digests, toolchain id) is fixed by the judge;
the proof below works for any of them except `maxProofBytes < 8 388 641` and a
public digest other than `sha256 publicBin`.
-/

namespace ReexecV3D0

theorem certificate : ArenaExpectedInst.expectedType :=
  admission _ _ _ _ (by decide) publicBin _ _ _ (by decide +kernel)

end ReexecV3D0
